### ISSUE TITLE
Sequence links use image ID instead of sequence ID

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#1042]
Hidden with the picture information, there is a sequence key with a link such as http://www.mapillary.com/map/s/lJBB9RAnvIZ4DgvRLTQdWA.

These links have never worked for me. I'm just getting an empty screen with the standard Mapillary header.

~~This is probably caused by the API request (https://a.mapillary.com/v2/s/lJBB9RAnvIZ4DgvRLTQdWA?client_id=MkJKbDA0bnZuZlcxeTJHTmFqN3g1dzo1YTM0NjRkM2EyZGU5MzBh) returning a 404 not found.~~

The links are not working, because the link uses the wrong ID.

**Comment by pyrog** [comment]
> This is probably caused by the API request returning a 404 not found.

No :wink: 
This is because the link use the **image key**, not the ** sequence key** :laughing: 

[![wrong key](https://cloud.githubusercontent.com/assets/2158081/7897091/afd6ebd0-06cf-11e5-87bd-e4b5a7e58c64.png)](http://www.mapillary.com/map/im/a-kJMIMleIwjPzsN0v9o0w)

* Link with **image key** [https://a.mapillary.com/v2/s/a-kJMIMleIwjPzsN0v9o0w](https://a.mapillary.com/v2/s/a-kJMIMleIwjPzsN0v9o0w?client_id=MkJKbDA0bnZuZlcxeTJHTmFqN3g1dzo1YTM0NjRkM2EyZGU5MzBh) return
```
{"code":"not_found","message":"Resource not found"}
```

* Link with **sequence key** [https://a.mapillary.com/v2/s/M6hu-lNBh6oF0YTBzvd4nw](https://a.mapillary.com/v2/s/M6hu-lNBh6oF0YTBzvd4nw?client_id=MkJKbDA0bnZuZlcxeTJHTmFqN3g1dzo1YTM0NjRkM2EyZGU5MzBh) return    
```
{"boundary":{"min_lat":47.03208194,"min_lon":5.9671788,"max_lat":47.0336192,"max_lon":5.96745522},"captured_at":1432833284840,"cas":[304.624066591263,307.940946102142,309.462796092033,309.052274346352,306.937398433685,306.745919942856,11.8239059448242,10.1466464996338,8.09623694419861,10.3927178382874,16.0035837888718,20.9181463718414,20.5331950187683,19.7576639652252,26.4225286245346],"coords":[[5.96722258,47.03208194],[5.96719637,47.03225923],[5.96720925,47.03239451],[5.96723325,47.03250266],[5.96720137,47.03260069],[5.9671788,47.03262892],[5.96720089,47.03270326],[5.96720989,47.0328469],[5.96724306,47.03293973],[5.9672347,47.03314155],[5.96726785,47.03322294],[5.96731383,47.03331195],[5.96735559,47.03342687],[5.9673954,47.03353425],[5.96745522,47.0336192]],"key":"M6hu-lNBh6oF0YTBzvd4nw","keys":["a-kJMIMleIwjPzsN0v9o0w","E_o6plN6pxzWDpVZhOcrTQ","z0QbIwoBE6R8jQ0xN9DFnQ","ZvyBqfuCOUtpaiKTUL-Otg","5-nM6qVywsLMVtPRl21zaQ","3No_TYZI-kvGIAOb5SCm1g","QEcsFxQb0d4LGSueo-2tbg","VCyKCL0lxJDlM_mEypz_kg","bGJNVhtqkPo_Z0ZePVGI6w","uYQahmwh3vuLw-Te5NThEg","p6GkXPPE6O5SfDJZq54Adw","RTkn_LWYKP4JLk3SgiffdQ","qj6yVqR4IVR1odj8PwSFDg","x3rWu8T9uF1-wSZzuSom0A","gruLC17Rr2sUozDJtKW-KA"]}
```

**Comment by it4workflow** [comment]
starting with http://www.mapillary.com/map/im/PGMnRxRhxjcvYvXOlq_zuA you can see, that the sequence link got the image id, not the sequence id!

**Comment by pbb72** [comment]
Thanks! I updated the issue with more precise information.

**Comment by jesolem** [comment]
Should be a quick fix for @knikel

**Comment by knikel** [comment]
:wrench: :boom: :hammer:  Fixed, sorry about the hassle!

Bear in mind that the behaviour of linking to sequence directly defaults to the very first image in that sequence and changes the url afterwards.
