### ISSUE TITLE
Problems editing photos in one specific sequence

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#1058]
I'm sorry for not being able to provide a more descriptive title, but I'm having several weird problems editing the photos in this sequence: http://www.mapillary.com/map/im/S0uSZoLbgBH5oJnf6sDgoA

* After I move one of the photos, the red line connecting all photos is not updated:

![image](https://cloud.githubusercontent.com/assets/1436366/7913699/5ad88dba-0872-11e5-95c2-f772b0b2a342.png)

* Then when zooming out, none of the lines are updated, some lines disappear, and I can't even drag the map around anymore (I could still drag after the first action, moving one of the photos):

![image](https://cloud.githubusercontent.com/assets/1436366/7913727/83fbda12-0872-11e5-9b35-c314b93909b7.png)

* I can still zoom in to the map, but the lines are not zoomed in:

![image](https://cloud.githubusercontent.com/assets/1436366/7913808/0a01d47c-0873-11e5-9b9f-62a1a5fee0ef.png)

I have this problem on both Chrome and Firefox, with all the photos in this sequence, but it seems only in this sequence.

**Comment by pbb72** [comment]
Not a single reply for over a year, and then closed before we can verify that the problem is actually fixed. I hope you guys are going to be better at following up bugreports after the re-launch, because over the last year your lack of feedback has been very frustrating.

**Comment by knikel** [comment]
@pbb72 I'm sorry you took my actions this way. As you've seen I did a sweep through issues on June 1st, to see which ones will be fixed by the release that will be visible in ~2 hours. The interface is going to change fundamentally and I'm only closing issues that have been implement and I know fixed functionality/irrelevant do to the interface/technology changes. You're right that I should close them when we've released, but I'd prefer users to file new ones (in case something goes funky) with new context, instead of one with screenshots from the previous iterations of mapillary.com. I promise I, and now the rest of the front-end team, will do better job on following up on bug reports. I'm sorry you took it that way. Kamil.
