### ISSUE TITLE
UI Behavior W/ Density Of Pictures ( A Use Case Sort Of Thing )

### ISSUE THREAD

**Issue by AllenGraetz** [mapillary/mapillary_issues#1117]
If you're looking to see how well things work with a lot of pictures, this area should be a decent source.

http://www.mapillary.com/map/im/H3bcVflCv8HoNeBml4fofQ

Beside walks around the neighborhood, there will be a lot of sequences coming from here and going down the Alcoa Highway ( US 129 ).
For example,

Seq 1
http://www.mapillary.com/map/im/v6Etgzy4fB0h8yzzCwtI5Q

Seq 2
http://www.mapillary.com/map/im/v_wMhNHm-_NZecRTj5367w

**Comment by jesolem** [comment]
Thanks!

**Comment by knikel** [comment]
We'll have persistent map filters in the upcoming release of mapillary.com, that should help such situations. Impressive coverage!

**Comment by knikel** [comment]
We do have persistent filters nowadays, see e.g. https://www.mapillary.com/app/?focus=map&pKey=H3bcVflCv8HoNeBml4fofQ&lat=35.97144065009026&lng=-83.9193970673915&z=18.529984866956383&dateFrom=2017-03-01&dateTo=2017-04-01 however we still need to load a LARGE tile with all these points.

I'm closing this issue since we have a feature which allows to filter such dense views, but I'm also looping in @amahon so we can work on data, rendering and speed performance for such areas.
