### ISSUE TITLE
Problems uploading photos from Android app

### ISSUE THREAD

**Issue by jrcarlsen** [mapillary/mapillary_issues#1125]
My phone has been uploading photos all night, thousands of them. But they do not disappear from the upload queue (review photos) and they do not show up in my profile.

The upload was interrupted in the morning as I went to work.

The application is not reporting any errors and I don't know if this is a general problem with this version, or if it is unique to my setup.

Let me know what kind of information I can provide for troubleshooting.

Mapillary v1.28 (beta)
Android 5.0.1
Samsung Galaxy Note 4

**Comment by simonmikkelsen** [comment]
Same issue here - was just about to report it.

The problem is only on this phone and only when not selecting "Take low resolution images". I have had this problem for all the time I have used Mapillary (since Apr 21, 2015).

A zip file with around 1 GB of images that always causes this issue can be downloaded from http://simonmikkelsen.dk/files/mapillary.zip

It seems that some of the images are uploaded and on the map, but not deleted from my phone. I have seen the phone create images for Mapillary up to 13 MB. The python upload scripts have failed on them too, with an error from Amazon stating the file was too large (sorry I didn't save the error message). The images uploads fine if I recompress them with ImageMagick and upload them using the python scripts.

Phone: Sony Xperia Z2
Mapillary version 1.24 (newest from Play Store)

**Comment by peterneubauer** [comment]
This is because of the upload toke the not being correct. @gyllen could you take a look at the python scripts and switch to the new token so a can update the Android app asap?

**Comment by jrcarlsen** [comment]
The updated fixed the issue, it now works on:

Mapillary v1.29 (beta)
Android 5.0.1
Samsung Galaxy Note 4

**Comment by polarbearing** [comment]
Testing v.1.29 with a batch of 25 pictures, and I don't get them uploaded. In the second attempt, I watched the upload traffic, and it used the full bandwith, with a few gaps of about a minute long, until all 25 were processed. The notification says 'done with problems, 0 of 25 uploaded', and all remain in the upload folder. All fail in the trace with status 403. Log excerpt below, full available. 

```
Tue Jun 30 16:27:39 CEST 2015 : app.mapillary.android.activity.Utils  - WiFi: true, Ethernet: false
Tue Jun 30 16:27:39 CEST 2015 : app.mapillary.android.sync.NetworkMonitor  - We have Wifi or Ethernet Connection.
Tue Jun 30 16:27:39 CEST 2015 : app.mapillary.android.sync.NetworkMonitor  - No Wifi Sync preference, not syncing
Tue Jun 30 16:27:41 CEST 2015 : app.mapillary.android.service.MapillaryServerFacade  - getTokens: HTTP/1.1 200 OK
 ...
Tue Jun 30 16:30:25 CEST 2015 : app.mapillary.android.sync.UploadService$SendFileTask[2]  - upload status: 403
 ...
Tue Jun 30 16:46:14 CEST 2015 : app.mapillary.android.sync.UploadService$SendFileTask[0]  - upload status: 403
Tue Jun 30 16:46:14 CEST 2015 : app.mapillary.android.sync.UploadService  - Done, errors Network error
```

**Comment by polarbearing** [comment]
Downgraded to 1.24 and uploaded that batch smoothly, and without gaps in the traffic.

**Comment by polarbearing** [comment]
Took pictures with 1.29 (which works much better in shooting even in 1 sec mode, which never worked before), but cannot upload them with 1.29. Downgraded to 1.24 and uploaded them successfully. Thus we can exclude the problem that the pix in the previous test were older. 

Can we reopen the issue?

**Comment by polarbearing** [comment]
The above problems were with the version labelled 1.29, from Dropbox 28 June. Today I tested the version also labelled 1.29, from Dropbox 4 July. Seems the upload problems are gone. 

Still it is a pain to report bugs with different versions having the same release number. Can we have some unique build numbers in them?
