### ISSUE TITLE
proposal for a new logic for taking sequences in the apps

### ISSUE THREAD

**Issue by HolgerJeromin** [mapillary/mapillary_issues#1135]
Here is my proposal of a new logic for taking images in the apps in pseudocode.
would solve #242, #247 and #819. #1006 is optional here.  I am not sure how to include #229 into this :)

    if(distance to last image > 300 meter){
        start new sequence
    }
    
    if(low battery){
        //or something smarter with SystemOS events
        if(riding mode || walkingAuto mode)
            recall after getprefs(autopausedelay)
    }else if(low disk space){
        //or something smarter, phone could be able to upload since the last event
        if(riding mode || walkingAuto mode)
            recall after getprefs(sequence frequency for this mode)
    }else if(still processing){
        //skipping
        if(riding mode || walkingAuto mode)
            recall after 200 ms
    }else if(phone shakes && getprefs(pause on shake)){
        //skipping
        if(riding mode || walkingAuto mode)
            recall after 200 ms
    }else if(user pushed volume key && getprefs(activate vol key)){
        //user push have prio to distance, tilt, time or pointing down
        taking image
        remember timestamp, location
        if(riding mode || walkingAuto mode)
            recall after getprefs(sequence frequency for this mode)
    }else if(pointing downwards){
        //skipping
        if(riding mode || walkingAuto mode)
            recall after getprefs(autopausedelay)
    }else if(phone tilted && getprefs(pause on tilted)){
        //skipping
        if(riding mode || walkingAuto mode)
            recall after 200 ms
    }else if(distance to last image > 10 meter){
        //force taking image as we missed too much
        take image
        remember timestamp, location
        if(riding mode || walkingAuto mode)
            recall after getprefs(sequence frequency for this mode)
    }else if( speed<2 && getprefs(pauseonstop) && (riding mode||walkingAuto mode)){
        //skipping
        if(riding mode || walkingAuto mode)
            recall after getprefs(autopausedelay)
    }else if( timestamp of last image > getprefs(sequence frequency for this mode)){
        take image
        remember timestamp, location
        if(riding mode || walkingAuto mode)
            recall after getprefs(sequence frequency for this mode)
    }

**Comment by jesolem** [comment]
thanks @HolgerJeromin

**Comment by peterneubauer** [comment]
Awesome, thanks! Will check this against the existing logic and see if applicable!

**Comment by HolgerJeromin** [comment]
Imo the logic is valid for all apps. iOS, android, firefox and Windows phone.

**Comment by vincentdephily** [comment]
This looks good. My current pet peeves on Android 1.39 is that most errors (like shaking, couldn't focus, tilted...) should get a quick retry (200ms sounds good), and that the too_slow error should compare to the position of the last successful photograph rather than the position of the last phtograph attempt.

**Comment by naoliv** [comment]
In `else if(distance to last image > 10 meter)` please make it `else if(distance to last image > gps_precision())` ie, if the GPS precision is 3m and we moved 4m, then take a picture.

I am losing so many pictures when the car is moving slowly...

**Comment by HolgerJeromin** [comment]
@rsahlin I read you changed some capture logic in version 2.0
Is my proposal still needed? 
Especially the quick retest after shake or busy and the distance check for the last image (for very slow drives) are the most important changes.

**Comment by rsahlin** [comment]
Hi Holger and thanks for your comment!

Yes, one fundamental change is that the activity will synchronize to capture completed.
This means that the app wakes up after camera completes capture of a photo.
At the moment I just wait for sequence delay timeout but will implement capture driven by distance #247 

Pause on shake is no longer default option, the goal is to have a focus mode that uses a fast shutter so that normal shake should not provide blurry images (due to shaking)
This blurryness obviously has to do with the exposure time, in the future it could be insteresting to look into how situations where the exposure time is long should be handled.

Please look into version 2.X and see what features you think are needed, apart from #247, and create new issues if needed.

In the meantime I will close this issue - thanks for input and comments from all!

**Comment by HolgerJeromin** [comment]
> Pause on shake is no longer default option

Then the settings should be labeled different. Right now the text suggest that pause is a good option to set.

**Comment by rsahlin** [comment]
Done - it is coming in the 2.20 release :-)
