### ISSUE TITLE
sequence lines often not shown

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#1196]
with the new interface, sequence lines do not seem to be displayed in many cases.

for example, this image :
https://www.mapillary.com/map/im/URjvnlItL-v2v9lxgJ3SzQ/map

tested with firefox 39.0 and vivaldi 1.0.233.3 - the sequence line just does not show up at all

**Comment by knikel** [comment]
Could this be a tiles issue, @gyllen? They seem to be interpolated correctly in other areas.

**Comment by gyllen** [comment]
Yes its just new seuences, it should catch up soon though

**Comment by bertdeb** [comment]
I added a bunch of photos around Vista Park 5 days ago. As soon as you zoom in, the sequences disappear:
http://www.mapillary.com/map/search/45.43044069404402/45.45995577692011/-75.49353547186004/-75.43386872093338
And in iD editor for OSM, the sequence for the East and South sides of the park don't show up at all.

**Comment by gyllen** [comment]
@bertdeb I think its a matter of that we do not generate all zoom levels for vector tiles yet. The images are there. Why they are not shown in iD is a different question though. @peterneubauer could that be a limitation of how many images you get in the API call?

**Comment by peterneubauer** [comment]
Yes, in ID there are only 1000 points loaded at a time, since otherwise the iD SVG would be overloaded with layers. We need time ordering in the Mapillary API in order to make that e.g. the latest 1000 photos in order to satisfy your requirement. Right now these are random 1000 photos, potentially missing your new ones.

**Comment by moenk** [comment]
Since a few days I don't have maps when I open any sequence, map field stays gray in FF 39, but in IE it works fine. Error messages in web console: 
Error: WebGL: Refused to create ANGLE OpenGL context because of blacklisting. mapbox-gl.js:186:831
Error: WebGL: Refused to create native OpenGL context because of blacklisting. mapbox-gl.js:186:831
Error: WebGL: WebGL creation failed. mapbox-gl.js:186:831

**Comment by jfburke3** [comment]
I'm still finding sequences that aren't showing up on the map as lines, even though they're over a week old (and often even older than that).  However, because I know they're there, I can select them, at which point the line (usually) shows up on the map.

**Comment by moenk** [comment]
WebGL-problem on AMD graphics adapter solved with driver update.

**Comment by gyllen** [comment]
@jfburke3 Can you paste some examples?

**Comment by gyllen** [comment]
Fixed in new tiles
