### ISSUE TITLE
New blur editor highlights the unrequested rectangles, not the requested ones (to be removed)

### ISSUE THREAD

**Issue by polarbearing** [mapillary/mapillary_issues#1204]
When I use the new blur editor in the new GUI, and I remove some of the blurs, the removed ones remain red, while the untouched blur changes to orange with my username attached to it. 

Should be the opposite?

Maybe the confusion comes from removing unnecessary blurs. When I add a new one, the orange is logical.

**Comment by polarbearing** [comment]
Probably the pending removals should be given a third colour. That also helps, not to try a blur-removal again while one is still pending.

**Comment by gyllen** [comment]
@polarbearing good idea

**Comment by knikel** [comment]
@polarbearing Fixed, thanks for the feedback. We've decided not to introduce another color with meaning. It should be less confusing now.

A little explanation: So as the photo is _touched_ whether with removal of blurs and new additions it will have the blurs marked only in orange with the data who was the last one that requested/removed blurs on the given photo. Bear in mind that the **to be approved** state marks all markers as orange, even though I just blurred the face in the photo below - there is no point in distinguishing which blurs were touched or not touched by the user because photo has to be approved as a _whole_ and cannot be edited by other users until approved/denied.

![blurs](https://cloud.githubusercontent.com/assets/1574656/9007663/cec27722-3793-11e5-8c91-9d615a383d3d.png)
