### ISSUE TITLE
EXIF of camera manufacturer and model in metadata?

### ISSUE THREAD

**Issue by moenk** [mapillary/mapillary_issues#1244]
I'd like to see the combined camera manufacturer and model string in the picture viewer in the metadata. Also it would be nice if the API can return this.

**Comment by gyllen** [comment]
We have no plans at supporting this at the moment. Im closing this issue, but please write why you would want this here and we might change our minds :)

**Comment by richlv** [comment]
don't know about the reporter, but personally i'm quite often interested "what did they use to take such good pics". or sometimes the opposite :)

**Comment by shlublu** [comment]
+1 @richlv, me too.

**Comment by moenk** [comment]
I'd like to compare resulting pictures of various brands and models, see which works good or not. As EXIF is stripped from downloaded pictures and not available from the API it would be enough to see this data in the picture details in the web view. Finally this should also mean better pictures for mapillary because it helps users when buying their next smartphone or camera.

**Comment by de-vries** [comment]
I've got to say that I also feel the oddly desire to see the camera make...

**Comment by jesolem** [comment]
Would make sense in the photo details section in the web view, agree. We should add to the backlog but low priority.

**Comment by gyllen** [comment]
Reopening

**Comment by GITNE** [comment]
At first glance, this seems like a reasonable request. Yet, some privacy issues with that kind of meta data may exist because not all users may be aware that they would be giving away this data to anybody. It is one thing for Mapillary to collect this data, for various reasons - may it be for debugging Mapillary apps, user support, or statistics. But it is another thing for Mapillary to redistribute meta data about a specific user's device to anybody. If such a feature shall become to exist then I think it should be reflected in Mapillary's terms of service and/or privacy policy. And, users should be free to decide to opt-in if they want to share meta data about their devices with third parties.

**Comment by jaakkoh** [comment]
I would also very much like to see the camera make & model for reasons noted above. To add to the  quality evaluation needs -- I think it goes both ways:

Just recently I wanted to [give examples of bad/blurry images](http://forum.mapillary.io/t/better-than-nothing-approach/373/5) from a specific stretch of a drive that I had recently captured. The thing was/is that for parts of this drive I captured with both my Galaxy S5 and my Galaxy Note 10.4 -- and I would have wanted to reference specifically the photos from my S5 since that gives quite clearly inferior photos in low light conditions.

Well, it took me a bit of time to figure out what photos were taken with which camera as the photo details don't even show the original size of the photo. Seeing the model of the camera would have made finding the photos I wanted to reference super easy. And, in fact, I'm not sure if I got the right photo eventually or not. I did find [a reasonably blurry one for the purpose](http://www.mapillary.com/map/im/43XqF7Nma8z62w8Usk2Frw/photo) of this example but now looking at it quite possibly the one(s) taken with the S5.

An additional twist for the above reason(s) to see this information -- and search for sequences taken by a given camera is that it would allow targeting reviewing of e.g. blurry images, which some cameras are much more prone to.

As for potential privacy issues raised by @GITNE , I think it's a valid question as IMO privacy issues always are. I wouldn't have come to think of it. But Mapillary wouldn't be the first nor the second "photo sharing service" to publish this information. It's not to say that there are no issues or concerns about it. But I think it means that by looking at how e.g. Flickr has handled this there is no need to reinvent the wheel.

**Comment by moenk** [comment]
It should be easy to add an opt-out in the profile, besides I think all uploaders agree with the use of metadata anyway: Otherwise they would not contribute, the purpose of Mapillary is the use of pictures and particularly their metadata, GPS position in first instance.

**Comment by GITNE** [comment]
> As for potential privacy issues raised by @GITNE , I think it's a valid question as IMO privacy issues always are. I wouldn't have come to think of it. But Mapillary wouldn't be the first nor the second "photo sharing service" to publish this information. It's not to say that there are no issues or concerns about it. But I think it means that by looking at how e.g. Flickr has handled this there is no need to reinvent the wheel.

By looking from the outside, one can not say much about how Flickr handles device meta. All I can see is that this data is redistributed but not why. So, I do not know how Flickr handles device meta data privacy. And, just because other services are not concerned about meta data privacy or deliberately just ignore this issue does not make it right. Generally speaking, if you look around all sorts of internet services, there are still a lot more "wheels" to invent in the privacy sector. Actually, I am certain that when historians will be looking back at the early forming ages of the internet they will most probably majorly condemn the terrible privacy policy record of most major internet companies.

Effectively, the issue with device meta data comes down to the same questions of risk assessment when sharing data or meta data publicly, like I have already commented in #1390.

> It should be easy to add an opt-out in the profile, besides I think all uploaders agree with the use of metadata anyway: Otherwise they would not contribute, the purpose of Mapillary is the use of pictures and particularly their metadata, GPS position in first instance.

No, publishing any data and meta data that is not required by the basic Mapillary service, like image content and location data should be **opt-in** for users.
@moenk, calm down your ego and desires. Just because *you* cannot restrain *your* *personal* eagerness about other people's devices to a respectful level does not mean that others do not have a problem sharing this data. However, you can ask for this data politely. Hence, in this context this means to give users an option to **opt-in**.

**Comment by jesolem** [comment]
I also want to see make and model and @gyllen and I was just discussing exposing this in tiles and API. Let's do this. 

Once it is there, we can show it on web too.

**Comment by richlv** [comment]
weeeeee, thanks a lot :)

**Comment by gyllen** [comment]
Yeah it will be availble in `V3` 🎉

**Comment by gyllen** [comment]
@ptpt Can you add this as an issue internally (if its not already in `V3`) and close when thats done

**Comment by ptpt** [comment]
Yes, it's added in v3. See `camera_make` and `camera_model` https://www.mapillary.com/developer/api-documentation/#the-image
