### ISSUE TITLE
Play button: Too fast too furious

### ISSUE THREAD

**Issue by yopaseopor** [mapillary/mapillary_issues#1260]
When I click the play button with previously loaded images the track starts to go fast to a high speed...that doesn't allow you to watch any detail and to stop at one concrete photograph.Walk speed should not be the same play speed as Car track. Is it possible to make a speed setting to watch tracks played faster or slower?

**Comment by jfburke3** [comment]
I second this!

**Comment by wasdy** [comment]
The speed of the play button could also be determined by the distance between pictures.

**Comment by shlublu** [comment]
I support this too!

**Comment by oscarlorentzon** [comment]
The transition speed between two images when playing a sequence is now adjusted according to the distance between the images. A longer distance between two images means a slower transition speed, a shorter distance means a faster transition speed. 

This will not result in the meter per second speed being constant when playing a sequence but it will vary less than before when distances between images vary much.

You can e.g. try it here where the actual driving speed varied a lot because of crossings: http://www.mapillary.com/map/im/s7aj0R2oDqAOc9JLU2_ZuA/photo

**Comment by paulinus** [comment]
Are we happy with the current speed of the player?

**Comment by jfburke3** [comment]
Actually...I kinda think it's slightly too slow now.  But I'd rather have too slow than too fast.

**Comment by yopaseopor** [comment]
Why we don't have a speed slider? It would be useful and funny also.

**Comment by paulinus** [comment]
You got it!

https://blog.mapillary.com/update/2017/12/11/mapillaryjs-sequence-playback-speed-direction.html
