### ISSUE TITLE
unprocessed images shown in traffic sign game

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#1276]
traffic sign game today gave me this image :
http://www.mapillary.com/map/im/g4i2FHJpfQSxbZf44jFn8g/photo

only after i had looked at the image a bit, i spotted this below it :
"It is not possible to approve or add traffic sign on this photo yet."

it does not seem to make much sense to show unprocessed images in the game.

note that despite claiming that the image is unprocessed, it was showing version "1.0" by "Mapillary (trafficsign_eu_1.0) "

**Comment by jesolem** [comment]
Thanks @richlv 

We just bumped the version of the traffic signs, could be related.

**Comment by de-vries** [comment]
@jesolem I don't it's related. I get the same error on all images in the game for the last two days. It's more like the data base doesn't give any signs, so the game decides to display that message. 
Also there is some serious slowness on the site for the last two days, most parts work fine, but blurs load only after 5 minutes or not at all. since today I'm not able to load profile pages any more (stuck on spinner). Most of the profile page loads fine, but some were I get a 503. In the game I also get a 503.

From here it looks like (some part of) your DB or server is misbehaving and causing the problems.

**Comment by jesolem** [comment]
Thanks @de-vries

**Comment by de-vries** [comment]
also, I don't get any tiles or hi res photos in the fall-back version (chromium)

**Comment by de-vries** [comment]
Except for my latest note, all inconveniences seems to be gone, including OP's issue.

**Comment by richlv** [comment]
unprocessed images have not shown up since then, so apparently it was some transient issue - let's close this one :)
