### ISSUE TITLE
API: Allow to edit requested scope

### ISSUE THREAD

**Issue by eMerzh** [mapillary/mapillary_issues#1293]
currently it doesn't seems to be possible to edit the scope you want to request ...
it leave no other choice to create another app (with all the problems that it give)

**Comment by gyllen** [comment]
This is a security issue. Once a user authenticated for a specific scope the app should not be able to authenticate for more. To use scopes read more in the Oauth section of the documentation https://a.mapillary.com/#oauth .

**Comment by eMerzh** [comment]
mmh ok, not sure to understand , but ok ...
it's the point of the scope parameter in the oauth request no? you ask a token for a given user / scope / app combination no? if you need more you should ask a new token , not have a new app ?

So no i've created a app with all scope asked to be sure i  have everything i need (and i still can't lower the number of scope i want)

**Comment by gyllen** [comment]
@emerzh Sorry I thought you misunderstood the concept of oauth. You are right, the scope lies within the user.

Its actually an implemention issue of why you can not change the required scopes. Some of the authentication lies within the token you get back.

So long story short, no at the moment you can not add more scopes to your app once you created it.

Also you might think its confusing that you need to add specific scopes to your app since you actually do ask for them when you enter the connect URL, In theory we could just give the app all possible scopes and then you just oauth for the ones you want. In practice it is good to try to limit the purpose of the app.

Please let me know if you have any more feedback. You are one of the first persons trying it out, \o/

Best
Johan
