### ISSUE TITLE
please disable macrophoto by defoult on mapillary

### ISSUE THREAD

**Issue by proxymi** [mapillary/mapillary_issues#1299]
please disable macro focus possibility  by default on mapillary - otherwise often my camera focuses on the windscreen.

**Comment by jesolem** [comment]
Hi @proxymi
Is this Android or iOS?

**Comment by proxymi** [comment]
this is iOS iphone

**Comment by millenbop** [comment]
We are setting focus mode to far (i.e. AVCaptureAutoFocusRangeRestrictionFar). I don't think there is much more we can do, but I'll do some research and see if there is something else we can do.

**Comment by millenbop** [comment]
Sorry forgot to comment on this. 

It is possible to set the focal distance manually since iOS8. I did some testing and it's very hard to predict what focal length would be good for all use cases and Apple warns in the docs that it might not be the same on all devices. Many of my test shots with fixed focal length came out blurry but are pretty much always sharp with AF.

I think what we do know, setting the auto focus range to "far", is the best option.

The best you can do is to place the phone close to the windscreen as possible and make sure it's clean so it cannot focus on dirt etc. Placing it close to the windscreen also helps with reflections.

Closing for now.
