### ISSUE TITLE
Viewer : weird Photosphere view

### ISSUE THREAD

**Issue by Stefal** [mapillary/mapillary_issues#1302]
There are still some problems with the photosphere view, I can't see it as a 360° picture : 
http://www.mapillary.com/map/im/BumrfNtDmR_9oMClvCMeFA/photo

**Comment by oscarlorentzon** [comment]
This should indeed be shown as a 360° panorama and not a cropped one as is currently the case. We will look into it.

Thanks for reporting @Stefal !

**Comment by mbirth** [comment]
It's shown as a 360° sphere for me (Chrome, Windows), but I can only turn around until the image "ends". I expected to be able to make seamless/endless 360° turns.

**Comment by shlublu** [comment]
Same as @mbirth here.

**Comment by oscarlorentzon** [comment]
Thanks for updating the status on this issue @mbirth and @shlublu.

We have made some improvements in the way we handle panoramas in general recently which made this photo appear correclty. The ability to look around 360° (horizontally) without stops now also works.

For the record: The panorama photo discussed in this issue is actually a cropped one. It has full width but it does not have full height. Compare with the following full 360° panorama to see the difference when looking up or down:

http://www.mapillary.com/map/im/kWh29NJu5HeDc4af7AfLIA/photo
