### ISSUE TITLE
Change requests limited to 100 changes per request

### ISSUE THREAD

**Issue by shlublu** [mapillary/mapillary_issues#1315]
I'm discovering this message: "We currently can not accept more than 100 change sets at once. Please make sure you submit less than 100 change sets in one request."

One of my change request consisted in making precise the 136 (as far as I remember) points of this sequence on a location and orientation standpoint: https://www.mapillary.com/map/im/vMeSYltnzhwxuTY3K-Q6wg/photo

Doing this took me a while, is that change request lost?

**Comment by pbb72** [comment]
This is a weird limitation. It was my understanding, that one change set = one request. Meaning, I can ask to change many photos in one change set, and submit that as one request.

If the real limit now is that only 100 *photos* can be changed in one change set, than this will indeed make things very dificult. It will basically make the tool to change the angle of all images in a sequence, unusable. Because most sequences contain over 100 photos...

**Comment by polarbearing** [comment]
Is that related to #1203 and #991 ? Though in my case, 322 pics were accepted out of 400-500.

**Comment by peterneubauer** [comment]
This is not a hard limit but related to us having a risk of timeout I am the backend. When we get around to change this to a better data structure for changes, this limit will stop. It's mostly to minimize the risk of loosing a change.

**Comment by shlublu** [comment]
Ok, good to know. Tanks @peterneubauer

**Comment by gyllen** [comment]
We are still investigating this issue.

**Comment by pbb72** [comment]
Could you change the wording to

> We are currently having trouble processing large change requests. Please submit less than 1000 changes in one request.

- This doesn't make it look like a hard limit.
- This makes clear that the reason to the limit is technical, instead of a policy change.
- This fits with the definition of "Change set" you're using elsewhere on Mapillary (1 change set = 1 submit; not 1 change set = 1 changed photo).

**Comment by knikel** [comment]
@pbb72 Updated the wording, thanks for the suggestion. Leaving the issue open until resolved.

**Comment by gyllen** [comment]
Fixed in new version of change set API
