### ISSUE TITLE
link to map in mail sends me to wrong location

### ISSUE THREAD

**Issue by pgiraud** [mapillary/mapillary_issues#1351]
I received a mail in my box telling me that my upload is on the map. However, clicking on the map link, I get redirected to a page with a map located in a wrong place.
It looks like the link points to `/map/search/zoom/lat/lon` where it should be `/map/search/lat/lon/zoom`.

**Comment by HolgerJeromin** [comment]
Perhaps the parsing is wrong since a few weeks. 
`http://www.mapillary.com/map/im/zoom/lat/lon` was active for the old viewer. (and was linked by me for example at [Wikipedia DE](https://tools.wmflabs.org/geohack/geohack.php?pagename=Aachen&language=de&params=50.776666666667_N_6.0836111111111_E_region:DE-NW_type:city%28241683%29))
I can not test, if this link is still valid and shows the center of Aachen.

**Comment by gyllen** [comment]
@knikel Can you check on this?

**Comment by knikel** [comment]
This has been fixed. All URL schemes will work, thanks for reporting!
