### ISSUE TITLE
Picture direction is thoroughly messed up

### ISSUE THREAD

**Issue by ToeBee** [mapillary/mapillary_issues#1354]
I'm not sure what happened but this affects even some of my earliest uploads that I know used to work correctly. Somehow all pictures seem to be oriented towards the northeast instead of the direction that was set in the EXIF data when uploaded. The little arrow in the bottom left corner of the map always points in the same direction (northeast) for all my pictures now. This results in having to move through sequences by using left/right instead of up/down arrows. But if you go into the edit view, the arrows in the pop-ups are indicating the correct direction so maybe this is just a problem with the new viewer?

Examples:
http://www.mapillary.com/map/im/9_BWZZ3cA3tHcyTmEyAxFg/photo
http://www.mapillary.com/map/im/-2Zgnpmt4vW3P6ph0esMQQ/photo
http://www.mapillary.com/map/im/TlL2xTMabXhn1WwuarxA0w/photo

**Comment by paulinus** [comment]
Hi @ToeBee,
The viewer uses the results of SfM to display moving directions and compass angle. SfM is often confused by open skies and moving objects. This leads to flawed directions. The original orientations values are saved, but not used in the viewer right now.
It is a problem we are aware of, and try to solve. Sorry about this, and thanks for sharing the examples.

**Comment by ToeBee** [comment]
> SfM is often broken by Kansas

Fixed that for you :)

But seriously, I think a large majority of my pictures are affected by this. I want to say pictures pointing north or south are less affected than east/west ones but that's from a pretty small sample so I'm not really sure about that.

**Comment by paulinus** [comment]
Some time ago we started [filtering out clouds and other potentially moving objects](https://blog.mapillary.com/tech/2017/07/26/improving-3d-reconstruction-with-semantic-understanding.html) when doing reconstructions.

This fixed the random orientations problem and you no longer get side-way arrows when you are actually moving forward.

Kansas is still a challenging place for visual reconstruction because of the uniformity of the landscape but you get no transition between images rather than a wrong transition.
