### ISSUE TITLE
Sequence incorrectly tilted when using the "Play" button

### ISSUE THREAD

**Issue by ToeBee** [mapillary/mapillary_issues#1362]
See picture: http://www.mapillary.com/map/im/NjD33te7jo4uBYWNbxorxw/photo

Seems ok. But now hit the "Play sequence" button. Suddenly the world tilts!

**Comment by jesolem** [comment]
Thanks @ToeBee 
The play button uses a smooth interpolation based on the 3D reconstructed points. Interesting failure case. Will let @paulinus and @oscarlorentzon debug.

**Comment by ToeBee** [comment]
Kind of figured that's what was going on. Wonder if it is picking out the white line as the most prominent feature or something. Anyway, later on in the sequence it goes completely insane and starts bouncing between rotated and not. Kind of fun to watch actually. A few pictures after this: http://www.mapillary.com/map/im/EAQ9xHNPNrbylnLz5oq-kA/photo

**Comment by oscarlorentzon** [comment]
Thanks again for reporting @ToeBee .

It is quite difficult to get a good reconstruction in areas with no distinctive objects like the one in this sequence. The first problem occurs because we have a faulty indication of what is "up" when we play the sequence. The second problem is not actually related to playing the sequence, the same strange transitions occur when navigation freely with the navigation buttons too. Again the problems arise because it is hard to 3D reconstruct this area. 

We will work on a solution to make this behave better when playing.

**Comment by oscarlorentzon** [comment]
We have now made changes to ensure that the sequence is not tilted when playing anymore. 

Since there are other issues specifically related to strange navigation transitions (#1247 and #1278) like the one you mention in the comment above I'm closing this issue.
