### ISSUE TITLE
update overlay maptiles

### ISSUE THREAD

**Issue by HolgerJeromin** [mapillary/mapillary_issues#1366]
mapillary offers a tile layer for overlay via "http://{s}.tiles.mapillary.com/{z}/{x}/{y}"
I am not sure if they are still used by mapillary itself, but i have this layer as an overlay in osmand for easier trip planing.
But these tiles are a few month out of date. It would be nice, if they would get some love again :-)

follow up from #349

**Comment by balooval** [comment]
+1
Not sure if authorized but i use this layer on my phone (with Locus) for riding on uncovered roads as far i noticed it's not updated.

**Comment by gyllen** [comment]
@HolgerJeromin @balooval Its correct that they are not updated anymore since we have switched to vector tiles. However it seems like that we for the forseeable future still will need the old raster layer, expect it to be starting to update soon again (within a couple of weeks). Closing this, since this is added to internal stack. Reopen if you nothing is updating in a couple of weeks.

**Comment by liskin** [comment]
Any update on this? Couple weeks already passed and the tiles still don't include my trips from half a year ago. I too would like to use this as a map overlay in Locus to plan my trips, but with outdated tiles it's useless. :-(

**Comment by jaakkoh** [comment]
+1 to @liskin 's question. Any chance to get the traces' raster layer updated? Ideally on a continuous or regularly recurring bases. Vector tiles are great but I don't know that a single tool that I am using would support them. Or at least how to get the tools to show (also) vector tiles. (My main Mapillary related tools are: OsmAnd, JOSM, QGIS).

**Comment by jaakkoh** [comment]
BTW, regarding @gyllen 's suggestion to "Reopen if you nothing is updating in a couple of weeks":
Is that something that I would need some additional privileges for? Or does re-opening need to be done via terminal -- or something else? That is, I can't see the option in my Github web interface.

**Comment by gyllen** [comment]
@jaakkoh @liskin Is raster tiles still needed or would you consider using vector tiles instead? I know that some older map systems by now has plugins for vectortiles.

**Comment by jaakkoh** [comment]
Thanks for your super quick note. As said, I don't know of any way to use the vector tiles with _any_ of the tools that I use regularly. And for my Mapillary usage that means the tools listed above. So, yes, raster tiles would be great to have until there's a way to view vector tiles in at least OsmAnd and JOSM (for my needs, others have raised the need for Locus, understandably I should add). I would assume that QGIS would get vector tiles support sooner than the other two -- but JOSM and OsmAnd are the top needs for me. .. Hmm. thinking about it JOSM does actually have a "sort of" way view Mapillary -- through the Mapillary plugin. .. But that limits the viewing area and downloads much more than just the traces..

**Comment by liskin** [comment]
@gyllen If [this](http://help.locusmap.eu/topic/can-i-see-in-my-locus-as-transparent-layer-tiles-from-mapillary) is still true (and I have no reason to believe it isn't) I'm afraid I still need raster tiles.

**Comment by jaakkoh** [comment]
Looking at the areas that I captured (and uploaded) during my summer vacation the raster tiles haven't been updated at least since July of this year, it seems.

**Comment by jaakkoh** [comment]
In regards to #578 -- and in any case -- thinking on this further I (still) feel that this raster/TMS layer would (continue to) be very useful. The thing is that raster layers are used _so_ broadly in all kinds of applications that one can't really dismiss it's significance.

For example I'm currently looking at getting the Managua bus routes fully covered in Mapillary and as things are the only way I can think of doing this is with JOSM. ... But downloading all images to JOSM with my connection is a bit of a PITA. If the TMS layer was updates on a sufficiently regular basis I could simply overlay that on top of the public transport map. Just like I can with OSM GPS traces - like this: http://mc.bbbike.org/mc/?lon=-86.258736&lat=12.13774&zoom=13&num=1&mt0=public_transport&mt-1=ol_osm-gps&mt-1p=100

**Comment by jaakkoh** [comment]
Is there any update to this? The need for raster tiles hasn't gone anywhere and isn't in the foreseeable future. The yet not functioning map-in-camera feature reminded me to check if this has moved forward.

The thing is that as is it's really a PITA to figure out what roads are not mapillaried. TMS service of the coverage would help significantly. It would make it possible to view the map of the area I'm driving on my tablet's OsmAnd (as overlay) while capturing new images with Mapillary. Just to explain my specific most typical need. Just like I did before. You can see the impact of the change in the significant slow-down in Managua's Mapillary coverage since the TMS tiles have not been getting updates.

**Comment by jaakkoh** [comment]
FYI, new interest surfacing to this issue in the forums: http://forum.mapillary.io/t/mapillary-layer-in-osmand/390

**Comment by simonmikkelsen** [comment]
It would be really helpfull to me. I use  OsmAnd to see where I am and where I have been on this trip. Added where others have not mapped would make it possible for me to map efficiently in more areas.
Currently, I have mapped a lot of areas in such detail that it would be really hard to improve on it without doing everything again. The last 10% of coverage are really hard to get and without tool suport I will go for the relaxed version and simply redoing large areas.

I think many tools will take some years to catch up to vector tiles.

**Comment by gyllen** [comment]
Hey guys. We hear you, I think this would be really useful too. @peterneubauer we need to open up the gudrun tile discussion again. I think that would be a beautiful tool. Mapnik seems to have good java bindings for raster tiles.

**Comment by peterneubauer** [comment]
yeah, agreed. Building static raster tiles is probably a good idea for the places where Vector tiles are not possible (yet). Will look into it.

**Comment by govvin** [comment]
Are there on-gong updates to this?

Like many others here, I used to use the tile layer in OsmAnd to let me plan around routes I could take for photo mapping with Mapillary. I still haven't found any decent alternative to this.

**Comment by gyllen** [comment]
@govvin Thanks for reminding us

@ptpt Have you done any work on this?

**Comment by ptpt** [comment]
Yes next week we will design some new styles for the raster tiles, and then bring back them to live. Stay tuned!

**Comment by ptpt** [comment]
Hi all,

Finally, the raster tiles are available at this endpoint: https://d6a1v2w10ny40.cloudfront.net/v0.1/{z}/{x}/{y}.png The tiles are available from zoom level 0 to level 17. (We will add this information to developer documentation soon, together with vector tiles)

We have a demo page showing these tiles: http://mm.mapillary.io/raster_tiles.html

Thank you all for the input!

Tao

**Comment by govvin** [comment]
I'm excited about this. The web demo works great, but on OsmAnd nothing is showing up.

**Comment by pbb72** [comment]
@govvin Works great in OsmAnd for me, but beware that you need to use {0}/{1}/{2} instead of {z}/{x}/{y}

**Comment by peterneubauer** [comment]
Would be great with a OSM post about this so people know how to use it @pbb72 ?

**Comment by govvin** [comment]
That's what I missed @pbb72.  Thanks!

**Comment by pbb72** [comment]
I've posted a (very) short article at https://www.openstreetmap.org/user/Peter%20Bremer/diary/39986

**Comment by peterneubauer** [comment]
Awesome, good piece, thanks!

**Comment by HolgerJeromin** [comment]
The old url was a.tiles.mapillary.com/y/x/z which is still serving tiles.
You could do a redirect or serve only tiles with an X (or information text) on it to inform the users that this tiles are deprecated and have a successor.

**Comment by ptpt** [comment]
@HolgerJeromin Exactly. We can do this. Need some help from @gyllen here.

**Comment by GITNE** [comment]
@ptpt What is the update period (if any) for these tiles?

Please, if it is not too much work, can you produce fully transparent tiles for areas which do not contain any sequences or photos? I am asking because some tools like JOSM render ugly `403 HTTP` errors or simply black tiles instead of *transparent* *tiles* themselves. :worried:

My two cents: I too am well aware that raster tiles can be considered a legacy technology and that as a developer one would like to drop support for these as soon as possible, since vector rending is not only superior with regards to scaling and volume of data transfer required but also bears computational and storage savings for the service provider (*Mapillary*) too. However, a lot of widely available tools (like JOSM) still rely heavily on raster tiles or do not support vector rendering yet. Thus for now, supporting this *legacy* *technology*, even though it comes with a cost, seems to me more useful to Mapillary in the bigger picture than not providing this data (effectively) at all. So, thank you for providing this service! :smile:

**Comment by pbb72** [comment]
This is the issue @GITNE is referring to:
![image](https://cloud.githubusercontent.com/assets/1436366/20787040/100e1924-b7aa-11e6-8fec-a22469b3e6f4.png)

@GITNE, I assume you are aware there is a Mapillary plugin for JOSM which gives you vector traces (and links to the photos)? But in general I agree with you, the tileset should not return HTTP 403s for empty tiles.

**Comment by ptpt** [comment]
Hi GITNE,

Thanks again.

I've answered some of your questions in @pbb72's post: https://www.openstreetmap.org/user/Peter%20Bremer/diary/39986#comment36874 I will investigate if it's possible to configure S3 to return a default content such as a transparent image instead of 403.

I'm glad it still so useful, and helps you for better mapping. We will keep supporting raster tiles. 

Tao

**Comment by GITNE** [comment]
@ptpt Thank you! :smiley:

> I assume you are aware there is a Mapillary plugin for JOSM which gives you vector traces (and links to the photos)?

Yes, I am aware of that. However, unfortunately it is buggy and in its current state basically unusable. It does not pull just the sequence data but comes loaded with all the photos in one go (one cannot configure that). Furthermore, sequence data is not downloaded continuously while panning over the map/layer. And finally, the bbox for the sequences to pull is always the viewport, which seems to work in theory but is impractical.

A raster tile layer is much more convenient and bug free (in JOSM, unless you consider these `403 HTTP` errors a bug). So, :+1: to @ptpt for resuming support of raster tiles. Having transparent tiles in sequence free spaces or as the default tile would be nice but not having them it is not a deal breaker.

**Comment by Klumbumbus** [comment]
I would add this tms to the JOSM internal imagery list (https://josm.openstreetmap.de/wiki/Maps). Is there any license or attribution or a link we should display in the corner for these tiles?

It would be great if you could deliver empty tiles instead of 403 error codes.

**Comment by pbb72** [comment]
What is the use really of having this (raster) layer in JOSM? I can understand the problems with the official JOSM Mapillary plugin, but I don't really see what help is offered by the raster layer. You'll have to open a webbrowser to see the images.

**Comment by govvin** [comment]
Mapbox could look into the Strava heatmap [0] for some inspiration, which is often used in JOSM for checking or aligning aerial imagery.

[0]: http://labs.strava.com/heatmap/

**Comment by Klumbumbus** [comment]
>What is the use really of having this (raster) layer in JOSM?
You can quickly check if mapillary images are available at all in the current area. With the plugin I always woder if there are no images or if the plugin is just not working atm or if it did not yet load images or if somehow the download mode was changed.
Additionaly you can also see the coverage also on a lower zoom.

**Comment by GITNE** [comment]
> What is the use really of having this (raster) layer in JOSM?

It is a simple, quick, and often better replacement for GPX traces. Besides, you do not always need take a peek at the photos (in JOSM) to map. Personally, I have come to use this “feature” in two instances already, where I used the sequence traces to add new ways and modify an existing one after refurbishment. In one case the road layout changed significantly and satellite or aerial imagery is not scheduled to become available before 2020 for the particular area. So, as you can see there do exist practical use cases for this. :wink:

**Comment by pbb72** [comment]
> It is a simple, quick, and often better replacement for GPX traces.

Be aware that the Mapillary sequences are not necessarily from GPS receivers. I don't remember the exact number, one of the Mapillary people once mentioned it, but a considerable number of sequences are actually handmapped on top of possibly outdated or misaligned maps. I do this a lot myself because the GPS signals are simply too erratic in dense urban environments.

**Comment by GITNE** [comment]
> @Klumbumbus Is there any license or attribution or a link we should display in the corner for these tiles?

@ptpt How about adding a **very** faint Mapillary watermark on each tile?

**Comment by GITNE** [comment]
> Be aware that the Mapillary sequences are not necessarily from GPS receivers.

@pbb72 I am aware of that and thank you for the heads up. :smiley: However, I have been referring to my own sequences only, and although I do pre-process them before upload too, I know what I have done to them. Besides, the point is that I **have** survey the affected locations, so I do know what I am doing. :wink: To say the least, I know if I can basically trust my own sequences.

**Comment by Klumbumbus** [comment]
>How about adding a very faint Mapillary watermark on each tile?

I don't think this would be useful, as it would display also on your own [preview map](http://mm.mapillary.io/raster_tiles.html).

I don't know how familiar you are with JOSM. Just in case we misunderstood, what I was suggesting was the following: JOSM has different parameters which can be added to imagery entries. You can display two different texts and a logo in the down left and right corners of the mapview. Each of them can include a link. These are always visible when the layer is active and keep their position in the corner, independet from panning and zooming. Most of the imageries in the JOSM list use at least one text with a link. For mapillary it could look like this:

![mapillary_in_josm](https://cloud.githubusercontent.com/assets/7115609/21032820/5dc119c0-bdac-11e6-8630-8c06e2b10d59.png)

(I took the logo from https://github.com/mapillary/mapillary-js/blob/master/styles/cover-logo.svg)

**Comment by GITNE** [comment]
>> How about adding a very faint Mapillary watermark on each tile?
> I don't think this would be useful, as it would display also on your own preview map.

It is true that it would become visible on the layer. This is also why I have stated it to be very faint. :wink: I was rather aiming at other tools and use cases, since JOSM is not the only tool to consume these raster tiles. Well, I cannot think of any other (commercial) use cases as of now but some jurisdictions have provisions which state that any works which have not been specifically signed or marked by the author are put into public domain by default. Mapillary may want to protect its rights by doing this—just in case—although I am not sure to what extent such a watermark might be legally binding or effective in those jurisdictions.

> For Mapillary it could look like this:
> […]
> (I took the logo from https://github.com/mapillary/mapillary-js/blob/master/styles/cover-logo.svg)

I guess this should be okay, since this is one reason why the logo exists and has been made available.

**Comment by jesolem** [comment]
Hey everyone. If you don't want the big logo, you can just put `Mapillary, CC-BY` in the corner, with a link to mapillary.com.

**Comment by Klumbumbus** [comment]
it seems 403 error was fixed :)

**Comment by gyllen** [comment]
@Klumbumbus Correct we do have a working raster tile overlay now :)
