### ISSUE TITLE
no better resolution available for new images

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#1419]
there was an issue where only a low-res image was available in the new viewer. this was mostly fixed, although there's still one edge case - new images.

when a new sequence is uploaded, it is processed for basic things, blurred etc, and then the images are available. unfortunately, until 3d processing is done (at least so it seems), the better-resolution images are not available.

this is not good as the contributor might check some blurs before the 3d processing happens (and this sometimes takes a long time), and the results will be of lower quality because of the image resolution making the image appear much more blurry than it actually is

**Comment by jesolem** [comment]
@richlv All thumbnails at all resolutions are created at the same time and should be available at the same time. The may be minor differences as they propagate out in the Cloudfront CDN system but should not make a big difference. 

Do you have any example link where you see this behavior?

**Comment by de-vries** [comment]
here you go: http://www.mapillary.com/map/im/Q699sQnUBE_1BO0UIBRbFg/photo
in my experience fresh sequences always take a few hours before the highres imgs are available

**Comment by oscarlorentzon** [comment]
We were actually filtering this actively on the viewer side so that only reconstructed images were shown with high resolution. There is no point in not showing high resolution for images that haven't been reconstructed as you rightly point out. All images are now shown in high resolution when navigation is halted. Thanks for reporting and providing example!

By the way @de-vries, that bridge/park is super cool. It is just like the High Line, except that it is much better because there are almost no people on it! When did they convert it to a park?

**Comment by de-vries** [comment]
@oscarlorentzon it is build this way. and I have to say I was a bit lucky with the amount of people/wheater combination

**Comment by jesolem** [comment]
Thanks for reporting guys!

**Comment by oscarlorentzon** [comment]
OK, it looked like an old structure. Well, it was just modern then... Cool thing anyhow!
