### ISSUE TITLE
Arrow buttons sometimes not indicating expected direction

### ISSUE THREAD

**Issue by mackerski** [mapillary/mapillary_issues#1450]
With reference to this image and a number either side of it:

https://www.mapillary.com/map/im/DHqOa8MlKy6zIik9dnC6Xg/photo

This sequence is taken to the forward direction while moving at cruising speed. The compass bearings of the successive images appear to be plausible and to move in a single direction (this is a very gentle curve). But whereas I would expect forward and rearward arrow buttons, a number of images have left and right buttons instead.

**Comment by oscarlorentzon** [comment]
You are right @mackerski , this sequence should only have forward and backward navigation arrows because the motion is definitely forward. 

The problem occurs because the distance between each image is roughly 50 meters which means that there is not much overlap between the images. Also on roads like this one there are not many distinctive objects which makes finding recurring interest points in successive images hard. In the end this makes 3D reconstruction a hard problem to solve and that this can clearly be seen here. We have gotten the relative position between some of the photos wrong. 

Thanks for pointing this out. We are working on improving the reconstruction algorithm to handle these situations in a better way. Examples of where it does not work properly always help.

BTW. To navigate more easily in situations like this one you can use the up and down keyboard arrows which here falls back to the next and previous node in the sequence. Playing the sequence is also an option.

**Comment by oscarlorentzon** [comment]
We have now implemented stricter rules in the viewer regarding the navigation arrows. For this sequence , which clearly goes in the forward direction with only small turns, there should only be forward and backward motion indications (regular arrows) or next and previous in sequence indications (chevron arrows) from now on.
