### ISSUE TITLE
iOS: compass headings seem to drift

### ISSUE THREAD

**Issue by mackerski** [mapillary/mapillary_issues#1451]
In a photo sequence many of whose photos have plausible headings, later parts of the sequence have headings that are not only poorly calibrated, they appear not to reflect device direction at all.

Consider this image and those that follow it after the roundabout is negotiated:

http://www.mapillary.com/map/im/dNjjon6RQbJgliYlVeKtJw/photo

The heading starts out slightly incorrect, though still just about plausible. After a 90 degree turn left, the heading appears to turn a little to the right, at which point it is directly opposite to the direction of travel.

At all points in the recording of this sequence, the phone remained fixed in its windscreen holder, the camera facing the direction of travel. I cannot rule out some source of interference, though nothing in the passenger cabin had changed since the earlier part of the journey in which headings were plausible.

**Comment by oscarlorentzon** [comment]
Thanks for reporting again @mackerski .

In the fallback viewer (when there is no WebGL support in the browser) it is possible to see the compass angle on the map. I guess that is what you are referring to.

Recording correct compass angles in a car is hard because it is affected by the magnetic field within the car. Therefor the compass angle can be far off. For this reason we are using the computed compass angle retrieved from the 3D reconstruction when showing the heading on the map.

In the case of the images you refer to in the roundabout it can be seen that the navigation arrows are off and the reconstruction is not completely correct. Therefor the compass heading appears to be off for those images too.

This issue has the same root cause as #1450 , it just appears in another part of the application.

**Comment by ybkuang** [comment]
mapillary_issues is no longer an active repository.
This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!
