### ISSUE TITLE
Adjust EXIF data before the upload

### ISSUE THREAD

**Issue by Matthias84** [mapillary/mapillary_issues#1520]
I like to ask, if you could add an possibility to add single photos to mapillary manually and edit their location and viewport. Possible usecases:
- own highres panoramas
- historical photos
- wikipedia / wikicommons photos
- link webcams

**Comment by jesolem** [comment]
You mean photos that are not geotagged and have them tagged on upload or after?

**Comment by Matthias84** [comment]
Yes, esp. if the photos have no geolocation/direction and you need to pass them manually.

**Comment by jesolem** [comment]
Understood. 

Maybe an option to drag them to a map in the upcoming desktop uploader before uploading? Could also go in the web uploader (no GPS tag, then place on map). Assigning to @knikel for him to think about how to do this.

**Comment by Matthias84** [comment]
Sounds nice :smile:

**Comment by rudolfmayer** [comment]
I would support this - sometimes when walking in interesting places I take pictures with my digital camera, and if I remember well enough where it was taken, adding a selected handful of them to the map manually might bring additional value

**Comment by knikel** [comment]
Such functionality would definitely land in the desktop uploader. No precise ETA for it though.

**Comment by HolgerJeromin** [comment]
Geosetter has a really nice gui for adding position and direction to images (even when no gpx track is available) . Did not found an adequate program on Linux for that. 
Preparing some old images from honeymoon for mapillary. :-)

**Comment by de-vries** [comment]
@HolgerJeromin try GottenGeography

**Comment by HolgerJeromin** [comment]
thanks! But installing this seems quite hard on a debian oldstable... 8-/
gir1.2-gexiv2-0.4 is not available.

**Comment by mxa** [comment]
Another case is when pictures have wrong coordinates (due to lost GPS signal, etc, especially with manually uploaded pictures) that one has to manually correct the position.
![example: outlier in path](https://cloud.githubusercontent.com/assets/1220707/11762533/601f2f14-a12d-11e5-8b71-348989fdd744.png)

**Comment by jaakkoh** [comment]
Since it seems like there might be a desktop uploader coming out at some point I think including a geotagging and of course also marking the direction of the photo would be fantastic. I've been looking a few times a little for a convenient way of doing this so I could upload my thousands of Mapillary-wise meaningful photos not taken with Mapillary.

I think if this feature was convenient enough it could help get more contributors from outside the current contributors that to my understanding are quite often techies at least to some extent. I haven't used Panoramio in years but was amazed by the quantity and breadth of the types of images and clearly the range of people that were contributing to it already nearly 10 years ago when I used it for some time. Mapillary should be at least attractive choice/option for all Panoramio contributors.

**Comment by gyllen** [comment]
This should work in new uploader, please confirm.

**Comment by nickplesha** [comment]
Confirming. :)
