### ISSUE TITLE
Delegate reviews

### ISSUE THREAD

**Issue by Matthias84** [mapillary/mapillary_issues#1540]
As the review of 1000s of photos can be time consuming, I suggest to add the ability to delegate or distribute the review process. So you can pick an user / friend and ask him to review your photos before they get published.

This might be useful to very big teams (gov, companies, loc. communities, ...) which still have to assure privacy of recorded people on the photos. While some part of the team work outside and take photos, one (or multiple) user can start reviewing, so the others can continue recording in the fields (decoupling of workflows)

**Comment by de-vries** [comment]
This is a great idea, but it doesn't make sense to make a feature out of this until your idea to only publish sequences after manual check[[1]](https://github.com/mapillary/mapillary_issues/issues/1518), or the request for a "reviewed-flag"[[2]](https://github.com/mapillary/mapillary_issues/issues/211) [[3]](https://github.com/mapillary/mapillary_issues/issues/818) is implemented.

For now if you need help reviewing; I'm sure you will find it when you put a request in the forum.

**Comment by Matthias84** [comment]
I agree @de-vries but wanted to submit the idea, so you (maybe?) could consider it for a roadmap.

Currently I pause my contribution till I get better hardware and the privacy workflow is optimized

**Comment by gyllen** [comment]
@Matthias84 @de-vries I like this idea very much. You guys have any more thoughts on how this should work.

**Comment by de-vries** [comment]
I think a [blur game](https://github.com/mapillary/mapillary_issues/issues/886) is the way to go here. Such a tool should provide a nice work flow for the user to review its own photos, or contribute to Mapillary in general where it's most useful. 

For Mapillary it's more a way to bring volunteer effort and work that needs to be done together.

The photos shown is this blur game should be selected by one or more of the following criteria:  

 - Photos made by this user
 - Photos in a certain area
 - Photos with blur requests that need reviewing
 - Photos with blurs that have a high probability of being incorrect

The user should be able to choose between three different focus modes: 1. only show it's own photos,  2. focus on a certain area,  3. work were it's most needed.

Also needed: some stats to show users how much they've done (people love stats)

**blur request approvals**
This is probably also the best way to crowd source the approval of blur requests, as it will prevent biases because of the randomized connections between the reviewer and requesting.

**Comment by gyllen** [comment]
We now have a nearly `100%` accurate blurring algorithm. Eliminating needs for any game and mass reviewing of images. Checkout the detections games though, they are fun!
