### ISSUE TITLE
stats page: link to bigger entity

### ISSUE THREAD

**Issue by HolgerJeromin** [mapillary/mapillary_issues#1544]
When i loaded [germany](http://www.mapillary.com/map/places/85633111) i can click at the containing 16 "bundesländer" (for [example](http://www.mapillary.com/map/places/85682513)). There i can click further "down". 
It would be nice if i have a link the other way round at the web page. Link from Nordrhein-Westfalen to germany.

**Comment by knikel** [comment]
If I recall correctly we tried to implement it, but skipped it, because the problem was that a shape internally can belong to many bigger shapes containing it and it doesn't have explicitly stated single parent: in this case Nordrhein-Westfalen -> Germany, etc. Let's investigate that further and see if we can find a way around it. This would be definitely useful.

**Comment by knikel** [comment]
This has been fixed, will be visible soon.
