### ISSUE TITLE
no transitions in the blur mode

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#1575]
this is a regression.
when blur mode is enabled, there are no 3d transitions - there were previously

**Comment by knikel** [comment]
The main reason why there are no transition is because you're seeing an actual photo on top of the viewer. We had to make a choice: either we want to get the blur/traffic sign rectangles in CSS right (the only way to do it right is to have an actual image and use positioning on top of it (Trust us, we tried everything here) or we would have to do the rectangles in the viewer, which is not a good option, the magic that happens there is well, complex enough. Sorry about not so magical experience, but we had to make a choice here, and when it comes to that functionality it's better have more correct data and reliable information for the user where they're editing.

**Comment by richlv** [comment]
ok, thanks for the response - totally agreed on reliability over shiny :)
closing this issue then
