### ISSUE TITLE
GPX files do not pass validation

### ISSUE THREAD

**Issue by voschix** [mapillary/mapillary_issues#1578]
The GPX fiels creating from Mapillary sequnces do not pass validation tests.
The header of the file from the site reads like this:

<?xml version="1.0" encoding="UTF-8"?>
<gpx version="1.0">
  <name>Mapillary/NllQ3_Mhr67-zXZ3mTsvow</name>
  <trk>
    <name/>
    <number>1</number>
    <trkseg>
...

I noticed the problem when opening with the RouteConverter program on my Windows10 system. Other programs or sites are less choosy and accept the Mapillary GPX files (examples: GPSvisualizer.com, Geosetter) 
There are two obvious errors in the GPX file header:
- the slash in ' <name>Mapillary/NllQ3_Mhr67-zXZ3mTsvow</name> '
- the text fragment '  <name/> '

Verifying the file on the XML validation site http://www.validome.org/xml/validate/ 
in addition shows an error in ' <gpx version="1.0"> ' which I do not understand.

It's not an urgent issue as it's easy to convert the file in a formally correct one with GPSvisualizer, but it should be cleaned up.

**Comment by mander2li** [comment]
The first 7 lines of Mapillary's gpx file are:

1   <?xml version="1.0" encoding="UTF-8"?>
2   <gpx version="1.0">
3     <name>Mapillary/ptAE_mewQgYaIKbrPKZbiQ</name>
4     <trk>
5       <name/>
6       <number>1</number>
7       <trkseg>


Please make the following changes so that Garmin's MapSource and BaseCamp can load/import it:
1. remove lines 5 & 6
2. interchange line 3 and 4
3. change line 2 to:
<gpx xmlns="http://www.topografix.com/GPX/1/1" creator="" version="1.1">


The resulting file looks like:

1   <?xml version="1.0" encoding="UTF-8"?>
2   <gpx xmlns="http://www.topografix.com/GPX/1/1" creator="" version="1.1">
3     <trk>
4     <name>Mapillary/ptAE_mewQgYaIKbrPKZbiQ</name>
5       <trkseg>

**Comment by mander2li** [comment]
The resulting file should looks like:

1   <?xml version="1.0" encoding="UTF-8"?>
2   <gpx xmlns="http://www.topografix.com/GPX/1/1" creator="" version="1.1">
3     <trk>
4     <name>Mapillary/ptAE_mewQgYaIKbrPKZbiQ</name>
5       <trkseg>

**Comment by mander2li** [comment]
[Mapillary error.txt](https://github.com/mapillary/mapillary_issues/files/55355/Mapillary.error.txt)

**Comment by gyllen** [comment]
Add GPX download to new website.

**Comment by gyllen** [comment]
GPX is no longer available. Please open a thread at http://forum.mapillary.com if this is still something that you want.
