### ISSUE TITLE
Tilt left right difference

### ISSUE THREAD

**Issue by hakuchi** [mapillary/mapillary_issues#1611]
"phone is tilting" message comes when I move my phone to left on 20°
But if I move my phone to right, it comes after -44°

Tested only in hands without moving.

I use App 1.68 with standard settings on my android 5.0.2
Also in 1.70

**Comment by kaitu** [comment]
I confirm the problem is still present in version 1.71. 

Tilting to the left: the tilt reading increases correctly from 1° to 44°, then suddenly jumps to 90° (this is not really a bother for practical purposes, just a bit weird). The "phone is tilting" message comes accordingly to the "max tilt" setting.

Tilting to the right: the tilt reading behaves in the same way (just with negative angles). But the "phone is tilting" message only comes with the -90° reading.

Guess what, when my pictures are badly tilted, it's always to the right ;-)

**Comment by kaitu** [comment]
Excellent, working flawlessly in version 2.24. As far as I'm concerned, this issue can be closed.

**Comment by hakuchi** [comment]
works fine in 2.24
