### ISSUE TITLE
Image direction is reversed

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#1659]
I often have photos where the image direction gets changed from what I entered into the Exif data. In some case, such as with http://www.mapillary.com/map/im/BX52wxEjdMVuIQsetRTe0g/photo, the direction is actually reversed. If you go into Edit mode, you can see the direction was originally correct.

The problem with this is, you cannot browse the sequence, unless you turn on "Lock to sequence" (which ignores direction information).

I can understand that you need to apply routines for correcting the direction in case of malfunctioning GPS equipment or misuse of manual tools. However, I think there are a few case in which your routines should be more careful before adjusting the supplied information:
- Manually uploaded images.
- Directions are more or less constant in relation to the movement (eg. always close to movement direction for forward-pointing camera, or always circa 90 deg off for sideward facing camera).
- No connections to other sequences nearby.
- Low-quality photos (mine are frames from an interlaced HD video -- far from ideal for image matching I would guess).
- Adjustments would create a non-browsable sequence (in my example, only the first 8 images are connected).

Of course, in any of these situations the included direction information could still be faulty, but I think the likelihood that image matching will provide better information will be much lower.

**Comment by gyllen** [comment]
It would be interesting to get a couple of sample sequences so we can do some further investigations.

**Comment by pbb72** [comment]
I come across this quite a lot.

- http://www.mapillary.com/map/im/BX52wxEjdMVuIQsetRTe0g/photo and 8 following photos
- http://www.mapillary.com/map/im/Z0HopbKfT8V1Xn4ZAIF30A/photo and almost the whole rest of the sequence
- http://www.mapillary.com/map/im/krUgc8Q0y617v07VsAo4MQ/photo (the whole sequence)
- http://www.mapillary.com/map/im/x3fnUCARY5Iu_fdtzkVkwQ/photo (twirling around for 40 images)
- http://www.mapillary.com/map/im/mVazYpyXW6IXSfv_RZKdSw/photo (a little twirl)

**Comment by paulinus** [comment]
We have found that a lot of images come with bad compass angle, which is why we chose to rely very little on it. Unfortunately, that sometimes modifies angles that are originally correct.

We could add special cases for when should we modify the original data, but I fear it will be difficult to come up with rules that work in general.

The cases you mention are indeed sequences where sfm has little information and should not modify the original direction. The direction of the train sequence should not be modified. I will investigate what is happening.

Thanks for the examples!

**Comment by paulinus** [comment]
We are now displaying the original direction on the map, which partially solve the problem. I will keep working on getting better updated directions.

**Comment by pbb72** [comment]
Thanks for looking into this @paulinus.

On compass angles:
Yes, I agree with this. In every situation there is a good chance that the compass information is not trustworthy. Maybe you could add a decision routine to determine if compass direction should be interpreted from SfM. If more than x exceptions (like the 5 I listed) are applicable, then don't use SfM.

On the map update:
Actually, I prefer that the map displays the "interpreted" direction. This helps with finding the cause of weird sequences. For example, http://www.mapillary.com/map/im/BX52wxEjdMVuIQsetRTe0g/photo now only shows an arrow on the bottom, to go back in the sequence, while it is the first image in the sequence. With the map showing the interpreted orientation, it was clear what was the cause of the problem. Now the map is no longer any help with this problem.

**Comment by paulinus** [comment]
With the latest reconstruction algorithms, the reversing of the direction does not happen anymore. Previous versions were too optimistic finding correspondences and interpreting the motion. We are now more strict which results in no motion prediction for this sequence, since the overlap between the images is very small.

I agree that seeing the interpreted position and orientation of the images would be good for finding reconstruction problems. We are working towards that.
