### ISSUE TITLE
3d data from pointcloud somewhat off the grid

### ISSUE THREAD

**Issue by echeloni2p** [mapillary/mapillary_issues#1669]
Hi!

If you look in that area http://www.mapillary.com/map/im/-KiT2wx0LE2LSmOlNrStSg/photo in the pointcloud, the 3d recognition is bad, as the tracks are registered in different height. Something went bad. Enough pictures available, but if they are registered in different geights, they cannot create a good pointcloud.

**Comment by paulinus** [comment]
What we have here are two independent reconstructions at different heights one for each direction.

There are sequences going in both street directions. The matching algorithm is unable to match them and we end up with two sets of registered images, one for each direction. These sets are reconstructed independently and, in this case, end up having different estimated heights.

One solution to it is to add either side-looking or panoramic shots that would join the two sets.

At some point we will need some higher level matching algorithm that would understand that the two reconstructions are of the same place and register them even if there are no matches between the images. Until then, having multiple reconstructions of the same street is an the expected behavior.

thanks for pointing the issue!
