### ISSUE TITLE
Cannot map because inaccurate GPS

### ISSUE THREAD

**Issue by beer119** [mapillary/mapillary_issues#1671]
Hi
There is some areas that I cannot map. When I try then I get "waiting for (better) location fix". I dont know if it is a problem with my phone (Nexus 6p) or with mapillary itself. But when looking at my build in maps then it does not look that bad. Is there any suggestion what one can do?

**Comment by echeloni2p** [comment]
Hi!

Thats usual a issue of the phone and/or the place you are in. As not all places do have good receivement from the GPD/Glonass satellites and/or WIFI information from Google service locations.

All you can do: get a different, better GPS receiver, tick the "ignore GPS location check" in mapillary app, move to another position with better GPS receivement.
You can also do take pictures and move them later on to the good position with the JOSM plugin and upload via that way, but thats lots of work.

Usually in the city with street canyons there is not good enoguh GPS signal to get good pictures, or in the valleys in the mountains.

echeloni2p

**Comment by beer119** [comment]
I am a bid of a noob so I have a few question. 

1: Where do get a better GPS receiver for a phone and how does it look like?
2: As far as I understand "ignore GPS location check" then the most of the pictures would get discared anyway (server side instead of client side). Is that correct?

I dont know why but sometimes (app 1/3 to 1/2 of the time) restarting mapillary solves the problem (speciel if if it is a long time I got gps signal).

I have tested the "ignore GPS location check" today and waiting on them to be show on thee map to see how bad the sequence is. According the the debug information I could see on the screen then the normal is accuracy 12-14 meters (yellow mark) and bad is like 15-17 (few times up to 19m).

I dont know if it is a problem with mapillary, the GPS resiver in the phone or natural cours such as street canyons, forrest or valleys.

**Comment by beer119** [comment]
Hi

I just checked the data from yesterday where I did remap older areas with "ignore GPS location check".I can see that this is either a phone problem or a regression since the old corridanates from my old phone (Nexcus 6) are much better. So it is not pure a pure location problem

One example is:
https://www.dropbox.com/s/10u2dk23okompgr/gps.png?dl=0

**Comment by echeloni2p** [comment]
Moin

1. every mobile has a different GPS setup and so every mobile has a different receivement and process of GPS signals and this results in: different mobile, different GPS accuracy. Thats nothing you can fix with software alone. It is not mapillary fault, it is the hardware of the mobile. 
2. A better GPS receiver could be a different mobile, or a external bluetooth GPS receiver which is connected with the mobile. Or you need the mobile to bring in a better position (over the head instead of direct in front of your chest, as your body shields some signals). BUT there are very few limited external GPS receiver working fine. In the end, I did not choose that option, I just try to get along with a good mobile (and I choosed esp. for this feature, too).
3. Yeah, the pictures with bad GPS signal CAN be removed, but currently they are not (at least from my tracks). Usually all get online and you can manually move them to the correct position in mapillary account. But thats lot of work.
4. And yeah, 15m is the breakpoint for bad GPS signal in mapillary. Which is usually a god idea, e.g. in a city with narrow roads or a small hide with lots of ways to walk on (http://www.mapillary.com/map/im/gYdy_xBH3DGZ0qrtlKrp0g/map for my town, Schloßberg in the middle e.g.) it is already really bad and lots of manual work needed. 

In the end: if you do not want to invest a lot of work, choose the "ignore GPS location" option and go on hoping it work out fine. Everything else is really dedication, e.g. buying a special mobile, placing pictures in josm,...

echeloni2p

**Comment by peterneubauer** [comment]
Hi there,
it looks like the phone is not able to get a good location fix. Disabling
the check does not make the problem go away but submits location info that
is worse than our threshold of 15m accuracy, which is what you see on the
map.

**Comment by mxa** [comment]
This app can help pinpoint the issue with the GPS of the phone and lets you download new APGS data so that you should get a gps fix faster. https://fossdroid.com/a/satstat.html

**Comment by rsahlin** [comment]
Update 1.81 has several changes and fixes to location usage.

Please check if this version makes your problem better (or perhaps even worse)?
You can download directly from http://www.mapillary.com/using.html - 'Direct Android .apk link'
or as a Beta developer (choose join beta group in the settings menu)
