### ISSUE TITLE
allow zooming/panning the map

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#1673]
in-app map that shows the sequences is great, but there does not seem to be a way to zoom or pan it. when considering which region to explore, it would be helpful to see a bit further away than a few blocks

**Comment by millenbop** [comment]
Thanks for the suggestion. I agree, it would be useful.

Seeing two solutions:
1. let the user pan/zoom when no auto-capture is occurring
2. let the user pan/zoom in all modes, and move back to user's location after a few seconds if location is changed and user has stopped interacting

**Comment by richlv** [comment]
the second solution sounds good enough to me - with "few" being 5 or 10 - i'm thinking about a usecase where one person is driving and another could use the map on the device that is auto-capturing

**Comment by millenbop** [comment]
yeah that's a valid use case. maybe it's better to have a button of some sort to toggle if it should follow or not. not sure how navigation apps usually do, will do some researching. preferably I'd like to keep the number of buttons down if possible.

**Comment by richlv** [comment]
gps devices usually do have a separate control that appears when you have panned away from your current location.
you could reuse that concept - when panned, show a new button. tapping that will pan back to the current position and track it again. probably the same for zoom ?
this way you would only have one new button that would be shown only when changing the view - in the normal mode no changes to the ui.

**Comment by millenbop** [comment]
sounds good!

**Comment by jaakkoh** [comment]
Glad to see a ticket opened regarding this already.

I would like to see a possibility to change the zoomlevel of the map so that it would not autozoom back after at all, ie. control the zoomlevel myself. The reason for this is rather simple: The ideal zoomlevel depends a lot on a number of things including at least the density of roads/paths in the area, how thoroughly mapillaried the area already is, how fast you are moving (while autocapturing).

I think that automatically centering after X seconds makes sense for many users so that could be ok as such (without additional settings). However, the autozoom question is something that I think should have a toggle in the settings: autozoom or not. ... And if such setting is created then I would think that adding a setting for automatically centering the map would make sense too.

Actually you could also consider copying all this from OsmAnd (feature/settings wise). There a user can choose if autocenter or autozoom happens, and after what time if so. Additionally there's a dot(?) on the map that is blue if the map is centered and gray if not. With that you can also manually center the map to where you are (regardless of the mode of the app: browsing or navigation) -- and then the map follows your position as you move.

**Comment by ovivoda** [comment]
This issue should be fixed in the latest android app version
