### ISSUE TITLE
Switching sequences on the "Map" page, activates the "Photo" tab.

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#1695]
When on the Map page (for example http://www.mapillary.com/map/im/i0XxqZMOEhzMuIOFOO7fZQ/map) and clicking on another sequence to switch to that, the tab bar on top of the map automatically activates the "Photo" tab, making it impossible to switch back to the Photo page. Not even clicking on the miniature photo helps.

At this point, I have to click the "Map" tab, which causes the page to rebuild, and then I can click the "Photo" tab (or the small photo besides the map).

**Comment by GITNE** [comment]
Yes, please fix this. I get this on Firefox too. This is one of the small but very annoying bugs.

Furthermore, this bug seems to have the side effect of adding a vertical scroll bar and the lower portion of the Mapillary website map after *finally* switching to photo mode. And then, if you press the ```DOWN``` key the photo gets properly updated to the previous photo in the sequence (or point of view moves backwards) but so does the page scroll down too. One has to reload into photo mode again to get rid of the vertical scroll bar and the Mapillary website map.

**Comment by knikel** [comment]
This is no longer an issue given the changes in the new web app. It's possible to change the `focus` (whether map or photo) in a smooth way now.
