### ISSUE TITLE
save vertical space (mobile and large desktops)

### ISSUE THREAD

**Issue by HolgerJeromin** [mapillary/mapillary_issues#1715]
On mobile i have the problem that i loose about 1 cm of vertical space with the two "toolbars", while the map/photo is only 4,5 cm high!

So i would propose combining both (before + afterwards mockups)
![mapillary_mobile](https://cloud.githubusercontent.com/assets/2410353/13124997/a7255256-d5c3-11e5-9f20-f4fd34c94b5e.png)

On desktop browsers we have a menubar, so this is only possible on wide screens:
![mapillary_desktop](https://cloud.githubusercontent.com/assets/2410353/13125013/ba003a08-d5c3-11e5-841a-8209a444c7b0.PNG)

**Comment by pbb72** [comment]
I agree with the unnecessary waste of screen space, but I have a different suggestion:

- The Search function should be permanently integrated in the top menu bar (since it has no relation to the currently displayed photo).
- The Map and Photo buttons should be replaced with a flowing "Enlarge" icon on either the mini-map (in photo mode) or the mini-photo (in map mode and on the search results page).

Come to think of it, it's already obvious that clicking the mini-photos will switch to photo-mode (it already does this), so there is no need for an icon there. Only an Enlarge icon on the mini-map is needed.

**Comment by knikel** [comment]
[That](http://blog.mapillary.com/update/2016/04/28/www-remake.html) is what we have in pipeline for you guys. Search is always there, one can toggle between map and photo, extra details in the drawer on the side. I'm going to close this one as the layout in the upcoming release is what you can see on the screen. Btw. all issues tagged with `fe-new` (but without `fe-feature-request`) will be solved when we release the update.

**Comment by pbb72** [comment]
Looks very good! Though you should not really close issues before the new feature has actually been deployed... :-)
