### ISSUE TITLE
Mapillary Xperia Z1c tilt error

### ISSUE THREAD

**Issue by rsahlin** [mapillary/mapillary_issues#1730]
Hello, I am using mapillary app on Android phone (Xperia Z1 compact) and tilt is not working correctly. Tilt alarm is always blinking with "phone tilted" message and app reports 90 degrees tilt when phone is perfectly horizontal. Is this known issue? I can disable tilt checking, but I think it is better not to.

Thanks
Jiri

**Comment by jiri-novacek** [comment]
I have reported this issue 4 months ago, it has been fixed couple updates ago :)

**Comment by rsahlin** [comment]
Ok - we will investigate and bring back the fix :-)

Do you have the issue number for reference?

Thanks
/Richard

**Comment by jiri-novacek** [comment]
I don't remember if anybody responded to my original bugreport, I think not, so I have no issue number of any kind. I just know that next Google Play update of Mapillary App fixed the issue. I even think there was some mention in GPlay changelog about tilt fixing for some phone models. It has been working correctly ever since, so I dont understand what you mean by "bring back the fix" :)

**Comment by rsahlin** [comment]
Ok thanks - Let's treat this issue as the main one :-)

**Comment by rsahlin** [comment]
@jiri-novacek Could you please try the latest (1.76) release from our site:
http://www.mapillary.com/using.html - choose 'Direct Android .apk link'
Thanks

**Comment by jiri-novacek** [comment]
I am afraid there is still some misunderstanding. English is not my native language, so I'll try to explain it differently:

- I reported this issue on 13 Dec 2015 by email
- after couple of days after my initial report, updated app has been released on GPlay and this bug has been **fixed** (coincidentally?) and is fixed for me ever since
- text of my original email has been converted to this "issue" on github just yesterday (4 Mar 2016), that is when I have received email "thanks for email, I have created issue..." from you
- I commented on this issue, replying that the problem has been fixed long time ago

So I really don't see any reason to do anything else but closing this issue as FIXED :)
Thank you for your help

**Comment by rsahlin** [comment]
Thanks Jiri - closing issue.

Thanks for your support!

**Comment by rsahlin** [comment]
Hi Jiri and thanks for clearing this up!
I will close the issue and thank you for your support :-)
Best regards/Richard 

    Den lördag, 5 mars 2016 18:23 skrev jiri-novacek <notifications@github.com>:
 

 I am afraid there is still some misunderstanding. English is not my native language, so I'll try to explain it differently:   
   - I reported this issue on 13 Dec 2015 by email
   - after couple of days after my initial report, updated app has been released on GPlay and this bug has been fixed (coincidentally?) and is fixed for me ever since
   - text of my original email has been converted to this "issue" on github just yesterday (4 Mar 2016), that is when I have received email "thanks for email, I have created issue..." from you
   - I commented on this issue, replying that the problem has been fixed long time ago
So I really don't see any reason to do anything else but closing this issue as FIXED :)
Thank you for your help—
