### ISSUE TITLE
Vector map style hides footways 

### ISSUE THREAD

**Issue by HolgerJeromin** [mapillary/mapillary_issues#1735]
All current map styles in the Web and Android app somewhat hide foot and bicycle ways. They are visible only at a very high zoom. 
This is not very good for trip planning.

**Comment by knikel** [comment]
Closing this since we're using standard mapbox styles for our maps with couple of extra layers on top. They've released great updates to their styles recently. You can see the styles [here](https://www.mapbox.com/maps/streets). We'll be using the same styles in the upcoming update. Closing for the same reason as #1560 then.
