### ISSUE TITLE
"Same Location" popup message while driving, good GPS

### ISSUE THREAD

**Issue by jfburke3** [mapillary/mapillary_issues#1757]
I kept getting the message "Same Location" popping up a *lot* during some short sequences today.  I was driving 20 to 45 mph at the time, and the GPS indicator was almost always green.  I'm uploading the sequences today so I can see the GPS track on the map.

Samsung Galaxy S7 Edge, Android 6.0.1, Mapillary v1.81

**Comment by jfburke3** [comment]
The GPS tracks look good to me.  Here is the sequence key for one example "Same Location" track:  http://www.mapillary.com/map/s/RcZ-0jzEXsW3m26NzDvC6g

**Comment by jfburke3** [comment]
Pretty much all of the sequences I uploaded on 16 March gave me the Same Location message while I was taking them.  Also, the sequences I shot today (not completely uploaded yet) had the same problem.

**Comment by rsahlin** [comment]
Hi @jfburke3  and thanks for reporting.

Yes, this is a tricky one. 
The check was introduced because we have had issues with sequences being taken with the exact same latitude/longitude.
Could you please try without Google Mobile Services (ie gps only)?
I will probably need to add a checkbox to disable this check....

**Comment by rsahlin** [comment]
After checking the GMS documentation I found this line:
"All location requests are considered hints, and you may receive locations that are more/less accurate, and faster/slower than requested."
This leads me to believe that we should default to GPS and only use google services for indoor usage.

I guess an option to 'Disable same location' check would be helpful?
In the meantime please try without google services and as a last resort check 'Disable location check'.

**Comment by rsahlin** [comment]
Turns out that there probably was an error in how the code handled thread access.

Version 1.82 fixes this issue.
Could you please try this version as normal and report any anomalies?

Thanks for your support!

**Comment by jfburke3** [comment]
I hate to tell you,  but I'm still  getting the popular. Happens on both my S7 (Android 6.0.1) and S5 (Android 5.0).

**Comment by echeloni2p** [comment]
HI!

with 1.81 the "same location" error was really annoying. Lets test today with 1.82

echelon

**Comment by jfburke3** [comment]
@echeloni2p, I'm still getting it while driving at 60mph, too. 

It doesn't seem to be completely consistent (i.e., I can't say it's every second picture), and there are some brief period when I don't see it at all,  but it is there the majority of the e time.

**Comment by jfburke3** [comment]
BTW, I had Use Google Mobile Services  enabled, and didn't realize the new Skip Same Location Check was there.  I'll try again with Google disabled.

**Comment by rsahlin** [comment]
Version 1.83 is just out to Beta developers

I have removed the same location check. 
This is since location sensors provide data asynchronously at a rate that is not guaranteed.
What this means is that it can never be guaranteed that the next pic to capture will have a new reported location. 
Focus now is to get as good reported position as possible.

Please check version 1.83 and thanks for your support!

Best regards
/Richard

**Comment by jfburke3** [comment]
I should have responded a couple of weeks ago just to close the loop, but yes, the message is gone.

**Comment by rsahlin** [comment]
Thanks for your support and efforts, much appreciated :-)
