### ISSUE TITLE
Better Possibility to Edit Image Angle

### ISSUE THREAD

**Issue by Nakaner** [mapillary/mapillary_issues#176]
Could you please implement a better possibility to edit image angle in
online editor? I would like to have a little line with an arrow at its
end which shows me more exactly in which direction the image was taken.

The small arrows inside the markers are ok, but I would like to have a
hand gear I can pick and use for rotating an image.

**Comment by korst** [comment]
I have been thinking about this too. I want to add that I want to be able to make this line as long as I want, so it's easier to line it up to objects that are on both the photo and the map.

Or maybe you can use a view angle instead of a line. I think you should be able to determine this angle from the make and model of the camera.

Another approach would be to directly link objects on the photo to objects in osm. 
![selectie_044](https://cloud.githubusercontent.com/assets/1449609/6226383/d82641a2-b694-11e4-82fc-8bdd286062bc.png)
*A bit like this*

This approach would nicely contribute to your vision of reconstructing a 3d model from the photos.

**Comment by jaakkoh** [comment]
This is an interesting thought and a good one not only for editing the angles of the photos but also for mapping purposes as by taking two photos with different angle to an object it's trivial to define the location of the object. Just like the Mapillary system already does in it's 3D side. Adding a feature like requested here would make using the angles for mapping purposes easier.

**Comment by knikel** [comment]
Will be a much better experience in the new editor

**Comment by gyllen** [comment]
Check new editor and report issues in new issue, closing
