### ISSUE TITLE
app should link to all project URLs

### ISSUE THREAD

**Issue by jidanni** [mapillary/mapillary_issues#1786]
All links listed on http://www.mapillary.com/developer.html should also be listed and hyperlinked from within the app.

**Comment by jesolem** [comment]
Hi @jidanni 
Can you help explain why the developer links should be linked from the app?

**Comment by jidanni** [comment]
Because a developer might be using the app and want to follow a link.
OK put them in a sub menu called Developers.
Anyway be sure all the website links are also in the app,
else one cannot get a grasp on the project as well.

**Comment by jesolem** [comment]
OK, maybe a Developer section then. -> @millenbop @rsahlin

**Comment by millenbop** [comment]
Yeah my bad, read too fast so missed the app part :)

**Comment by rsahlin** [comment]
Thanks for the comment, we will look into adding the apropriate web links to our apps in the future.

Best regards
/Richard

**Comment by GITNE** [comment]
I do not think this is really necessary. Every sane developer should be able to find information on Mapillary today. No offense, but if a developer is unable to do that then he or she should probably change profession. Why? Because basic research skills are a hard requirement for a developer's job. And frankly, in the age of the internet it is not that difficult to get initial information. So yes, links to Mapillary should be included into an "About..." or copyright section of the app but it is not really a defect or missing feature to skip developer links.

**Comment by millenbop** [comment]
Thanks, we will keep the suggestion, but closing this issue for now.
