### ISSUE TITLE
releasing android client as open source?

### ISSUE THREAD

**Issue by mnalis** [mapillary/mapillary_issues#1791]
would it be possible to release android client source under Free/Libre/OpenSource license?
that is, release source on github?

It would make it possible to include it in repositories of free android software, like f-droid.org (which some users use exclusively), and allow more users to contribute.

**Comment by HolgerJeromin** [comment]
#469 is one of the open source issues

**Comment by mnalis** [comment]
Searching the archives reveals that there was also #1124 with some activity (last being @peterneubauer reassigning to @rsahlin as Enhancement request,  but it seems something broke there (Github now returns 404 for https://github.com/mapillary/mapillary_issues/issues/1124 )

it can (still) be seen at https://webcache.googleusercontent.com/search?q=cache:https://github.com/mapillary/mapillary_issues/issues/1124

**Comment by rsahlin** [comment]
@mnalis You seem to be right, issue 1124 is nowhere to be seen...

Thanks for spotting this :+1:

**Comment by GITNE** [comment]
@mnails makes a good point here, especially when it comes to auto updates for non-Google customers. However, you can already download the latest apk from Mapillary's website. So, the Android app is already freely available for non-Google customers. But yes, it is not open source and not free software. Maybe just not yet? Anyhow, simply open sourcing the app may not be the best course of action for Mapillary. Providing open source Mapillary API libraries for common programming languages might be a better way to go because on top of that people could build any kinds of applications with any kinds of licenses and distribute them how ever and where ever they want. Hence, also Mapillary's business model should not and probably does not revolve around any particular client app but around the access to the data stash of photos.

**Comment by rsahlin** [comment]
Hi and thanks for your interest!

You are correct, we would not _just_ release the app as opensource. 
We would need to find a way for it to make sense.
One way to go could be to break out the photo capture functionality and provide as opensource.

We are definately interested in doing this and I'll be looking into it after finishing support for Camera2 interface.

**Comment by nighto** [comment]
A possible way to warn non-Google users would be to have a check on the app initialization to see if it is updated.

**Comment by GITNE** [comment]
Yeah, it should be fairly easy to check the Google Play Store for updates via the Google API, even if not signed-in with Google, and notify the user. Besides, implementing self updates from the Mapillary's APK repo are like 2 or 3 lines of code, while at the same time being safe and secure.

**Comment by blobgo** [comment]
> However, you can already download the latest apk from Mapillary's website. So, the Android app is already freely available for non-Google customers.

Regardless of the Google issue it should be noted that this website download is unsafe. It does not use HTTPS.

> One way to go could be to break out the photo capture functionality and provide as opensource.

So you want to release the open source app without a photo capture feature? :astonished: 
Or do you want to only release the photo feature as open source?

Both was would be quite strange. Why don't release the whole app as open source? Your app is free anyway...
BTW: If not photo capturing what other features does the app have, which you do not want to release as open source?

**Comment by mnalis** [comment]
Has there been any movement on this front (releasing the open source version of Android app, as mentioned also in #469,  and nowdays broken #1124 - archived at http://archive.is/kLbe7) ?

**Comment by jesolem** [comment]
#1124 works now. Must have been a temporary glitch.

Let me close this one and continue the conversation on #1124
