### ISSUE TITLE
Blank screen on Camera2 API on Galaxy S5

### ISSUE THREAD

**Issue by nighto** [mapillary/mapillary_issues#1838]
On my Galaxy S5, running stock, and Mapillary beta 2.05, I get a black screen when Camera 2 API is activated:

![photo140638738923502958](https://cloud.githubusercontent.com/assets/397851/14965354/6e610492-1083-11e6-91f5-7d9db90975e9.jpg)

Deactivating Camera 2 API works:

![photo140638738923502957](https://cloud.githubusercontent.com/assets/397851/14965358/751802f4-1083-11e6-85ec-061fec167a76.jpg)

Please let me know if you need debug logs (and what I have to do so they are useful).

**Comment by rsahlin** [comment]
Hi @nighto 

Yes please, debug logs would be very helpful.
Please enter the app, start camera (with Camera2 API) - when you see the blank screen go into 'Feed' and send the debug logs.

I have a hunch of the cause but it is always good to doublecheck :-)
Working on an update for this and a fix to streched preview.

/Richard

**Comment by nighto** [comment]
Sent the email. If it is not enough, please let me know.
Em 03/05/2016 06:33, "Richard Sahlin" <notifications@github.com> escreveu:

**Comment by rsahlin** [comment]
Hi Arnlindo and Thanks!
Could you please try this version?http://android-releases.mapillary.io/app-release_206-SNAPSHOT.apk

Please note that after installing this outside of Google Play you will need to uninstall the app and re-download from Google Play in order to get automatic updates.
Thanks!Best regards/Richard 

    Den tisdag, 3 maj 2016 12:25 skrev Arlindo Pereira <notifications@github.com>:
 

 Sent the email. If it is not enough, please let me know.
Em 03/05/2016 06:33, "Richard Sahlin" <notifications@github.com> escreveu:

**Comment by nighto** [comment]
Richard, just sent logs again. On this version the image appears, but it's
distorted, as if a 16:9 image is on a 4:3 viewport.
Em 03/05/2016 07:46, "Richard Sahlin" <notifications@github.com> escreveu:

**Comment by rsahlin** [comment]
Hi @nighto and thanks for the quick response :-)

Yes the preview image is not correct aspect, I'm working on fixing this.

Best regards
/Richard
