### ISSUE TITLE
Update cycle from photo upload to street sign detection 

### ISSUE THREAD

**Issue by maning** [mapillary/mapillary_issues#1839]
What's the usual update cycle until it lands to the [traffic sign detection overlay](http://blog.mapillary.com/update/2015/08/26/traffic-sign-updates.html)?

**Comment by ybkuang** [comment]
@maning It takes around 4-5 hours. However, the traffic signs for new images are not visible on the traffic sign overlay. This is because we updated our backend structure for storing traffic sign data some time ago. And we are working on a bigger project related to traffic signs on the side. The traffic sign data will be re-enabled once that is done.

**Comment by maning** [comment]
@ybkuang Any movement on this?  We are planning a navigation mapping in Canada and [a user reported that his upload since April is not detecting traffic signs](http://www.openstreetmap.org/user/manoharuss/diary/39088#comment35331).

Would be awesome to get new updates, so we can more traffic signs. :)

**Comment by ybkuang** [comment]
@maning The front-tend and back-end team have been working really hard pushing out our re-designed website (coming today actually!)  And traffic sign overlay (as well as a new object overlay) is the next thing in the roadmap. 

To explain a bit further,  there are several reasons that lead to the rewrite of the website. One of the reason is that the old website does not allow efficient display of the traffic signs (if there are many signs at certain zoom level, the page will load very slowly). With the rewrite, this will not be an issue anymore. We know that there has been a delay and we have to do it step by step.

On the other hand, we are running traffic sign detection continuously on the uploaded photos, so no traffic signs are missed. ;) So please keep the navigation mapping going!

**Comment by gyllen** [comment]
We now have a solid traffic sign detection. Checkout this blog post of the latest and greatest https://blog.mapillary.com/update/2018/06/15/global-sign.html
