### ISSUE TITLE
iOS GPS signal has deteriorated recently

### ISSUE THREAD

**Issue by octanebaby** [mapillary/mapillary_issues#1865]
iOS signal is almost always red in NYC.   There has always been the urban canyon effect, but it is now red in areas where it didn't used to be a few weeks ago, and in parks/waterfront areas with no tall buildings.

**Comment by nicolas17** [comment]
Can you think of anything correlated to this deterioration? Did you update iOS maybe?

**Comment by millenbop** [comment]
Thanks for reporting @octanebaby!

We use the accuracy value that the API tells us, and if it's red it means the API says it's worse than 15 meters (50 feet). We haven't touched that code in a year. I wonder if Apple has done some changes to make it more on the defensive side, I'll have to investigate.

**Comment by millenbop** [comment]
I compared the code with a version that is 1 year old and also sent it out to Janine who lives in NYC. The actual GPS code is not different, so my guess is that Apple have changed things internally (and not told us). Googling around some reveals that many have experienced GPS has deteriorated since iOS 9 was introduced.

However, I have seen some suggestions that some coders have said to be better to use on iOS9, so I will try those and see if it changes the performance to the better.

**Comment by millenbop** [comment]
Users who have had problems in cities still have problems with a year-old version of the app, so it def seems like an Apple thing. We'll double the values we check accuracy against.

Thanks for reporting.
