### ISSUE TITLE
HTC One M8 front camera not recognized

### ISSUE THREAD

**Issue by seb-1204** [mapillary/mapillary_issues#1868]
I've just updated to the version 2.10. Since the introduction of the new camera api Mapillary is locked to the front camera facing me and not the back (main) one directed at the road.
If I switch the new app off it goes back to the back camera.

**Comment by rsahlin** [comment]
Hi @seb-1204 

Ok, just so that I got this right:
When you are using Camera2 API the 'selfie' cam is used by Mapillary, but if you uncheck camera2 the camera works as expected?

Could you please provide logs by doing the following:
Go into 'Feed' and select 'Write trace logs'
Check to use Camera2 API then open the camera
Exit the Camera and go into 'Feed' and select 'Send debug logs'

Thanks for your support

Best regards
/Richard

**Comment by seb-1204** [comment]
You are correct when 
Camera2 API = OFF 
Focus mode = (LEGACY_0) CONTINUOUS PICTURE
Camera2 API = ON 
Focus mode = (CAMERA2_1) FIXED_NOT_MANUAL

I've send the logs as requested
[mapillary_trace.txt](https://github.com/mapillary/mapillary_issues/files/275718/mapillary_trace.txt)
