### ISSUE TITLE
GoPro Hero 3 - nothing transferred

### ISSUE THREAD

**Issue by seb-1204** [mapillary/mapillary_issues#1893]
I've connected my GoPro Hero 3 silver to a iPhone 6.
I took a few photos and pressed stop.
The first time I said _no_ when asked if I want to transfer the photos. Later the iPhone/app did not show any photos nor did it offer to transfer the previous photos from camera to phone.

On a second try I took photos and said yes to transfer them. I would assume I took at least 100 but the phone said transfer completed within seconds. Again no photos on the phone and app did not remember that I took any.

**Comment by ghsamme** [comment]
Same problem with Hero 3 Black and both Iphone 5 and 6. No problem taking photos but the app prompts "transfer completed" within seconds but no photos ar actually transfered.

**Comment by millenbop** [comment]
I got our Hero3 back today and have looked at it now. 

We have implemented a whole new system for transferring files, so this will no longer be a problem as all images are always transferred and we use time for syncing meta data instead of relying on (random) filenames.

Fix will be out in the next release. Thanks for reporting.
