### ISSUE TITLE
Navigation problem between pictures

### ISSUE THREAD

**Issue by Stefal** [mapillary/mapillary_issues#1908]
Hi !
I've uploaded some indoor pictures taken with my 360° rig.
The website seems to ignore the pictures metadata (timestamp, localization, direction): 
When I want to rotate the view, sometimes it chooses a picture a few meters away while there is a perfect one a few centimeters away.
Try to rotate from here: http://www.mapillary.com/map/im/QLAanIZ2BjIh1GtZbPHbDw/photo

**Comment by paulinus** [comment]
Hi @Stefal 
The images look very cool; we should get much better navigation of out of them. There are some things we can improve.

1. We have no good prior calibration of the XIAOYI camera. I'll look into that and update the reconstruction.

2. When using multiple cameras, it is better to upload them as separate sequences. We assume a single camera per sequence and impose some smoothness constraints that don't make sense when using several cameras. If several images from different cameras share the same timestamp and GPS, we will still be able to treat them as a rig.

**Comment by Stefal** [comment]
Ok, i will upload the sequence separately.

The pictures i've upload don't have the same coordinates (about 10 centimeters away from the rig center). For the other pictures, If you prefer I can move them to the same exact coordinates, but then it will be difficult to distinguish and select them on a map, or from the Josm plugin.

The Yi Action Cam FOV is 155° but there is an option to correct the wide lens effect. I don't know if it's possible to automaticaly detect if it is enable or disable.
I usually enable it when I take pictures in the car, and disable it elsewhere.
Correction disable:
http://www.mapillary.com/map/im/QLAanIZ2BjIh1GtZbPHbDw/photo
Correction enable:
http://www.mapillary.com/map/im/CzK8B6tVgdtsV-72ViEXWA/photo

**Comment by paulinus** [comment]
Hi @Stefal, we have added Yi Action Cam calibration, and rerun the train station sequence. Navigation is better now, although it still jumps between some images.
Did you try your rig again since then? There should be many less jumps if you upload each camera on a different sequence.

**Comment by Stefal** [comment]
Hi @paulinus !
Did you detect automaticaly is "lens correction" is enabled or not ?

I still have many pictures not uploaded. I will try to upload them separately and check if the navigation is better.

**Comment by paulinus** [comment]
I'm going to close this since mapillary_issues is no longer an active repository.

As of now, the reconstruction in the underground is still not good enough. I'll keep track of the issue internally since we are reviewing the calibrations for many cameras and this is a good test for the Yi camera.

[Other captures](https://www.mapillary.com/app/?focus=photo&pKey=QP3sg3t0nMx4TQJV2OsYXw&lat=47.083006514999965&lng=-1.3354179644444457&z=17) with the same camera are working fine, so the main issue might be the fact that all 4 cameras are put in a single sequence here.

We are working on detecting the internal camera undistortion automatically. And the examples you provided are useful, thanks.
