### ISSUE TITLE
Digital processing artefacts in images

### ISSUE THREAD

**Issue by rsahlin** [mapillary/mapillary_issues#1931]
Some devices will leave artefacts in photos - it seems they are from post-processing or maybe automatic white-balance.
Reported devices affected are:
 samsung SM-G930F (Galaxy S7)

Possible solution is to let users controll what mode is used for white-balance and exposure, or try with turning AWB off.

For the attached picture the modes are:
AutoFocus: CONTINUOUS_PICTURE
AutoExposure: ON
AutoWhiteBalance: AUTO

![fuzzy_photo](https://cloud.githubusercontent.com/assets/3063192/15889530/cd4f21e6-2d6b-11e6-8f72-21ff2b1ea6e1.jpg)

**Comment by rsahlin** [comment]
Please add comments of how often and where this type of artefacts are seen.
In the above picture the camera is in shadows with parts of the building very bright, possibly leading to auto whitebalance doing something.

**Comment by PTMaper** [comment]
Any new insights? I had to stop contributing pictures for weeks now since I can't take any acceptable picture since then.

**Comment by rsahlin** [comment]
Hi @PTMaper 

Could you please retest with the latest Beta (>=2.32) ?
I have changed the way the Auto whitebalance is selected.
Sorry for not updating this issue!

Best regards
/Richard

**Comment by PTMaper** [comment]
Still the same with 2.32
https://drive.google.com/file/d/0B2LPO5AGjh0ybmtmZ1NuOGlpRzQ/view?usp=sharing

**Comment by PTMaper** [comment]
Mapillary 2.32 with Camera 2.0
![Mapillary with Camera 2.0](https://cloud.githubusercontent.com/assets/19908085/16798528/c397aff0-48ec-11e6-8b2e-926b32a79fa2.jpg)
Mapillary 2.32 with legacy camera api
![2016_07_13_11_18_23_046](https://cloud.githubusercontent.com/assets/19908085/16798529/c397aa14-48ec-11e6-88d2-752a3ce8c149.jpg)
Google camera
![20160713_112316](https://cloud.githubusercontent.com/assets/19908085/16798527/c3976e82-48ec-11e6-94a8-831c04694253.jpg)

**Comment by PTMaper** [comment]
Mapillary 2.32 with camera 2 API
![2](https://cloud.githubusercontent.com/assets/19908085/16798757/ded13aec-48ed-11e6-860a-a87474465861.jpg)
Mapillary 2.32 with legacy API
![legacy](https://cloud.githubusercontent.com/assets/19908085/16798756/ded0dfd4-48ed-11e6-9819-5f0bb2270fe6.jpg)
google camera
![goo](https://cloud.githubusercontent.com/assets/19908085/16798755/ded0da66-48ed-11e6-9077-faee751bf1b2.jpg)

**Comment by PTMaper** [comment]
Still the same problem in 2.37. Seems to be a Camera 2 API issue. It works with the old API.

**Comment by gyllen** [comment]
Looks to me that the whitebalance is of. Maybe we have it in some fixed mode. Can you upload example pictures again @PTMaper

**Comment by rsahlin** [comment]
Another example is here:
https://www.mapillary.com/app/?focus=photo&pKey=cb3FbYZ7Dgya5y03l4-Csw&lat=47.20748027705426&lng=18.33117089860222&z=17

Camera information:
  Manufacturer: samsung
  Model:        SM-G930F

**Comment by simonmikkelsen** [comment]
When I (as a photographer) look at the image just before this post, my first thought is overly heavy noise reduction (gives blur but clean and smooth surfaces) + simmilar overly heavy sharpening (gives the wird edges). It could also be one of the "make my skin perfect" modes or simmilar.

**Comment by grinapo** [comment]
Seems to be S7 related?  S7 here and the same result, looks like someone running a sharpness filter on 500% power.

**Comment by grinapo** [comment]
New version (3.32) still same: Api2.0 bad, old api good. If you need I can set whatever combination you would like to try, pretty easy to test.

**Comment by grinapo** [comment]
On a cursory search some discussions popped up about broken api2.0 on samsung s6 and s7 phones. Seems to be a perfect candidate to implement camapi2.0 blacklist into the app..... :-S
https://forum.xda-developers.com/galaxy-s6/general/camera-api-2-broken-android-m-t3345491

**Comment by peterneubauer** [comment]
Nice find! We have added the model/manufacturer into the slogs. If you send them, beginning with the next public version and mention this issue, we can start building a baclklist!

**Comment by grinapo** [comment]
OUCH!
You seem to have removed the API2 switch from S7 and **set it to API2.0 fixed**. It is not impossible to make good images!
See iwSLyLNe2CpAVjdvKbZlVQ and all of them :'-(

**Comment by peterneubauer** [comment]
Ok! That is actually not that bad, since it's really a known bug according to StackOverflow. The device reports full Camera2 support but does not take good pictures. I think the best way to do this is to add the S7 to a Camera2 black-list. Can you send me the logs so I can see the reported model/devicename and do that @grinapo ?

**Comment by grinapo** [comment]
@peterneubauer sent you a drive link to the log.
But right now I cannot disable API2 at all. Wouldn't it be nice to have it back into developers options with a comment that 'beware'?

**Comment by peterneubauer** [comment]
Yes, I will put it back, coming out in the next version, under dev options. Android implementation compliance joys :)

**Comment by peterneubauer** [comment]
It's in, out in 3.44.

**Comment by grinapo** [comment]
(3.45-snapshot have a non-functional switch.)

**Comment by pbb72** [comment]
Why has this issue been closed? I am getting absolutely horrible photos from my S7. Mapillary version 3.56.

https://www.mapillary.com/app/user/pbb?lat=63.424215564210584&lng=10.42097615121827&z=17&pKey=HEvruHAi9hlD7WexQcuJ9Q&focus=photo

At the same time and location with an LG G5: https://www.mapillary.com/app/user/pbb?lat=63.42421943357493&lng=10.42102427272161&z=17.237304291637656&pKey=CP7SoOD_HCxKtrbf0hzbQg&focus=photo

**Comment by pbb72** [comment]
To make the problem a bit more obvious, here are two 200% crops from photos taken at the exact same time with an S7 and a G5. Looking at the S7 photo, it doesn't seem like a sharpening filter, but simply a blow-up of a very low-res image.

Galaxy S7:
![s7](https://cloud.githubusercontent.com/assets/1436366/26110422/961b21e4-3a52-11e7-80e2-e76c8e8a1a29.jpg)

LG G5:
![g5](https://cloud.githubusercontent.com/assets/1436366/26110424/988183c4-3a52-11e7-8c45-876c55846a65.jpg)

**Comment by grinapo** [comment]
@pbb72 you should select old API to use.

**Comment by katrinhumal** [comment]
@pbb72 can you please try if this helps? If not, let's reopen the issue.

**Comment by pbb72** [comment]
@katrinhumal I'm not getting these horrible artifacts anymore, though it still seems the quality is much lower than what I get from my LG. I will need to do a comparison with both camera's, but the weather is not very good at the moment.

However, I don't think this issues is solved at all by saying "Go into Developer Settings and enable Force Use of Legacy API". That is not a solution, that's a work-around! (And I'm not even talking about requiring the user to experience the problem first, then requiring them to do a web-search to end up at this GitHub issue to find these instructions.)

Before this issue can be considered Closed, the user should not even realize there has been any issue. Only if the app itself turns on legacy mode when necessary, can this issue be considered fixed.

**Comment by fgouget** [comment]
I'm running into the exact same issue on my Galaxy S7 (SM-G930F) running Android 7.0 with Mapillary 3.95. Furthermore checking the Settings -> Developer -> 'Force use of the legacy Camera API' checkbox makes no difference:

Mapillary regular: http://fgouget.free.fr/tmp/mapibug/Mapillary-regular-2017_09_19_16_50_19_591_+0200.jpg
Mapillary legacy: http://fgouget.free.fr/tmp/mapibug/Mapillary-legacy-2017_09_19_16_49_02_808_+0200.jpg
OpenCamera: http://fgouget.free.fr/tmp/mapibug/OpenCamera-IMG_20170919_165050_1.jpg

So this is still neither fixed, nor worked around through a blacklist and Mapillary is completely unusable on Galaxy S7 phones (which is quite galling since I bought one specifically because it has a good camera, quick autofocus, optical image stabilization for bumpy roads, and good GPS).

Since OpenCamera has no problem taking photos I guess that's what I'll be using now. Unfortunately it does not have a distance-based mode :-(

**Comment by katrinhumal** [comment]
Thanks for reporting! @ovivoda will take a look.

**Comment by ovivoda** [comment]
@fgouget @pbb72 

Please check out this APK and let me know if the image quality is improved:

http://android-releases.mapillary.io/Mapillary_Android_v3.96-SNAPSHOT1.apk

PS: You can leave "Settings -> Developer -> 'Force use of the legacy Camera API'" set to OFF.

**Comment by pbb72** [comment]
I haven't been having any problems on my Galaxy S7 anymore. Using version 3.95, legacy mode OFF.

These are some images I took recently: https://www.mapillary.com/map/im/pDsHnDV2uZmY2rD5c9RSmQ

**Comment by fgouget** [comment]
@ovivoda : As far as I can tell it works fine with Mapillary_Android_v3.96-SNAPSHOT1.apk. I took the same photo as yesterday (although there's a bit less light) and there was no sign of the artifacts. And that was with "Settings -> Developer -> 'Force use of the legacy Camera API'" set to OFF.
That's pretty encouraging!

**Comment by Cageythree** [comment]
@ovivoda Still bad quality for me on my S7 Edge (935F, 6.0.1).

**Comment by ovivoda** [comment]
@Cageythree can you please send me a image from your device captured with v3.96.

**Comment by Cageythree** [comment]
I haven't uploaded pictures to mapillary with this version yet, but here are two images I've just taken out of the window (I pulled the images from /Android/data/app.mapillary/files/mapillary/CAMERA2_0).  One image of a parking and one of a moving car.
![2017_09_20_17_33_56_294_ 0200](https://user-images.githubusercontent.com/20978969/30653358-2e77d7de-9e2b-11e7-87bb-a801afa86777.jpg)
![2017_09_20_17_31_39_524_ 0200](https://user-images.githubusercontent.com/20978969/30653368-3808c998-9e2b-11e7-8694-2081e5def1da.jpg)


It works fine with the legacy camera API option though.

**Comment by ovivoda** [comment]
Alright tx! The resolution is good but it seems that in the first picture the focus was on the window.

**Comment by Cageythree** [comment]
Yeah that might be true.

**Comment by grinapo** [comment]
@ovivoda my s7 seems to work as well just fine using force OFF.

**Comment by fgouget** [comment]
I went out for a walk today and it turns out this is not fixed :-(
http://fgouget.free.fr/tmp/mapibug/Mapillary-3.96-regular-2017_09_24_16_41_33_791_+0200.jpg

Unfortunately I did not test legacy mode during my walk but after I came back and noticed the issue I did a quick test and legacy mode did not seem to make a difference. I also rechecked and I'm still on 3.96-SNAPSHOT1.

**Comment by katrinhumal** [comment]
@fgouget Could you please try the 3.103 from Google Play now and see if the issue persists?

**Comment by fgouget** [comment]
I have retried today with Mapillary 3.104 (version code 404) and it works.
This time I tested with both legacy Camera API on and off, and both worked.

Interestingly in both cases the photos ended up in the LEGACY_CAM_0 folder. So I guess Mapillary detected my Galaxy S7 phone and automatically enabled the legacy mode. (unlike on the 24th I guess since the photos I took that day were in the CAMERA2_0 folder)

So it's good for me. Thanks!

**Comment by katrinhumal** [comment]
Thanks for reporting! @ovivoda looks like we can close this issue?

**Comment by fgouget** [comment]
Actually I've had the problem again today, still with 3.104 (version code 404). Forcing the use of the legacy Camera API fixed it, at least for a while. I suspect it has to do with how the Mapillary Android Activity gets started.

In the past I noticed that Mapillary tended to lose my settings. Most typically sometimes it would start taking picture every second instead of using "Distance based capture".

I suspect both issues are in fact tied and have to do with how Android resumes or restarts the Mapillary Activity. And I'll now refer to the Activity Lifecycle diagram on this page:

https://developer.android.com/guide/components/activities/activity-lifecycle.html

My theory is the bug only occurs when the Mapillary activity does not go through the normal onCreate() to onDestroy() cycle. That is I suspect there is a bug in the way the Mapillary activity restores its past state following an onStop() -> onCreate(), onStop() -> onRestart() or onPause() -> onResume() sequence. I would expect those to skip re-reading the configuration and performing auto-detection in order to restore the exact previous state instead. So, for instance, if the saved state activity stored "Force the use of the legacy Camera API = off" (which is the actual user setting although not the effective one since it was overriden by the autodetection code), then restoring from that setting without then reapplying the autodetection override would trigger the bug I'm seeing.

That does not explain the regular loss of the "Distance based capture" though (unless that setting is simply not part of the activity's saved state).

**Comment by pbb72** [comment]
Regrettably, I noticed yesterday that I am also still/again having the problem, using version 3.104.

https://www.mapillary.com/map/im/FykvSQ9kDCXacOtPX0bHEg

Looking back in my log, the problem started again between August 15 and September 17. (This could be because of a version change, but also may have been because of a phone reset.)

**Comment by lamerman** [comment]
https://www.mapillary.com/map/im/rcuTF1AajuXbchfhC_MrRA I also have very low quality image with Galaxy S7

**Comment by katrinhumal** [comment]
Thanks for reporting, everyone - and sorry that the problem has returned. @ovivoda will take a look soon.

**Comment by lamerman** [comment]
Even when using deprecated camera API on Galaxy S7 I still get bad images https://www.mapillary.com/map/im/gyaafY5pBUaStR6LjqaDqA

**Comment by ovivoda** [comment]
@katrinhumal http://android-releases.mapillary.io/Mapillary_Android_v3.102-SNAPSHOT3.apk

**Comment by pbb72** [comment]
@grinapo I think @ovivoda is referring to a general visual review of the photos. The halos and lack of detail are common results of applying an "unsharp mask" filter with too high a radius. (https://en.wikipedia.org/wiki/Unsharp_masking)

**Comment by pbb72** [comment]
Though I must say, to me it still looks like an upsampled low-res photo, not the result of oversharpening.

**Comment by ovivoda** [comment]
This is a camera issue on some of the Samsung devices mostly S7
