### ISSUE TITLE
Camera crash while shooting, then ERROR CAMERA IN USE

### ISSUE THREAD

**Issue by jfburke3** [mapillary/mapillary_issues#1934]
While shooting a sequence today, the Mapillary app crashed out of camera mode.  When I tried to go back in, I got ERROR CAMERA IN USE errors, then it eventually exited back to the menu.

Disabling/reenabling Camera2 API seemed to fix that.

Sending in trace logs in a few minutes.

**Comment by jfburke3** [comment]
Samsung Galaxy S7 Edge, Android 6.0.1, Mapillary app ver. 2.20

**Comment by rsahlin** [comment]
Camera reports in use error during capture.
According to Camera API:

int ERROR_CAMERA_IN_USE
An error code that can be reported by onError(CameraDevice, int) indicating that the camera device is in use already.

This error can be produced when opening the camera fails due to the camera being used by a higher-priority camera API client.

According to this spec this error should not be reported during capture, since the camera is already opened succesfully (by this thread)

After the error it was not possible to open camera.
[j_burke_06_08.txt](https://github.com/mapillary/mapillary_issues/files/306364/j_burke_06_08.txt)

**Comment by jfburke3** [comment]
I just e-mailed in some more logs about a similar--but not quite identical--problem.  This time, I started a new sequence, and it took one pic before it simply stopped taking pics.  It didn't crash out of camera mode as before.  I was able to reproduce it several times--look in the new logs starting around 18:50 today.

Disabling/reenabling Camera 2 API seemed to "fix" it.

**Comment by katrinhumal** [comment]
Closing this as outdated by now.

**Comment by jfburke3** [comment]
Well...it's still happening.

**Comment by katrinhumal** [comment]
@jfburke3 Do you think you could share logs of the CAMERA IN USE error for v. 3.41?

**Comment by jfburke3** [comment]
Well...no...because I've already upgraded to 3.43.

But if I can get it to happen in the "current" build, whatever that is when it happens, then I'll try to send logs.  I need to get in the habit of clearing the logs every time I start the app; that way y'all will only have a few hours of logs to look at, instead of days or weeks worth.

**Comment by katrinhumal** [comment]
@jfburke3 This is really helpful of you! Thanks so much. The logs clearing habit is also good in the sense that it can become quite a massive file in the end, unnecessarily taking up space. :)
