### ISSUE TITLE
Area Notification

### ISSUE THREAD

**Issue by thoschu96** [mapillary/mapillary_issues#1947]
Hey.. 

it seams that the Area Notification need a little Adjustment .
When i search for "Walldorf" it find's the other Walldorf what i am looking for.
There is a Walldorf next to Moerfelden.. 
Moerfelden itself, i can find .. But it's normaly found as "Mörfelden-Walldorf"...
So, i should find it , when i look for Mörfelden and/or Walldorf and/or Mörfelden-Walldorf.
The correct name/search is Walldorf(Hessen).. Same name as it's on the TrainStations and Google.

Cheers

**Comment by knikel** [comment]
@thoschu96: [These](https://whosonfirst.mapzen.com/spelunker/search/?q=walldorf#8/49.955/10.418) are the _Walldorfs_ you should be able to find through area notifications, since we're using Mapzen's search and WOF services for that.

@peterneubauer: Could it be that the shapes haven't been updated in a while, therefore we don't see them on our end?

**Comment by peterneubauer** [comment]
We have disabled area notification for the time being, closing this.
