### ISSUE TITLE
allow moving images out of the phone

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#1967]
when using an iphone with a mac, there does not seem to be a way to actually move the images from the phone to the computer.
https://github.com/mapillary/UserGuide/wiki/Transferring-Photos-From-Device describes a way to copy the images, but removal only seems to be possible from the app on the phone. that's extremely inconvenient, especially in a case when one has a lot of sequences they want to upload from the phone, but review a few sequences on the computer to remove incorrect images, for example.

**Comment by millenbop** [comment]
I agree, it's cumbersome. You can also delete images using iTunes where you copy the images. Just select what you want to delete and press CMD+BACKSPACE as you would normally delete files in Finder. I think this is more an Apple issue rather than a Mapillary issue tbh, so closing for now unless you have any suggestions on how we can make it better with what's possible within the Apple limitations.

**Comment by richlv** [comment]
oh. you actually can delete the images from itunes ? that's... bad usability :)
i tried all the buttons and right clicking. that feature is seriously hidden then. will test it next time, thanks for the info :)

**Comment by millenbop** [comment]
iTunes is quite horrible IMHO. Would much prefer it would behave as a normal USB memory stick :)

**Comment by richlv** [comment]
i was very surprised that it does not... but i'm sure there are a lot of excuses :)
