### ISSUE TITLE
map miss placed sequence preview

### ISSUE THREAD

**Issue by Cyrille37** [mapillary/mapillary_issues#1979]
Hi

Will exploring the map at (Saint-Paterne-Racan, France) http://www.mapillary.com/map/search/47.6043286522642/0.4806291050901734/15 **3 sequences are proposed** (at bottom left of the map).
- 2 are well placed sequences : http://www.mapillary.com/map/im/aZgol4LSCx9UBehRFNPtzw , http://www.mapillary.com/map/im/IMOEqPxBFiBnMz3G_jft_A
- **1 is really out of concerns** (show sequence in Paris, France) : http://www.mapillary.com/map/im/T4WlQbv1BmTIbK_k-Diigg

**Comment by de-vries** [comment]
I've seen this behaviour before. It happens because there is a long sequence close by, but when you click it you get to the first photo in the sequence.

Here is the track of the sequence: (in pink)
![selectie_135](https://cloud.githubusercontent.com/assets/1449609/16361903/464a9a80-3b9f-11e6-8812-09d813c607ca.png)

Ok, this sequence is not getting really close to were you linked to, but that's explainable because there are only two sequences in area you linked to. So what Mapillary does is adding the closest new sequence. Because that what this widget does, showing nearby fresh uploads.

But I have to agree that it's sometimes confusing when you get unexpectedly teleported.

**Comment by Cyrille37** [comment]
Thanks a lot for this fine investigation. I understand now.

But for "no geek" users it's a bug ...

Cheers

**Comment by gyllen** [comment]
@de-vries Thanks for find what this is, we will think about how to handle this
