### ISSUE TITLE
Android App stops taking pictures after a few photos

### ISSUE THREAD

**Issue by sb12** [mapillary/mapillary_issues#1981]
Recently I can't properly take pictures in riding mode. It always stops taking pictures after about 100-200 pictures. The interface looks like it still takes pictures but doesn't freeze on the single frames anymore. The app becomes very unresponsive and needs to be restarted to take pictures again.

This is the relevant part of the logfile:
[mapillary_trace.txt](https://github.com/mapillary/mapillary_issues/files/333809/mapillary_trace.txt)

**Comment by rsahlin** [comment]
Hi @sb12 and thanks for reporting!

I cannot find any camera exception, it just seems that the capture result is never delivered from the camera.
Please bear with me and I will investigate this soon, I currently have some other urgent features to deliver.

Thanks for your support!
Best regards
/Richard

**Comment by hob-gob-lin** [comment]
I don't know if I should open a new post, but I am experiencing a similar problem.  I have a Samsung Galaxy S6 phone and the Mapillary app randomly stops taking photos after 10-20 pictures.  Sometimes it stops after only one picture.  I can hit the STOP button, then start it again, so it has not crashed.  After reaching ~30 pictures, it will go on to take many hundreds without any further problems.  The shutter sound option has been useful so that I know when the app has stopped without having to watch the phone constantly.

**Comment by sb12** [comment]
The original problem hasn't occurred again for me since about end of July. Currently taking pictures works without problems.

**Comment by rsahlin** [comment]
Excellent @sb12 
Thanks for letting me know, I'll close the issue.
Please re-open if problem persists (on 3.X release)
