### ISSUE TITLE
move picture location is not working in Firefox 50

### ISSUE THREAD

**Issue by mxa** [mapillary/mapillary_issues#2072]
### Basic information
* Platform: `Web`
* System/Browser: `Linux Mint 18 Cinnamon 64, Firefox 50.0a1`

### Steps to reproduce behavior

 1. try to move an image in edit mode

### Expected behavior

image is moved to new location

### Actual behavior

image is not moved

### Additional information

works in Chrome (tested), possibly Midori (untested).

**Comment by pbb72** [comment]
Note that Firefox 50 is an alpha-release. I don't think it's fair to report bugs with that here, since it may also be a bug in Firefox.

Moving images in Firefox 47 (the current release) works well. Be aware that you need to keep the mouse button down for a second before it changes into image-dragging-mode (a "fist" pointer, as opposed to an open hand or a pointing finger, on Windows at least). If you're too quick, you don't move the image.

**Comment by mxa** [comment]
Works now in both 47 and 50. Did you change something?
