### ISSUE TITLE
How to hide sequence?

### ISSUE THREAD

**Issue by Andblue** [mapillary/mapillary_issues#2075]
By accident I managed to snap a few pictures while uploading. How do I hide/delete a sequence?

**Comment by peterneubauer** [comment]
Do you have a link to an image in that sequence? I will delete it, we are working on changesets for deleting content.

**Comment by Andblue** [comment]
Here is a picture in the sequence. Thanks!

https://www.mapillary.com/app/user/andreas.p?lat=59.29354666666666&lng=17.98447166666667&z=17&pKey=z2d96zceHEmpHalC-egkrA&focus=photo

**Comment by Caboosey** [comment]
@peterneubauer I need to hide these photos because a phone call came in that I didn't answer and for some reason mapillary (v2.34) on Android kept using old GPS coordinates/location info with theses following photos:

https://www.mapillary.com/app/?lat=30.4948698&lng=-87.3275782&z=17&pKey=GvnEqVv1YOzXFt19D7wvmg&focus=photo
https://www.mapillary.com/app/?lat=30.4948698&lng=-87.3275782&z=17&pKey=QDJrNmXZJv8_7W76salufA&focus=photo
https://www.mapillary.com/app/?lat=30.4948698&lng=-87.3275782&z=17&pKey=QYK4X9zBhw-FJg-i41_gDg&focus=photo
https://www.mapillary.com/app/?lat=30.4948698&lng=-87.3275782&z=17&pKey=K0mbAcwGsQ8YSmnChYbRKw&focus=photo
https://www.mapillary.com/app/?lat=30.4948698&lng=-87.3275782&z=17&pKey=vCofEIk-6xZv0eIKKBNU_g&focus=photo
https://www.mapillary.com/app/?lat=30.4948698&lng=-87.3275782&z=17&pKey=WvtdRJVCUqnhfU0tu672UQ&focus=photo
https://www.mapillary.com/app/?lat=30.4948698&lng=-87.3275782&z=17&pKey=WC1TaQlTX3ZTvcfVPk_cYA&focus=photo
https://www.mapillary.com/app/?lat=30.4948698&lng=-87.3275782&z=17&pKey=elkljCr_Y-R8oVkdyRjx6Q&focus=photo
https://www.mapillary.com/app/?lat=30.4948698&lng=-87.3275782&z=17&pKey=7UGyGZAPjr-KO431-nbwgw&focus=photo
https://www.mapillary.com/app/?lat=30.4948698&lng=-87.3275782&z=17&pKey=PwRFfT1N_tJZhvW8s83_Tg&focus=photo
https://www.mapillary.com/app/?lat=30.4948698&lng=-87.3275782&z=17&pKey=Q5gqArDjBmqMVpeJ7l_qbw&focus=photo
https://www.mapillary.com/app/?lat=30.4948698&lng=-87.3275782&z=17&pKey=HlCrxJ9hPRnv9zwFTQWIfg&focus=photo
https://www.mapillary.com/app/?lat=30.4948698&lng=-87.3275782&z=17&pKey=BU9AruEXt0C4R73gqR2P7w&focus=photo
https://www.mapillary.com/app/?lat=30.4948698&lng=-87.3275782&z=17&pKey=sPP_rki3g363H_aUIB-vxw&focus=photo
https://www.mapillary.com/app/?lat=30.4948698&lng=-87.3275782&z=17&pKey=xOmi1f5DZCV8n5LAij9SCw&focus=photo
https://www.mapillary.com/app/?lat=30.4948698&lng=-87.3275782&z=17&pKey=yVxwPtO0sDViQj3lP4MMqQ&focus=photo
https://www.mapillary.com/app/?lat=30.4948698&lng=-87.3275782&z=17&pKey=vhHwqdTktQ7QvLesYpPImQ&focus=photo
https://www.mapillary.com/app/?lat=30.4948698&lng=-87.3275782&z=17&pKey=JSILKrLhd9dW1gXHaeFzHw&focus=photo
https://www.mapillary.com/app/?lat=30.4948698&lng=-87.3275782&z=17&pKey=Gn_269vNO2WJxC6SMP7Ltg&focus=photo
https://www.mapillary.com/app/?lat=30.4948698&lng=-87.3275782&z=17&pKey=x1da2F4-rjffN-YlXrTX6g&focus=photo
https://www.mapillary.com/app/?lat=30.4948698&lng=-87.3275782&z=17&pKey=MkzhxQthpu4mxGSz5q2IbQ&focus=photo
https://www.mapillary.com/app/?lat=30.4948698&lng=-87.3275782&z=17&pKey=2RjxA8-jCXKVYCxM5K_d0A&focus=photo
https://www.mapillary.com/app/?lat=30.4948698&lng=-87.3275782&z=17&pKey=rTqtmuLK0RVfLc1oXHMDgA&focus=photo
https://www.mapillary.com/app/?lat=30.4948698&lng=-87.3275782&z=17&pKey=YTzt80VZBO6UwGUEajM9Gw&focus=photo
https://www.mapillary.com/app/?lat=30.4948698&lng=-87.3275782&z=17&pKey=EtBJ6F0Yp7h6WrlbhYBivQ&focus=photo


This needs to split from the rest of the sequence (This is where GPS location info is good again):
https://www.mapillary.com/app/?lat=30.4881147&lng=-87.323256&z=17&pKey=P4RLiVfR4fB8MxxSZOWtOA&focus=photo

**Comment by peterneubauer** [comment]
IMHO, just go in and edit the locations of these images in the editor, or delete them? Closing this for now.
