### ISSUE TITLE
Redirect certain domains instead of sending errors

### ISSUE THREAD

**Issue by floscher** [mapillary/mapillary_issues#2115]
The following domains (i.e. all URLs with this domain) should be redirected. Currently you get an error when trying to open them, in Chromium the error is called `ERR_CONNECTION_REFUSED`, in Firefox it is called `Unable to connect`.
- [x] https://mapillary.com → https://www.mapillary.com
- [x] http://a.mapillary.com → https://a.mapillary.com

Maybe you can also additionally send an [HSTS header](https://httpsecurityreport.com/best_practice.html#hsts) for the https-site, so the users are redirected client-side as soon as they have already visited the domain in the past.

**Comment by gyllen** [comment]
@peterneubauer We need to sit down and figure out this HSTS thing for whole backend.

**Comment by ArtificialTruth** [comment]
@peterneubauer 
Related to this issue; Redirect http://forum.mapillary.com/ -> https://forum.mapillary.com/ so people don't get hacked while entering their login details on a open wifi network or similar.

**Comment by floscher** [comment]
The redirect from `http://a.mapillary.com` to `https://a.mapillary.com` is broken again.
Both http://a.mapillary.com and https://mapillary.com now both time out (no longer the errors mentioned above).

**Comment by gyllen** [comment]
@martinskans elevate

**Comment by martinskans** [comment]
@gyllen is <nothing>.mapilllary.com hosted somewhere else cause it's pointing to a non-aws ip?

**Comment by floscher** [comment]
@martinskans `mapillary.com` only redirects to `www.mapillary.com`. According to the HTTP header, it is served from a `Microsoft-IIS/7.5` server, using `ASP.NET 4.0.30319`.

The redirect happens in a strange way:
* 302 redirect from `http://mapillary.com` to `http://mapillary.com/WZZXk/` (the path can vary, seems to be 5 random characters)
* 302 redirect back to `http://mapillary.com`
* 301 redirect to `https://www.mapillary.com`

**Comment by martinskans** [comment]
@floscher Thanks! I am trying to find out internally if that is hosted somewhere where the site was running at some point before my time here so that I can get rid of that strange behaviour. Also we do not use asp anywhere so that adds to my suspicion that it is some old thing that has been setup to redirect. The random characters may be an old hack to avoid caching behaviour. I think I should be able to just get rid of it completely - just want to check with the team first to make sure there are no catches. I will update you here once I am done!

**Comment by martinskans** [comment]
HTTPS works now for `mapillary.com` as well.

**Comment by floscher** [comment]
Great, thanks!
