### ISSUE TITLE
Bring back (and extend) filtering

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#2124]
I liked the filter feature in the old website a lot. There is now only very minimal filtering, to show only your own photos.

I would like the full filtering back, and possibly with these additions:
- Show only 360-degree photos.
- Show only photos pointing forward/backward/left/right.
- Show photos taken in summer/autumn/winter/spring.
- Show photos taking in morning/midday/afternoon/night.
- Show photos with missing direction information.
- Show photos that are too far from other photos (ie, no direction arrows).
- Show photos that are taken by foot/bike/car (filter by speed)

**Comment by gyllen** [comment]
Since we use vector-tiles we can do a lot of this filtering in the client. Whats easy todo is

1. 360 is in tiles so would be easy on lower higher zoom levels 14 and above
2. All time filtering is pretty easy, for specific times like season and time of day we need to be clever with the coordinates so this will likely only work on higher zoom levels too.
3. Missing direction, since direction is also stored in tile

Whats hard todo is
1. Photos to far from other photos. This needs some spatial lookup which I fear will be to haevy for the browser.

**Comment by gyllen** [comment]
@angelday Feedback for filters

**Comment by pbb72** [comment]
I guess relative direction (forward/backward/left/right) will also be heavy, because you will have to look at the direction towards the next photo in the sequence. But probably less heavy than checking the distance to other photos.

**Comment by richlv** [comment]
360 filtering is there, i guess others still missing

**Comment by gyllen** [comment]
Added to idea box around filtering

@angelday FYI

closing
