### ISSUE TITLE
Let users rotate images

### ISSUE THREAD

**Issue by blobgo** [mapillary/mapillary_issues#2142]
### Basic information
- Platform: `Web`
### Steps to reproduce behavior

See https://github.com/mapillary/mapillary_issues/issues/1892
### Suggestion

Please let users rotate images (the same way it is done with blurring images) in the browser, so users can fix this issue by themself.

**Comment by gyllen** [comment]
Our idea here is to use vision to automatically detect if an image is rotated and then do rotation for you without you having todo anything.

**Comment by mrbrown8** [comment]
If there are photos that need obvious correcting, what's the SOP for this?

Example:  http://mapillary.com/map/im/UBbDkeYrPwDBfqojlKX3sg

**Comment by ybkuang** [comment]
@mrbrown8 The automatic detection of wrong rotations will serve as a helper for this task, so that you don't need to go through all your uploads. 

And sure, we will have errors in the automatic detections. Therefore, on the side of this, we will also have the editor for users to manually rotate the images for those cases (as in blurs cc @blobgo). And we will use feedback from users to make the detection better and less manual work in needed.

**Comment by ybkuang** [comment]
mapillary_issues is no longer an active repository.
This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!
