### ISSUE TITLE
Bottom half of mini-map doesn't react to mouse

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#2156]
### Basic information
* Platform: `Web`
* System/Browser: `Firefox, Chrome`

### Steps to reproduce behavior

 1. Open a photo view, with the small map in the bottom left corner.
 2. Move the mouse cursor to the bottom half of the map.
 3. Try to zoom in/out by using the scroll wheel.
 4. Try to drag the map around.
 5. Try to active a photo by clicking on it.

### Expected behavior

This should work just like it does in the top half of the map.

### Actual behavior

Nothing happens. The map doesn't receive any of the mouse events.

### Additional information

Haven't noticed this before. Did this come with the latest update, or have I just never used the mini-map so much?

**Comment by gyllen** [comment]
Thanks for reporting issue is tracked and will be fixed in upcoming release.

**Comment by nickplesha** [comment]
@pbb72 This issue appeared when we added the map controls to the bottom-right corner of the map (so it was noticeable in the corner of the large map as well) due to a bug with how Mapbox Gl handles this. Luckily, it was easy to add a fix on our side while we wait for the next Mapbox Gl release so the map should work as expected now.

**Comment by pbb72** [comment]
Confirmed as fixed, thank you very much!
