### ISSUE TITLE
Missing documentation on needed Photo Sphere XMP Metadata 

### ISSUE THREAD

**Issue by kertase** [mapillary/mapillary_issues#2163]
Hello,

I am trying to upload spherical photos but I am missing the XMP Metadata.

I would like to know what xmp tags Mapillary needs to recognize and display Photospheres correctly but I cannot find anything about it in the documentation. 

It would be nice to document the needed data for this.

Thanks

**Comment by gyllen** [comment]
@ybkuang  Do we have a somewhere were this is documented?

**Comment by ybkuang** [comment]
@kertase We are following this https://developers.google.com/streetview/spherical-metadata

**Comment by kertase** [comment]
Thanks for your swift reply.

There are a lot of possible fields in the specification are the , if I may reformulate my question which fields are required by mapillarý?

**Comment by ybkuang** [comment]
There are the field we are parsing

`CroppedAreaImageHeightPixels`
`CroppedAreaImageWidthPixels`
`FullPanoHeightPixels`
`FullPanoWidthPixels`
`CroppedAreaLeftPixels`
`CroppedAreaTopPixels`

Additionally, it will be good to have `PoseHeadingDegrees` (compass direction). 

Unfortunately though, we are not currently using the `GPano` information for partial panorama (not 180x360 field of view) in the viewer. But it will still be good to have the information available i.e. once we add the support for it, the panoramas will display correctly. 

If you want to show the panorama correctly before our fix, you can add black padding to the partial panorama (so that it is 180x360 field of view).

**Comment by kertase** [comment]
Thanks this clears things up. Would be nice to add in the doc like in https://github.com/mapillary/UserGuide/wiki/Uploading but I don’t know which page fits best…
