### ISSUE TITLE
provide "basic zoom" for blur editing

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#2179]
the new interface has zoom - which is great. but the zoom now is sort of putting even single photos on a sphere. this is fine in the viewer, but in the blur editor it makes things more difficult - the image portion that is visible becomes sort of rotated, thus one can never be sure how the blur rectangle will come out.

for example, if there's a licence plate that is displayed horizontally aligned, the blur rectangle might go up or down when drawn to the right. it sometimes requires a few attempts to estimate the starting level.

it would be great if the blur editor used "basic" zoom without distorting the image

**Comment by gyllen** [comment]
@richlv I see your point. Im not sure if this is something @oscarlorentzon can think about implementing in MapillaryJS.

**Comment by richlv** [comment]
this seems to be resolved a long time ago - please feel free to close unless there are other improvements planned

**Comment by oscarlorentzon** [comment]
@richlv We do not provide the basic zoom you requested above in MapillaryJS but we have made some changes since the issue was originally reported. Most importantly the viewer bounces back when trying to look outside the boundary of a regular image.

It is not a priority to provide basic zoom in MapillaryJS at this point. If you do not feel that it is important to keep the issue open we should close it.

**Comment by richlv** [comment]
indeed, the zoom is still "sphered", but it's not such a huge issue, closing
