### ISSUE TITLE
Offer direction camera is pointing in app

### ISSUE THREAD

**Issue by james2432** [mapillary/mapillary_issues#219]
I think it would help a lot if you offered a way to tell the app where the camera is mounted/pointed for sequences. Example: camera is mounted on right side and pointing towards the right side, this could give the application an offset to work with when tagging the image with the directional data. So far it seems to only be tagging with the direction of travel, which might not be accurate at all if it's not mounted to point forwards.

**Comment by knikel** [comment]
@gyllen, @jesolem I think this issue is more related to exposing _lock_ compass angle functionality before the photos are taken. The editor part of this issue could be solved by allowing the user to adjust compass angle at once for the whole sequence, right?

**Comment by polarbearing** [comment]
Yes setting a fixed angle offset from the forward lock is a long-missing feature now. Going to edit every sequence in the web editor is still a major hassle.

**Comment by polarbearing** [comment]
The label of this issue should point to the app, not the editor.

**Comment by jesolem** [comment]
Thanks @polarbearing -> updated and reassigned

**Comment by peterneubauer** [comment]
Yup, it's mostly a UI think - how would we visualize different offsets, and when should we reset it to avoid false offsets in the next sequence?

**Comment by polarbearing** [comment]
We already have the compass lock icon in the bottom-right area. That could be given a warning colour when offset and display the value. 

The offset could be reset when the app is started, since that would be the same action as mounting and adjusting in the windscreen.

In this context you could review the "Compass locked forward" button in the settings, which should change when I change between walking and riding mode. Currently it behaves a bit inconsistently. the offset button should then sit next to it.

**Comment by peterneubauer** [comment]
closing, done.
