### ISSUE TITLE
Feature Request: using SFM for GPX/OSM matching

### ISSUE THREAD

**Issue by blaueente** [mapillary/mapillary_issues#2201]
**Problem:** 
I have an action cam and track the GPS with my phone. It is quite tiresome to align both afterwards exactly, e.g. because of time drifts due to battery changes. I use JOSM for that, and I need to try&error a lot 
**Idea 1:**  (enhancement to #1303)
I would like to upload the images and the GPX unmodified as they come from the camera and phone.
Using SFM you apparently can extract a basic camera movement track. Can you use this to automatically adjust the time difference between GPX and images? Even better, if there are a limited number of battery changes in the photo stream which insert additional time drifts?
**Idea 2:**
Assuming the OSM data in the photographed area is fairly complete, would it be sufficient to upload the images only, and then use SFM to coarsely match the images to the OSM way data, and then refine the images location relative to the OSM using SFM?

**Comment by gyllen** [comment]
@blaueente I have seen other people doing matching against OSM data but for me the license is unclear. If we match against OSM data I _think_ the whole database would need to go ODBL. Looping in @jesolem

**Comment by HolgerJeromin** [comment]
Cc @simonpoole as he is a license expert

**Comment by simonpoole** [comment]
The improved positions would in principle create plus whatever key you require to reference the photograph would likely be considered to be a Deriviative Database, but could be used together with other data as per Collective Database guideline http://wiki.osmfoundation.org/wiki/Licence/Community_Guidelines/Collective_Database_Guideline_Guideline .

**Comment by jesolem** [comment]
@blaueente Thanks for your suggestions.

*Re idea 1:* 
We have thought about this and I _think_ it could work. There are many ways it can fail though so you need to set it up so that the result can be reviewed by a human before accepted. Ideally do this client side before upload but I think that will be hard. We'll keep thinking about how to do this. 

*Re idea 2:* 
I'm interpreting this as "map matching to OSM road segment, then adding back the diff as determined by SfM". Interesting and we have not thought about that. We are planning to do map matching and we could have 3 versions of a sequence in this case ("raw", "matched", and "matched with SfM").

**Comment by jesolem** [comment]
@simonpoole Thanks for the link and great to see that guideline adopted! I think I get how this would work. 

**Sanity check**
What we're planning on doing is to create a database containing Mapillary sequences (lat, lon, image, and relevant metadata), call this SDB. Then we map match that data in SDB to OSM road segments using the Meili Valhalla module. This will enable us to do routing, stats and coverage tiles. We then share the SDB under ODbL so that others can download and build their own tools and ideas. We could also add ODbL to the Valhalla tiles and coverage tiles of course but those are direct computations from SDB so not sure it matters. Then if we use this SDB data in combination with other data in our services, that would fall under Collective Database.

Did I get that right?

**Comment by simonpoole** [comment]
@jesolem yes.

**Comment by jesolem** [comment]
@simonpoole Excellent. Thanks for your help.

**Comment by jesolem** [comment]
Closing and please continue the conversation on the forum if there is anything to add. https://forum.mapillary.com/
