### ISSUE TITLE
Broken links in "Changeset approved" email

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#2225]
The emails that are send out when a changeset has been approved (subject "xxx commented on your photo"), contain many broken links.
- The link "photo!" seems to contain an invalid photo id. (One mail leads to http://www.mapillary.com/map/im/OmXmLn419lT0X83yUXLQiQ, another to http://www.mapillary.com/map/im/BfkjgMXtI7GazUZgBSI91M, both are invalid.)
- The URL to the photo that is embedded in the email returns an "Access denied" error. (The links are https://d1cuyjsrcm0gby.cloudfront.net/OmXmLn419lT0X83yUXLQiQ/thumb-320.jpg and https://d1cuyjsrcm0gby.cloudfront.net/BfkjgMXtI7GazUZgBSI91M/thumb-320.jpg.)
- The photo is also linked to the same address are the "photo!" link.
- The map is linked to https://www.mapillary.com/app/?lat=0.0&lng=0.0&z=15

All other links in the email seem to work fine.

**Comment by gyllen** [comment]
@peterneubauer see above ^^^

**Comment by peterneubauer** [comment]
If this is the "approved/created" changeset comment - the link actually refers to a changeset, but you are seeing the old feed that thinks this is a comment on an image. We will change that soon going forward. Since the links refer to changesets, the correct link is e.g. https://www.mapillary.com/app/?changeset=OmXmLn419lT0X83yUXLQiQ

**Comment by peterneubauer** [comment]
closing this for now, the issue is quite old and not relevant anymore.

**Comment by pbb72** [comment]
Indeed
