### ISSUE TITLE
Add exclusive filters

### ISSUE THREAD

**Issue by knikel** [mapillary/mapillary_issues#2229]
From [this](https://forum.mapillary.com/t/where-are-the-filters-in-the-new-mapillary/632/8) forum thread,
e.g. searching for `not:username` (or a toggle somewhere, as I'm not sure whether we want to build a query language in the search box) will display all the coverage from the given area from all, but the given user.

**Comment by knikel** [comment]
Assigning @amahon to consider this as a feature.

**Comment by pkoby** [comment]
Has there been any progress on this feature? I've actually wanted this for some time, and just considered adding a request, but I saw it has been suggested.

**Comment by madelenarnesdotter** [comment]
@pkoby the Mapillary Forum will from now on be the place to file and discuss feature requests, we're currently pulling issues from this repo into the forum to keep it all in one place. Please come and join us over there: https://forum.mapillary.com/t/where-are-the-filters-in-the-new-mapillary/632/11 (because this one originally appeared in the Mapillary Forum, we're not duplicating it back)
