### ISSUE TITLE
broken sequences

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#2237]
here are a few sequences that would benefit from a bit of cleanup.
first, a few that connect images across huge distances - and also over several years. it might be enough to properly split them (but i couldn't find a way to do that in the interface).
- http://mapillary.com/map/im/-efScemyPMW6FSe_eLzeoA
- http://mapillary.com/map/im/pFWQd5bxaCSwiciz4rb8pA
- http://mapillary.com/map/im/D4zoADI7KcCmvVZL_dpsQw
- http://mapillary.com/map/im/8IeNCU80vBYV5t8H9FcH8g
- http://mapillary.com/map/im/LqtSArfiTnAFWP13758cEw
- http://mapillary.com/map/im/HNKTTc8mrUI3Nq7LeyMraw

there are likely more - it might be a good idea and automatically find & split all sequences that have gaps, bigger than 500m or 1h.

and here's a sequence where first the coordinates stopped updating, and then the images jumped to the other side of the building. i find the browser based editor to be way too cumbersome to edit something like this...
- http://mapillary.com/map/im/XCIqZ2vXp-Yvw4TGeFAFDA

**Comment by danbjoseph** [comment]
Would be nice to have a way to split sequences once uploaded. Or even have some server process to do it automatically when there is some vast distance between images? I used the python tools to split action camera pics into folders by sequence but sometimes something didn't work or I messed something up such as with sequence `I-TsxHoBQt00SnwoXw--Ww`

**Comment by gyllen** [comment]
@danbjoseph We should have a bot that does the splitting. Need to look into if its doing its job properly though.

However it would be nice if the manual uploader automatically splitted the sequences too.

**Comment by danbjoseph** [comment]
Here's another example where the last two photos in the sequence are way off. 

adjacent in sequence: `Sk3Ap7txp5k3wh3UGnwIfA` the photo `TKs9wWtZyMfnR5zqso239Q` is an hour before photo `5n-a9vjp3zpZ5PrEqdb-HA` and separated by significant distance

i've been using sequence_split.py and not specifying cutoff distance or time because i thought both had defaults (though I'm not seeing that in the readme for distance so i'm not sure why i thought that, a blog post maybe?). may be the problem.

**Comment by danbjoseph** [comment]
also not sure why the python scripts broke apart sequence `cg3XJSgElJJSOd-MiwarfA` and `Sk3Ap7txp5k3wh3UGnwIfA`

**Comment by richlv** [comment]
i just thought that the new interface doesn't have splitting options in the editor so was ignoring broken sequences for some time :)

here's another recent one that is weirdly connected : https://www.mapillary.com/map/im/XNUbR57-aWJE2QB5iX02aA

**Comment by danbjoseph** [comment]
another example of where it'd be useful to request a sequence split. 
here's an example where the image max imposed by `sequence_split.py` put a break in the sequence where there doesn't need to be (the hovered image) and then kept the sequence together (because of the parameters i passed) where it really shouldn't be (the big jump between the selected image and the next)

![screen shot 2018-01-02 at 8 48 06 am](https://user-images.githubusercontent.com/4806884/34485723-0d5df5ea-ef9a-11e7-813c-fa21dbf9dd85.png)

**Comment by ybkuang** [comment]
can you share with us the link to the sequence? Will be great if we can see the parameter that you used for the split as well. Thanks @danbjoseph

**Comment by danbjoseph** [comment]
sequence is `TRYSnkCFEPavQ7-beqAucw`
was `python sequence_split.py /path/to/folder/ 100 120`
(when i've let it run with the defaults, i always seem to end up with a way too large number of sequences. i should probably fine tune and remember what i use for driving vs biking.)

**Comment by ybkuang** [comment]
We currently cut the sequences if the distance is large than 300 meters. We will revisit if we should use a small threshold. 

mapillary_issues is no longer an active repository.
This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!
