### ISSUE TITLE
sequence and blur editor hangs on next photo

### ISSUE THREAD

**Issue by jotpe** [mapillary/mapillary_issues#2257]
Blur editing this sequence https://www.mapillary.com/app/?lat=50.910309&lng=7.023926&z=17&focus=photo&pKey=oLTUUyfWI-SjDQEucanbKQ&menu=false 
often does not load the next image. The loading circle is rotating all the time.

Chromium Version 53.0.2785.89 Built on 8.5, running on Debian 8.5 (64-bit)

**Comment by jotpe** [comment]
Maybe related to #1472 ?

**Comment by gyllen** [comment]
I think this has todo more with the length of the sequence then the blur functionality. At the moment we are not handling long sequences correctly. We are working on making this much faster though.

**Comment by oscarlorentzon** [comment]
Tracked in mapillary/mapillary-js#191.

**Comment by oscarlorentzon** [comment]
We have made some performance improvements in the latest version of MapillaryJS which has been deployed on mapillary.com. Walking through this sequence works fine in both `blur` mode and in the regulare viewer for me now (when clicking the next button really fast there may be some loading from time to time because we need to fetch the images to show in the veiwer). 

Closing.
