### ISSUE TITLE
Max sequence length in apps

### ISSUE THREAD

**Issue by HolgerJeromin** [mapillary/mapillary_issues#2289]
To be able to easier review the images on device and later in web editor i try to keep the sequence length under 200 images. 
Monitoring the count and stop/start capturing while driving seems dangerous. 
So we should have in both apps a settings for starting a new sequence after X images. Same as we have for Max distance.

**Comment by gyllen** [comment]
I think this is a great idea. Longer sequences causes havoc in the system in many cases. Maybe 200 is a bit small though. I would suggest 1000.

**Comment by HolgerJeromin** [comment]
OK, put into a setting and default it to 1000 8-)

**Comment by peterneubauer** [comment]
However, that doesn't take care of manual uploads etc. I think we need to have the cut on the server side to be really effective. Also, auto-cut sequences would result in a LOT of review work if you get like 10x as many seuences per capture?

**Comment by HolgerJeromin** [comment]
I always view all my sequences before upload. But I have not always time for review very large sequences, because you can not have a break while doing one. That is why I prefer a length which is reviewable in a small time frame.

**Comment by kaitu** [comment]
@peterneubauer: I oppose the auto-cut server side of the manually uploaded sequences, since I'm afraid that would make tracking sequence review work a big mess. Also, I regard the automatic cutting sequences at arbitrary points, based only on sequence lenght, as suboptimal. If you want to limit the sequence lenght, better to do so at upload time, so that the user is aware of the limitation and can decide reasonable cut points.

@HolgerJeromin: I concur, reviewing long sequences can be problematic. But I'd definitely welcome a mechanism to easily resume the review of a sequence, over arbitrary sequence cuts.

**Comment by HolgerJeromin** [comment]
This was implemented in the beta Android app according to the changelog.

**Comment by peterneubauer** [comment]
Done, set to 600 photos in Android.
