### ISSUE TITLE
blurred plate number becomes visible when reviewing sequences

### ISSUE THREAD

**Issue by govvin** [mapillary/mapillary_issues#2296]
### Basic information
* Platform: `Web`
* System/Browser: `Chrommium`

### Steps to reproduce behavior

 1. Check out this sequence: https://www.mapillary.com/app/?lat=14.5921563&lng=121.0377441&z=17&pKey=06CqED3p6ry659k4NTQ_Jg&focus=photo
 2. If you move through the sequence (arrow keys on top of the screen) once, then back again, any user can read the blurred car plate number

### Expected behavior
Plate numbers should remain blurred even while manually going through a sequence

### Actual behavior
Plate number is discernible.

**Comment by nicolas17** [comment]
Did you manually blur it? Maybe your browser (or the CDN server) is still caching the old image without the blur.

**Comment by gyllen** [comment]
@govvin Yes it takes some time for the caches to be cleared. Can you check back now and report?

**Comment by govvin** [comment]
Hello. The blurring was automatic, and the video was uploaded 4 days ago. 

@gyllen , the plate number is still visible between the animated sequences.

**Comment by nicolas17** [comment]
Okay, I looked at the sequence in question. This has nothing to do with the animation or with switching between photos. The photo you linked has the license plate blurred, but the [next one](https://www.mapillary.com/app/?pKey=ZV8oMLuaJzA98vFF39-1DA&focus=photo) doesn't, the license plate is plainly visible. It's possible that on a 16:9 monitor with the browser maximized, when you look at that photo by itself, the bottom of the photo is cropped, so you only see the license plate in the middle of the animation, but you can also just drag to look down and see it.

This is fixed by manually blurring the license plate on that one photo, which I did now (may take some time to be visible).

**Comment by gyllen** [comment]
@nicolas17 Thanks for explaining and fixing 👍
