### ISSUE TITLE
Other user's activity to my photos showing up in my activity feed

### ISSUE THREAD

**Issue by ToeBee** [mapillary/mapillary_issues#2304]
I have been busy at my day job all afternoon and haven't touched Mapillary. Yet when I just pulled up my activity feed it claims that I submitted several blur requests and edited a picture. I also just got an email saying that user `gitne` blurred some of my photos. It looks like his activity is being assigned to me in my news feed.

I did none of these things:
![image](https://cloud.githubusercontent.com/assets/348948/19289437/63bf7ab0-8fd0-11e6-81f6-9f5a16e9cc4d.png)

**Comment by gyllen** [comment]
I think the messages are misrepresented in the feed. What they should say is that `gitne` has blurred some of your images and also edited some of your images. We are currently working on a big notification update that will straighten these things out.

**Comment by jfburke3** [comment]
I know that gitne has done a lot of blurring on quite a few of my images, and yes, they are mine.

**Comment by GITNE** [comment]
@ToeBee Yes, I have been blurring quite a bit. Not only your photos. I have also been requesting delete edits where photos have been shot on private property or photos that depict nothing but the ground.

I am sure once Mapillary developers revamp the notification system things will get into proper perspective again. Since the relaunch of the website Mapillary is making visibly positive progress. It is not fast but it is good.

**Comment by gyllen** [comment]
The messages should now be clearer.
