### ISSUE TITLE
take images every x meters instead of every x seconds in bike/car mode

### ISSUE THREAD

**Issue by HolgerJeromin** [mapillary/mapillary_issues#247]
With cobble stone it is not easy to keep the phone stable. If i drive very slow the app tells me to move faster. Driving faster the images are not really good.

Better would be renaming the "sequence frequency" to "minimal photo frequency" (to honour old phones) and use a "minimal photo distance" of 10 meters (or whatever) with bike/car mode.

Related to #242

**Comment by PolyglotOpenstreetmap** [comment]
It seems to me that it would help a lot if it were still possible to make pictures manually, even when in time/lapse mode. I discovered the volume buttons work as shutter buttons too. Since that discovery many of my pictures are taken upside down. The upside is that I can keep my gloves on.

**Comment by pbb72** [comment]
This will only work for distances greater than the precision radius of the GPS. For example, if your GPS reception gives a precision of 8 meters, then the application could theoretically receive information that you moved up to 8m while you're standing still. I think Mapillary accepts a precision of up to 16 meters. This means you can only have a minimum photo distance that is > 16 meters.

**Comment by jaakkoh** [comment]
@pbb72 This is true looking at things in a simplified way.

If the app would be smart / capable enough to detect that movement is occurring in a pattern that is not as erratic/random as the typical movement of the wondering GPS coordinates measurement error then it would still take photos even every 5 meters (with a "theoretical" guesstimated 16m (in)accuracy).

My own touch and feel is (for which I've done some measurements testing too) that once a device is moving its practical accuracy will go up quite a lot. On average :)

In any case, with Mapillary's one strong use case being highway mapillarying I would still want to see the photo every x meters feature -- given that e.g. 108 km/h translates to 30 m/s and with a photo every 2 seconds that means that you'll get a photos every 60 meters.. Surely a typical phone's processor won't be able to handle a photo even every 15 meters (2 photos per second) -- but the point stand.

**Comment by HolgerJeromin** [comment]
my main point is bicycle mapping. Often i am to slow to be over the threshold but >30 meter from the last image.

**Comment by pbb72** [comment]
90 % of my mapping is on foot, and sideways :-) I try to make seamless sequences of the street fronts (i.e. all shops in the street showing up) which practically means a photo about every 5m.

**Comment by jaakkoh** [comment]
@pbb72 .. and so this feature doesn't make sense for foot mode. But to cover the world (within the next century) it would be beneficial to support other modes of movement fluently too :)

**Comment by pbb72** [comment]
I think this would indeed make things easier/cleaner for speeds over about 30 km/h.

**Comment by kaitu** [comment]
My shootings in driving mode often result in an overabundance of pictures on straight stretches, while I miss plenty of information in winding parts.
If taking a picture every x meters can be implemented, maybe the x could also be automatically lowered to trigger some sort of burst mode as soon as a change of the  direction of travel is detected (while at the same time it would be good if the steady picure setting would ignore the horizontal accelerometer readings).

**Comment by rsahlin** [comment]
Hello all!

This mode is now implemented as default mode, instead of 'Walking auto'.
As a first step it is available to the Beta group  - anyone can join, just go into 'Feed' and select 'Join Beta program'
Please let me know how it works!

Best regards
/Richard

**Comment by naoliv** [comment]
And where do I configure it? (ie, how do I set the distance between each each picture)
With version 2.29 I only see "sequence frequency" (in seconds) inside settings.

**Comment by rsahlin** [comment]
Hi @naoliv 

As a first test the distance is not configurable, we have set it to 5 meters which is the optimal distance for the backend.
This can be added later if there is demand for it :-)

Best regards
/Richard

**Comment by naoliv** [comment]
But how exactly it's working now?
It takes a picture whatever "distance" or "frequency" is reached first?

**Comment by rsahlin** [comment]
No, in this particular mode 'Distance, auto shot' the only parameter is distance from previous (known) capture location.

/Richard

**Comment by richlv** [comment]
one risk would be jumpy coords while, for example, standing at a traffic light in a city. we'd get a bunch of identical images. not critical, but maybe in the future scene change detection will appear :)

**Comment by rsahlin** [comment]
Yes, this is exactly what I would like to test.

From my testing, jumpy GPS coordinates have not been a problem while standing still.
Please test and report any cases of images in same position.

Thanks!

**Comment by PolyglotOpenstreetmap** [comment]
Personally I don't like this mode. I switched it off immediately as it was only making pictures every 20-30s. I got a fast phone capable of making high res pictures and storing about 1/s.
I'm mostly mapping by bicycle and on foot. I like the fact it's making pictures automatically every 1.3s. So I can point it to the relevant things to map afterwards.

**Comment by rsahlin** [comment]
Hi @PolyglotOpenstreetmap and thanks for commenting!

Would it help if we provided a setting where you could adjust the distance between pictures taken?
We are also thinking of adding a feature where a photo will be captured if compass angle changes, ie you turn, more than a specific amount.

Please help us improve this mode so you feel comfortable with it :-)

Best regards
/Richard

**Comment by pbb72** [comment]
I think I have the same issue as @PolyglotOpenstreetmap. Sometimes you just want to know that the app is going to make a photo, even if there is no movement or change.

Take the example of approaching a busy intersection. Lots of cars from crossing roads are blocking a clear view. But after a few seconds, after their light has turned red, I have a nice clear overview. I did not move in any way, but I want a new photo taken.

This could alternatively be solved with a manual action to take an additional photo, but that requires interaction with the app, which is not always possible. (When my traffic light is about to turn green, I don't want to be reaching over to the app to take a photo of the cleared crossing.)

Timed photography with no form of intelligence at all, is sometimes the best solution.

**Comment by richlv** [comment]
crossings and similar cases would be best controlled with voice control. shout "TAKE PHOTO" and it happens :)

**Comment by peterneubauer** [comment]
So, if there was a possibility to take manual photos between distance-triggered shots (either by pressing in the viewfinder, or a button or a voice command) that would work even for in-between cases?

**Comment by richlv** [comment]
button for walking, voice for driving - i'd like that.
note that @PolyglotOpenstreetmap getting a pic every 20-30 sec is likely a different issue with the new mode.

**Comment by kaitu** [comment]
@peterneubauer 
 I like this manual additional mode. Please consider that sometimes timing is critical, especially while driving and fast approaching a target. I'd like to be able to set this manual (button/voice) command to a burst mode which takes a bunch of pictures as fast as possible for a few seconds.

@rsahlin 
I like the compass change triggered mode idea. If the compass reading proved to be slow in fast turns, it might be good to trigger a burst of pictures after the first detected change of direction, instead of waiting for the next compass reading, and stop it only when you have confirmation that direction is steady again. Also, when activated, it might be necessary to adjust the "pause on shake" detection not to let the centrifugal forces trigger a pause in shooting.

**Comment by naoliv** [comment]
Is it possible to have a "mixed" mode using both methods? (frequency and distance)

For example, if I am driving at 110 km/h (~30 m/s) I would like to take one picture at each second and not 6 pictures in a second (if one is taken at each 5 meters).

If the traffic is so slow that I am driving slower than 18 km/h (5 m/s) then I would like to take a picture at each 5 meters.

**Comment by pbb72** [comment]
It's all ok with me, as long as simple timed photography stays an option. :-)

**Comment by rsahlin** [comment]
Hi @pbb72 

Could you please explain what it is you require from a simple timed photography mode?

Best regards
/Richard

**Comment by rsahlin** [comment]
Hi @PolyglotOpenstreetmap 

Yes, I think @richlv is correct - if your phone is only capturing every 20-30 seconds it is likely an error somewhere.
Could you please consider testing again and note the behavior - please not that as usual the device needs a GPS fix in order to be able to capture.

Thanks
Best regards
/Richard

**Comment by rsahlin** [comment]
I think I am starting to understand (some of) the requirements :-)

* As an crowd-capturer I want to to manually capture one or more pictures, whilst in the automatic mode, so that interesting areas are not missed.
* As a crowd-capturer I want to be able to set the max capture rate so that my phone does not take too many pictures as my speed increases.

Best regards
/Richard

**Comment by PolyglotOpenstreetmap** [comment]
Hi Richard,

You are probably right. The Honor6 phones I got with good specifications, especially for Mapillary, have lousy GPS, so I have to switch off GPS detection, otherwise it would never shoot a picture. If I could set it  to 25m instead of 15m, I could switch it back on. When I look at my sequences afterwards, the accuracy is just fine.

Anyway, what we need for a time based shooting at the max rate the hardware allows, a bit over 1s, is a convenient way to pause. What I usually do, is to rotate the phone 90 degrees. This worked just fine until recently. I should test again. Lately, I just keep shooting. When I go more slowly I move the phone so more of the surroundings is caught too.

If I would mount the phones on a rig, where rotating to pause isn't possible and pausing more than 1 phone by touching the screen becomes impractical, it would be nice to have another solution master/slave or something of the kind, but I realise this is hard to accomplish and it would consume more battery power, as this would probably require bluetooth to couple the phones in the rig.

Jo

**Comment by HolgerJeromin** [comment]
Connecting a bluetooth gps device to get a proper fix could improve the situation from the other side :-)
I am very happy with my Wintec WBT-202, but this is discontinued.

**Comment by pbb72** [comment]
@rsahlin, my requirements for a simple ("dumb") timed photography mode are simply what it is doing now, set a frequency and the camera takes a photo at the given frequency.

As to _why_:

- Since the app **still** doesn't allow to turn the screen off to save battery power, I have to use it with the backlight set to a minimum. This means I often cannot see the screen because of bright sunlight, and thus cannot interact with the screen.
- I don't like to attract attention, rather not even show that I am taking photos. So lifting up my phone to make photos manually is not preferred, and voice control is definitely out of the question when there's people around me.

(As a side note, the Mapillary app is mixing the terms "frequency" and "delay" (interval). These two are the inverse of eachother, and should not be mixed in the same setting. A frequency of "20/10 sec" means 20 photos per 10 seconds or 2 per second. A delay/interval of "20/10 sec" means 2 seconds between each photo. Quite different, and it took me a long time to figure out why the app was not taking photos at the frequency I wanted.)

**Comment by pbb72** [comment]
Is the feature of taking a photo every x meter also available in combination with "Skip location check"? I often have to enable this, because of bad GPS reception in urban environments.

**Comment by kaitu** [comment]
Maybe the "Skip location check" could make the app default to a normal timed shooting while the GPS reception is bad?

**Comment by rsahlin** [comment]
Hi @PolyglotOpenstreetmap 

If you turn off location check for a sequence, you will need to manually set the location.
- How do you handle that when you turn off location check?

From a backend perspective we want to capture a photo when the location is known.
In the future I will separate photo capture from GPS tracking, making it possible to interpolate the position of a photo at time of upload.

Using the timebased mode with location check turned off and fastest capture rate may likely result in photos in identical, or near identical location.

I would prefer to get the distance mode working properly, possibly it could help with a distance limit that can be controlled?

Best regards
/Richard

**Comment by rsahlin** [comment]
@pbb72 

Could you please explain why a distance based capture will not meet you requirements?

The goal is that you should be able to just pickup the phone and walk/bike and everything shall be automatic.
It would be great if you could explain why it is not working right now, ie from a capture perspective - your other comments will be looked into in the future :-)

Regarding naming - I agree and it is something that I will start looking into.

Best regards
/Richard

**Comment by pbb72** [comment]
I think distance-based capture is very good, but it won't cover all situations.

- Sometimes I wait at one point until the crowds/cars/etc clear up.
- Sometimes I want to capture special buildings in lots of detail, and especially when I am not able to make some distance between me and the building, then I capture with far smaller distances, like 2m or even 1m. Example: http://www.mapillary.com/map/s/NMa8CvCMdHTSILYn9P2Iwg
- I do have my doubts if GPS precision is high enough at walking speeds. I know at speeds over like 10km/h the precision greatly increases, but in my experience at walking speed (especially in urban environments) the measure relative movement is not trustworthy.
- And why should such a basic and simple feature be removed?

**Comment by pbb72** [comment]
Becoming off-topic here, but regarding your comment on interpolating positions using a GPS track, you actually don't need a GPS track to interpolate. If you have photos in a sequence without good GPS positions, you can interpolate using the other photos in the sequence.

**Comment by richlv** [comment]
@pbb72, things like buildings, panoramas, intersections should be covered by the manual mode much better, i believe. if you have to wait for an intersection to clear, what good are identical pictures, just some of them full of cars ?

**Comment by rsahlin** [comment]
Hi @pbb72 

The distance tracker will not trigger a new capture if the GPS signal is bad, regardless of the 'Skip location check' flag.

One solution could be to increase the accuracy allowed before the app decides it has 'bad' location, maybe increasing it to 25-30 meters and see if the reported position is still usefull.

- Do you think this adjustement would help?

You can verify this by enabling 'Settings' -  'Show detailed stats - the GPS accuracy will de displayed last on the second row. 

Best regards
/Richard

**Comment by pbb72** [comment]
@richlv I always go through my photos to delete the worst ones before uploading ;-)

If timed capture stays available in manual mode, then I am happy!

@rsahlin I am often in locations with bad GPS reception (though I don't know if the error is bigger than 25m), so that would mean I can't use distance-based capture in those situations?

**Comment by PolyglotOpenstreetmap** [comment]
It would definitely help me if I could set the accuracy to 25-30m. At least I can switch 'Skip location check' flag back off then.

I use tilting as a way to pause capture, maybe it would also help in distance based mode.

Switching between capture modes is not practical. The phone should ideally figure out a panorama is captured when the compass heading keeps increasing/decreasing. The mode I had settled on was time based 11/10 when cycling, 14/10 when walking. I had hoped that shooting that many pictures would actually be helpful for the backend. I know it's helpful for me, when trying to use the photos for improving OSM. Not if the same scene is captured over and over again, but with small variations and also given that not each picture is of good quality.

I try to review the pictures before uploading, but it doesn't always happen and in fact, I stopped making more for a few months, as I couldn't get them reviewed/uploaded at some point.

Jo

**Comment by rsahlin** [comment]
Hi and thanks for all comments :-)

Ok, where to begin - a number of questions again - great!

@pbb72 Thanks for explaining the usecase to me - now I see the problem clearer!
- To make the answer short, yes of course we can keep timebased capture.

The goal is a capturemode that is easy to use and covers most usecases - we want the app to be easy to use for novices - with clear and functional modes.

Maybe the way forward is two different modes - distance or time-based capture?
- For distance based capture there is a way to select the distance in meters.
- For timebased capture there is a frequency (captures/second)
- For both modes it is possible to capture extra photos by pressing on screen or hardware button.
(This could possibly be customized to burst rate capture for X number of seconds)
-The threshold for 'bad' GPS signal is increased to 30 meters, with the intent to remove the option 'skip location check' in the future.

Best regards
/Richard

**Comment by pbb72** [comment]
Sounds great. Maybe even go so far that bike/car modes are locked to distance-based capture, while in manual mode you can select which one you want.

**Comment by PolyglotOpenstreetmap** [comment]
Hi Richard,

I'm not sure it's necessary to set the max to 30m all the time. Maybe have it as a configuration option, set to 15m default, but allow it to be increased to 30m.

Jo
