### ISSUE TITLE
cannot find page with discovered trafic sign

### ISSUE THREAD

**Issue by beer118** [mapillary/mapillary_issues#2471]
### Basic information
* Platform: `Web`
* Version: `55.` 
* System/Browser: `Chrome`

### Expected behavior
I could at some point find a sub page under my user where I got a overview over the trafic sign I have found. I can no longer find that overview

### Actual behavior
Easy to find a page where I get a list over trafic sign that I have discovered while taking pictures

-

**Comment by katrinhumal** [comment]
Hi @beer118 - currently we don't have this kind of page available, so that is why you can't find it. However, if you use the filters at the top of the web app, you can switch on traffic signs and filter for your own username. Then you'll see a combination of traffic sign detections and your captures. If you open a photo while the traffic signs filter is on, you can even see the signs in the photo.

This will not fully work everywhere yet, since we are still reprocessing the whole world for traffic signs. We are doing this because we had a big update recently where we added more than 500 traffic signs from all over the world. Anyway, in time you will be able to see detections in a lot of places (check the list of signs and countries here: https://www.mapillary.com/developer/api-documentation/#traffic-signs).
