### ISSUE TITLE
NoScript prevents this from working

### ISSUE THREAD

**Issue by rugk** [mapillary/mapillary_issues#2472]
### Basic information
* Platform: `Web`
* System/Browser: Firefox 51.0.1

### Steps to reproduce behavior

 1. Install NoScript
 2. Try to use Mapillary to view images…

### Expected behavior

Work as usual.

### Actual behavior

It shows me "Your browser does not support WebGL or it’s not enabled."…

**Comment by echeloni2p** [comment]
Moin

thats expected, all the scripts on the page uses lots of scripts.
Adopt NoScript to allow scripts on mapillary and you see the images again.

echelon

**Comment by rugk** [comment]
Oh I forgot to mention. Of course scripts are allowed. Using `https://` on the whitelist.

**Comment by knikel** [comment]
@rugk: Which system are you using? Is it possible that you do not have correct graphic card drivers installed?

**Comment by rugk** [comment]
No, it works when I uninstall/disable NoScript, so graphic drivers work.

Debian 8, x64 here

**Comment by knikel** [comment]
Alright, I had a closer look at this issue today and it if you want mapillary.com to work with NoScript you need to whitelist all the APIs, CDNs we use, external resource domains (e.g. mapbox.com) and so on, but you probably know that.

The reason why you might have seen the No WebGL support is _probably_ because [`mapillary-js`](https://github.com/mapillary/mapillary-js) couldn't fetch/render meshes from one of the forbidden domains or lack of some external library or errors from (e.g. [`mapbox-gl-js`](https://github.com/mapbox/mapbox-gl-js)) fail the WebGL support checks. Try whitelisting `mapbox.com` domains. That's the best answer I can give you, sorry.

I'm closing this issue since I won't be investigating this any further. While testing I managed to run mapillary.com on FF52.0 + NoScript; however, we won't be officially supporting this extension.
