### ISSUE TITLE
API v3: no more time filters parameters ?

### ISSUE THREAD

**Issue by PanierAvide** [mapillary/mapillary_issues#2496]
### Basic information
* Platform: `Web`
* Version: `API v3` 
* System/Browser: `Firefox 50`

### Steps to reproduce behavior

 1. Ask for `https://a.mapillary.com/v3/images?client_id=<CLIENT_ID>&bbox=-1.721,48.12421,-1.70733,48.12961&start_time=1467377425000&end_time=1475326225000`

### Expected behavior

Pictures are returned within the given time interval, as API v2 allowed to do.

### Actual behavior

Pictures are returned even if outside the time interval.

### Additional information

I know that this parameter is not documented in the new API version. However, this was a useful parameter for retrieving specific pictures (speaking as [Pic4Carto](https://framagit.org/PanierAvide/Pic4Carto) developer). Was these parameters only undocumented or the feature was completely dropped ?

**Comment by ptpt** [comment]
This is indeed a useful feature! We will add in API v3 in one or two weeks. Thanks for the input.

**Comment by PanierAvide** [comment]
Great to hear, thanks for the fast answer :-)

**Comment by ptpt** [comment]
@PanierAvide It is added to the image endpoint. See https://www.mapillary.com/developer/api-documentation/#search-images

Note that all dates in Mapillary API v3 must be ISO date string https://en.wikipedia.org/wiki/ISO_8601, instead of epoch ms. So a valid `start_time` or `end_time` should be `start_time=2017-12-22`.

Let me know if you have any further issue.

Tao

**Comment by PanierAvide** [comment]
Works great, thank you 👍
