### ISSUE TITLE
Not possible to make indoor photos anymore

### ISSUE THREAD

**Issue by Jurkis** [mapillary/mapillary_issues#2505]
### Basic information
* Platform:  `Android` 
* Version: `3.38` 
* System/Browser: `Honor 8, Android 7`

### Steps to reproduce behavior

 1. Enable "Skip location check" in Developer section
 2. Make photos **indoor**.

### Expected behavior

Photos are made with no problems

### Actual behavior

Photos are not made, "bad fix..." message is shown

### Additional information

Not sure but i think this problem occurred first in 3.37 or even earlier version.

**Comment by Jurkis** [comment]
OK, it works every 15th time.

**Comment by kaitu** [comment]
It's not only indoor, also in canyons or any place where reception is problematic.
I'd like a possibility to get rid of the fix quality notification altogether. Even if you know that reception is bad, there's most often nothing you can do to improve it, nor you have time to wait for a fading reception to improve. Just allow to take pictures without quality concerns, and tag the precision. You can still decide to discard it afterwards, if it serves no purpose for your application.

**Comment by katrinhumal** [comment]
@kaitu, thanks for the feedback! We are not planning to remove the notification. It is indeed a matter of preference whether to be seeing it or not. But the main purpose of the capture function of the app is to take geotagged photos, so when the app fails to do that due to a bad GPS fix then the user should know about it.

@Jurkis thanks for reporting the problem. We'll look into why the "Skip location check" fails to skip the location check.

**Comment by jfburke3** [comment]
Just my $.02 worth:  I absolutely want the GPS quality notification.  Among other things, it helps me determine if the reason it isn't taking pictures is that, or one of the issues I've logged :-)

**Comment by peterneubauer** [comment]
So, for the users wanting to skip location, the check is moved to settings->developer. It works again, but be aware that totally missing location in the GPX track (no fix at all) will now result in not uploading these images and make the images sit on the phone for you to delete.
