### ISSUE TITLE
lost connection w/ LG360 (capture continued? GPS didn't?)

### ISSUE THREAD

**Issue by danbjoseph** [mapillary/mapillary_issues#2509]
- iPhone 5s (A1533) running version 10.2.1(14D27)
- Mapillary v4.6.10(216)
- LG360 camera

In sequence `GVZCQd5oltViYcNKWH18HA` starting with photo `E67QPuZANTvGSuCOBaafPQ` the GPS seems to quit reading correctly. At photo `U5-NMRHi_-h2I7Mvv0liLw` you can see me look down and check my phone. This is when I noticed a "lost connection" notification. I lower the camera at `q0_IrEQt-1zRbFK12i32Mg`and then do something to terminate the sequence some number of photos later. I tried to reconnect after noticing the "lost connection" notification but every time the app would try and refresh the preview image it would close out. 

<img width="269" alt="screen shot 2017-04-01 at 5 55 28 pm" src="https://cloud.githubusercontent.com/assets/4806884/24582773/353bf580-1705-11e7-9f9b-1dc13d4e836c.png">
<img width="390" alt="screen shot 2017-04-01 at 5 55 36 pm" src="https://cloud.githubusercontent.com/assets/4806884/24582774/363ea3b0-1705-11e7-8870-066913883fe6.png">

**Comment by millenbop** [comment]
Thanks for reporting. It seems to happen to some users with the LG360. Both mine work good though but I'm expecting to get my hinds on a "faulty" one soon.

We are currently rewriting how external cameras work and one thing that I will change is so that the phone keeps recording the GPS track even if the camera is disconnected for some reason. I'll also investigate if the disconnect detection can be improved somehow.

**Comment by millenbop** [comment]
External cameras are now allowed to “fail” 3 times to send status update before being considered disconnected. Fix will be out in the next release.
