### ISSUE TITLE
webupload failes with mapillary app images

### ISSUE THREAD

**Issue by HolgerJeromin** [mapillary/mapillary_issues#251]
i just moved a bunch of jpgs from my phone (taken with the app) and tried to upload them via lastest desktop chrome and opera on linux. All failed with:

```
Filename: 2014_08_02_12_42_56_356.jpg 
Could not find valid EXIF Data 
...
```

I did not changed them on the desktop, just deleted a few files.

**Comment by polarbearing** [comment]
Apparently has not been changed yet, although the similar issue #218 was closed. 

Workaround is to load the files back onto the mobile and let the app do the upload.

**Comment by gyllen** [comment]
We will not support mapillary image upload from web. It might be supported by a native desktop app though. Closing.

**Comment by HolgerJeromin** [comment]
Ok, your design decision. But the error message should explain that better.

**Comment by stephan75** [comment]
It took me long time to get this hint that images cannot be uploaded via the web uploader at http://www.mapillary.com/map/upload/im even when having them copied manually from my android device (mapillary image folder) to my desktop PC.

Can you add a hint on the web uploader screen like that says explicitly:
"You cannot process images via this service taken with mapillary app, even when copied to a PC" or similar?

Because the sentence so far "Upload photos that have been taken outside of the Mapillary App." is to weak in meaning, I think.

**Comment by peterneubauer** [comment]
Yeah,
actually this is something we should fix @gyllen. Checking for dupes is a related issue that we need to solve independently of this issue in the backend.

**Comment by gyllen** [comment]
This is now fixed, closing
