### ISSUE TITLE
Android 6.0/7.1.1 app cannot choose sdcard

### ISSUE THREAD

**Issue by echeloni2p** [mapillary/mapillary_issues#2515]
### Basic information
* Platform:  `Android`
* Version: `3.44` 
* System/Browser: `...`

### Steps to reproduce behavior

 1. settings
 2. choose storage
 3. choose please select storage
 4. click arrow above and get stopped at /storage/emulated/0

No way to choose any SDcard

### Expected behavior
Choose SDCard to save picture upon, another directory 
...

### Actual behavior
Locked into mobiel phone own in-built storage

**Comment by drkludge** [comment]
This is a security issue for Android 6.0.1 and above. Where you could change this in Mapillary settings before, you have to change an Android system setting to move photo capture to a sd card. For the life of me I cannot find the setting but experienced the same issue.

**Comment by echeloni2p** [comment]
Hi!

I do not know much about the internals, but is it possible to create a new dir on sdcard and give mapillary rights to it?

**Comment by drkludge** [comment]
@echeloni2p that's what I used to do on the sd card before 6.0.1. Once the Android configuration is made, the Mapillary sd card location starts with Android/data/app.maillary/files/mapillary... The long story short is that you do not have a choice on the directory path.

**Comment by jfburke3** [comment]
That doesn't make sense.  A while back, when I first installed Mapillary (in the 2.x days) on my Galaxy S7 running Android 6.0.1, I was able to specify the SD card for image storage in Mapillary.  I'm still running it on that phone, with Android 6.0.1, and it is still storing images on the SD card.

**Comment by peterneubauer** [comment]
The thing is that we probably need to find a way to have multiple roots to start from, the different SD cards, since it seems hard to go further up than the current sd card in order to choose the other. See something like http://stackoverflow.com/questions/38143961/sd-card-path-of-android-phone

**Comment by peterneubauer** [comment]
@jfburke3 it might be that different models are different hard in enforcing the process permissions of the spec, but it seems there are only certain dirs and listings an app process is allowed to see in newer Android versions.

**Comment by jfburke3** [comment]
I worded my comment poorly.  I should have been more clear that I didn't think it was an inherent Android 6.0.x issue.  @peterneubauer, I know you're correct, because of all of the info out about subtle changes introduced by Samsung on my model phone.

**Comment by richlv** [comment]
a samsung phone with android could have taken many thousands of beautiful, sunny photos recently if it was possible to choose the sd card :)

@drkludge, you said "you have to change an Android system setting to move photo capture to a sd card" - the only thing i was able to find was moving the app to the sd card, but nothing seems to affect where the photos go. in the file manager, one can choose "internal" or "sd card", but nothing like that in the mapillary app.

**Comment by echeloni2p** [comment]
I can move the pictures from internal to sd card with "total commander", e.g. - but that takes a long time. I am not in the mood to take 2h pictures while riding the bike and at a break move all pictures to SD card while mobile needs power to refill battery ;-)
Thats why I try to get as big internal storage as possible now. Would like to have the Asus AR with 256GB ;-) but not yet available.

**Comment by drkludge** [comment]
@richlv I thought that I was sunk with my new phone.  I actually had to take the phone back to the store so that they could assist me.  Some of my long runs in Arizona would overrun the internal storage.

The reason why I could not find the setting is that I had to use "force stop" on Mapillary before I could use the change storage location button.  Like I said the default location is `SD card/Android/data/app.maillary/files/mapillary... `

I have also tried to changing the directory once I performed the move external card procedure.  I was not allowed to do so.

[It almost sounds like it is a new permissions issue](http://www.androidcentral.com/kitkat-sdcard-changes?pg=2#content)
[The hint of the procedure is here](http://forums.androidcentral.com/samsung-galaxy-s5/453106-why-can-t-i-move-any-files-onto-sd-card.html)
"Sure you can..
If you want to move apps to the SD card go to settings-application manager. Find the app you want to move (not all apps are movable) tap force stop then tap move to SD card.

**Comment by severinmenard** [comment]
I do not have the possibility to move the app to the SD Card from settings-application manager (see screenshots below)

![screenshot_20180110-091353](https://user-images.githubusercontent.com/1291055/34772529-fa851bd0-f5e6-11e7-8124-eec9d0e5a2f9.png)
![screenshot_20180110-091406](https://user-images.githubusercontent.com/1291055/34772528-fa5e6b16-f5e6-11e7-9313-94ffa2d27c15.png)

**Comment by jfburke3** [comment]
@severinmenard There are 2 different issues that are being mixed up on this thread. 

1) Ability to move the *app* to external storage.  This is allowed or prohibited by your phone manufacturer. 

2) ability of an app like Mapillary to save data on external storage, while the app remains on internal storage. 

If I'm following this thread correctly, you're posting about #1, but this thread is about #2.  #1 isn't something the Mapillary developers can do anything about.

**Comment by severinmenard** [comment]
@jfburke3 actually I had reported #2 on another thread (now deleted by the Mapillary support because it was not at the right place) and my interest is related to it. Moving the app to the SDcard is a potential fix to #2 provided by @drkludge just above my reply. I should have added that the fix does not work for all the smartphones because of the manufacturer limitations, as you wrote.

**Comment by peterneubauer** [comment]
When it comes to moving the app to the SDCard, that should be possible, but when you do this, the app doesn't have access anymore to the system account manager and you might be forced to log in every time you start the app.

As for choosing the SDCard for images, @ovivoda is working on that right now ...

**Comment by ovivoda** [comment]
Please try this APK: http://android-releases.mapillary.io/Mapillary_Android_v3.118-SNAPSHOT1.apk1

and let me know if it works for you. For KitKat and up the application will now use SDCard private folder to save the images if you enable the setting to use the SDCard from Settings->Storage section.

Warning: If you are using this setting and you uninstall the application before uploading the images, the images will be lost.

**Comment by ovivoda** [comment]
This is fixed for most of the devices out there.
