### ISSUE TITLE
Join Sequences

### ISSUE THREAD

**Issue by FoliniC** [mapillary/mapillary_issues#2520]
### Basic information
* Platform: all
* Version: all
* System/Browser: all

### Steps to reproduce behavior

 1. upload more than one batch of images
 2. start the slideshow oft the first sequence
 3.the slideshow stops when the sequence ends (on mapillary the sequence are connected)

### Expected behavior
After uploading images in more than one sequence, it would be better if the sequences could be joined in only one (or create a 'parent' sequence)

### Actual behavior
Different uploads creates different sequences

### Additional information

...

**Comment by katrinhumal** [comment]
@FoliniC Thanks for your suggestion! You are not the first one to mention this, but right now do not intend to implement it. If the end of one sequence and the beginning of the next one are close enough to each other, you will be able to navigate between them using the spatial arrows (read more [here](https://help.mapillary.com/hc/en-us/articles/115001761965-Spatial-arrows)). However, I am taking note of your request so that we can refer to it in the future if we are reconsidering this function.

**Comment by FoliniC** [comment]
Hi,
I noticed the spatial arrows, but clicking on it changes only the top
triangle and brackets, so I didn't realized this behaviour.
Maybe you Could consider changing the image to the next one, when the
spatial arrow is clicked.
Thanks
Carlo


Il 10 apr 2017 1:44 PM, "katrinhumal" <notifications@github.com> ha scritto:

@FoliniC <https://github.com/FoliniC> Thanks for your suggestion! You are
not the first one to mention this, but right now do not intend to implement
it. If the end of one sequence and the beginning of the next one are close
enough to each other, you will be able to navigate between them using the
spatial arrows (read more here
<https://help.mapillary.com/hc/en-us/articles/115001761965-Spatial-arrows>).
However, I am taking note of your request so that we can refer to it in the
future if we are reconsidering this function.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/mapillary/mapillary_issues/issues/2520#issuecomment-292925837>,
or mute the thread

**Comment by katrinhumal** [comment]
Hi Carlo,
The spatial arrows let you literally move around in space. In some cases, they are going to take you along the sequence, but that is because the photos in a sequence are usually close to each other in space. If there are no other photos/sequences around, then you will only have spatial arrows that take you along the same sequence. As soon as some other person has captured near where you went, you will get a spatial arrow that lets you look to that direction, too.
/Katrin

**Comment by FoliniC** [comment]
Ciao Katrin,
I realized how spatial arrows works.
My suggestion was to display the near est picture when clicking on it.
If you take a look at my sequences you will see that when the first one
ends a spatial arrow is displayed. There's a picture very near, but when I
click on the arrow only the topmost links changes (triangle and "less than"
).
My suggestion is to display the nearest picture.

Ciao Carlo


Il 11 apr 2017 11:04 AM, "katrinhumal" <notifications@github.com> ha
scritto:

Hi Carlo,
The spatial arrows let you literally move around in space. In some cases,
they are going to take you along the sequence, but that is because the
photos in a sequence are usually close to each other in space. If there are
no other photos/sequences around, then you will only have spatial arrows
that take you along the same sequence. As soon as some other person has
captured near where you went, you will get a spatial arrow that lets you
look to that direction, too.
/Katrin

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/mapillary/mapillary_issues/issues/2520#issuecomment-293196860>,
or mute the thread
