### ISSUE TITLE
occasional rotated picture with Android version 3.45

### ISSUE THREAD

**Issue by voschix** [mapillary/mapillary_issues#2526]
### Basic information
* Platform: `Android` 
* Version: `3.45` 
* phone: 'Sony Z5compact'

### Description
Occasionally individual photos are rotated by 180 degrees.  Frequency below 1%

### Steps to reproduce behaviour
Not possibly to reproduce reliably. 

### Notes
The rotations all happened with the bicycle mount. I have no comparison with car mount with the same App version.
I had reported the problem in the past (with essentially the same hardware set-up, but it had disappeared and I produced some 200,000 photos with the same hardware setup (phone, bicycle and mount) without problems with the App version of August/September 2016.

I realise that this is potentially a multi-variable problem as I also updated the Android system every time an upgrade was available.

I think that the correct remedy is not to change the App, but to provide the user with the option to rotate single pictures in the web interface.

...

### Additional information

...

**Comment by peterneubauer** [comment]
Yes,
I think this might actually be the phone reporting faulty rotation data. Before every capture the rotation of the picture is adjusted, since people have reported that this is the more dynamic and desirable solution insead of setting rotation at the beginning of a sequence.

If the phone occasionally is reporting wrong, there is not much we can do but to provide for instance rotation adjustment on the phone in the review, and in the web edit (it's already working in the backend).

Closing this for now as there is not much we can do. Maybe you can open an issue around the rotatoin UX in the app/web instead?

**Comment by peterneubauer** [comment]
@voschix how is http://android-releases.mapillary.io/Mapillary_Android_3.47.apk working for you? Is that better?
