### ISSUE TITLE
Problems with Upload from Android App

### ISSUE THREAD

**Issue by voschix** [mapillary/mapillary_issues#2536]
### Basic information
* Platform:  `Android`
* Version: `3.48`
* System/Browser: `...`

### Steps to reproduce behavior
not reproducable

### Expected behavior

At the end of the automatic upload no picture folders or files should remain on the phone

### Actual behavior

Upload does not finish properly

### Additional information
On 17 April 2017 I produced 12 (or 13?) sequences. At the end I find one sequence left in the Upload window of the app. I click the green Uplaod button, confirm the UPLOAD, see briefly the Upload in Progress window signalling the upload of 70 photos very quickly. Finishes with "Upload finished", BUT the sequence does not appear in my upload list on the site (giving it enough time to be processed). Inspecting the contents of the microSD card I find all the pictures still on the phone at this location:

This PC\Xperia Z5 Compact\SD Card\Android\data\app.mapillary\files\mapillary\CAMERA2_0\2017_04_17_11_27_42_701

This directory contains all the missing photos plus a GPX track with their positions.

I can obviously manually upload them, but this is not how it should work.

In addition, but most likely unrelated, I found two empty photo directories on the card that are two weeks old whose pictures have been uploaded successfully:
![image](https://cloud.githubusercontent.com/assets/11076112/25142433/20464b5c-2467-11e7-8fd8-467ef359ba6b.png)

...

**Comment by jfburke3** [comment]
There are cases already opened about the upload problems this #2530 #2533

**Comment by peterneubauer** [comment]
@voschix can you please send the log after the processing? It seems some images were not passing processing, I need to check what the problem was.

**Comment by voschix** [comment]
@Peter:
The file I sent to Katrin is the log after the uploads. One of them did not
work. The 70 photos are still on the phone. In the meantime I launched a
manual upload of these files, but they are not yet visible on the site.

**Comment by voschix** [comment]
Update:
There is an additional problem:
all photos in the the "strange" directory 
![image](https://cloud.githubusercontent.com/assets/11076112/25172843/7f245052-24f2-11e7-9031-d791988d837e.png)
are geotagged with the location of the first photo. 
You can see the result in the manually uploaded sequence G_-YzztDDx_t4Kitt0kzVQ
Could be something similar to 
https://github.com/mapillary/mapillary_issues/issues/2537

**Comment by peterneubauer** [comment]
For the hanging empty sequences, you can delete them @voschix as they are from older versions of the app.

**Comment by peterneubauer** [comment]
@katrinhumal can you please get me @voschix logfile for this issue?

**Comment by voschix** [comment]
This all a bit difficult to reproduce, as apparently I have been using different versions in quick succession. I am now on 3,50.
Regarding the manually uploaded sequence G_-YzztDDx_t4Kitt0kzVQ where all photos have the same position (of the first photo in the sequence), I noticed that the data in the phone are strange: the directory
![image](https://cloud.githubusercontent.com/assets/11076112/25267214/30b88a2c-2674-11e7-8036-bce64cea0827.png)
contains a sequence of JPG files and a GPX file.  That GPX file corresponds to the preceding sequence (in time), i.e. 42y-f1hz2DhaEZdclasTiw and not to the JPG photos in the directory. Photos and GPX seem to be out of phase. The photos of this preceding sequence were uploaded correctly directly with the App from the phone.

**Comment by peterneubauer** [comment]
Can you maybe get me that sequence folder? If there is a GPX file in it, it probably comes from the first version of the new upload, and if it's not super important, delete it. Otherwise, I can probably check the time-offset and synch/upload/fix it.

**Comment by katrinhumal** [comment]
Sorry for my slowness here. @peterneubauer I sent you a sharing link via email, the logfile was too big to upload here.

**Comment by peterneubauer** [comment]
For the 3.54 version, empty folders now will be deleted and the directories should look more clean. Please et me know if you find problems.

**Comment by voschix** [comment]
with 3.54 upload is not automatic. When I have a number of sequences (mainly produced by the App stopping taking pictures for reasons still not understood - but this is another problem) on my phone, I start the upload with the upload button. The app goes through the procedure of processing all sequences and then starts uploading. When I come back to the phone, often it has stopped uploading. I have to restart it manually a number of times to get all sequences (or partial sequences) loaded. The screen messages are confusing and it's difficult to figure out when it has finished all bits of all sequences.

**Comment by peterneubauer** [comment]
Volker,
we will rework the upload procedure, I have some ideas on how to speed it
up, and maybe take one sequence at a time in order to make it more obvious
on what is loaded right now. Also, the backoff- and retry routines need to
be more transparent. Thanks for the feedback! At least it seems the images
are uploading ok, which means processing is correct.

**Comment by drkludge** [comment]
@peterneubauer is there any chance that you can go back to the 3.43 uploader with other improvements in the current 3.55 release verses rewriting what is there now.  It is becoming clear that I traded the stability of uploads for capture over rough ground as described in https://github.com/mapillary/mapillary_issues/issues/2552.  I had a great bicycle ride the other day of around 7800 images captured.  However, I've been nursing the upload of that information for the last 24 hours.  I cannot upload what I have collected.  It really is that bad.  I recognize the same problems that @voschix describes.  I installed 3.55 hoping for the best but no joy.  The [play store change logs are always too brief] in order to understand what has changed.(https://play.google.com/store/apps/details?id=app.mapillary&hl=en)

Here are some things that I have tried or observed:
- I extended the screen timeout thinking that interfered with the upload.
- As an example, I receive a message in the Android central notifications that the upload was complete.  I switch to the app and see Upload in progress and the screen saying that 430/556 of images are done.
- I have to hit back arrow or cancel and then try to upload.  Now is says that the app will upload 592 photos in this sequence.
- Where I used to be able to press the upload for all sequences and go to bed, I find that the application has stopped, or it has cherry picked out some of each sequence but left the lion's share of the photos.
- I  have found that it works best to exit the application then come back into the app.  This allows the app to "reset".  Otherwise, the application thinks that it is still uploading and you cannot start another upload when a partial upload completes.
- [I just when back to 4.44](http://android-releases.mapillary.io/index.html?sort=lastmod&sortdir=desc).  I could not find 4.43.  It is a shame that I did not backup where I was at with the partial uploads.  I lost all the partial uploads.  Hence, there will be some duplicate photos.  I'd rather go back to this release than to try with the current releases.  
- It would be great if you would help complete https://github.com/JOSM/Mapillary/issues/47 the JOSM upload.  I used to use the JOSM plugin for uploads because of the slowness of the Android upload.  Until this issue is addressed, then I do not have an alternative to the Android platform that I know of.  At this point I do not believe that the JOSM  plugin is aware of the separate meta data file.

I uploaded one of the 600 image directories that I could not upload contiguously with the 3.55 release. The 4.44 release was rock solid.  No issues in the upload.  Please put this ticket at your highest priority.

**Comment by voschix** [comment]
Just uploaded some 5000 photos in about 13 sequences, This time I exited the App every time it told me it had finished (and invited me to cancel). I had to relaunch the App five o six times. One thing which happened (and I had somehow noticed before): each time the number of uploaded photos decreases. The first upload was more than 1k photos, the last one was 11 photos. Every time the number of uploaded photos was smaller than the number in the "uploading xxx photos" messages, bar the last one,

**Comment by voschix** [comment]
3.56 snapshot seems to work. I just uploaded three sequences in one go.

**Comment by jaakkoh** [comment]
I've tried the new versions with little help in uploads. I just went back to 3.27 (on my old phone for uploads only) and that seems to upload without any problems.

Is there something that is not happening or information that gets lost when uploading with 3.27 vs. the 3.5*?

**Comment by jaakkoh** [comment]
@peterneubauer @voschix 
Uploads with 3.56-SNAPSHOT2 work for me too. (Currently running only on my Galaxy S5.)
Thanks!

**Comment by ovivoda** [comment]
Closing this. Please reopen it if you still have issues with upload.
