### ISSUE TITLE
Blur / Unblur .. more detailed mail/information

### ISSUE THREAD

**Issue by thoschu96** [mapillary/mapillary_issues#2548]
### Basic information
* Platform: `Web`

### Steps to reproduce behavior

 1. an other user signup an blur/unblur request of the own pictures.
 2. after approval a mail and Feed entry got updated

### Expected behavior

Detailed information if blur or unblur happend
and which Section / Area

### Actual behavior

Only BLUR get report, even if it's an unblur request
So an Adjustment would be nice to get an better Mail, 
if an BLUR or UNBLUR happend ..

Maybe an additional Option to Approve the Request
to Speedup the Blur/unBlur as you are the picturetaker ...

**Comment by katrinhumal** [comment]
Thanks for the input! The reason that we haven't invested time into giving detailed information about which blurs took place is that to date, we haven't yet come across a case where someone would have sabotaged anyone else's photos. When you get the notification about blurs, then the edits have already been approved by the Mapillary team (or a bot, if the requester has a tracklog of successful blur editing). When you look at the photos (due to cache it can take up to 24 hours until you see the actual edited photo), you should normally not see any more false blurs.

@thoschu96 Do you feel like someone has done bad blur edits to your photos? If yes, could you share a link to an example?

**Comment by thoschu96** [comment]
Hi.
No, was just saying/asking for improvements.
But you are working on, to send out Blur Mails if something got blurred and 
UnBlurred Mails if something got unblurred.
It's confusing, when u get an BLUR Mail and u don't know if Blur or UnBlur take aktion on your Pictures.

**Comment by katrinhumal** [comment]
@thoschu96 I understand. I will take this idea to the team for sure, but I can't promise that we will work on this anytime soon. While I understand that it would be much nicer to get a detailed report on what happened, it is at the same time not as critical as some of the other things that we need to work on in the near future. We'll do our best to move fast though, and perhaps you will see this enhancement at some point. Thanks for sharing your thoughts!
