### ISSUE TITLE
Automatic hide images in sensitive areas

### ISSUE THREAD

**Issue by mishari** [mapillary/mapillary_issues#2549]
Is it possible to automatically hide images taken in sensitive / military areas in Thailand? This will help prevent legal accidents as many of these allow public access and one can stumble into it unknowingly.

http://www.openstreetmap.org/search?query=bangkok#map=13/13.9031/100.6094 you
can see the restricted areas here with the red stripes.

**Comment by katrinhumal** [comment]
@mishari That is a very good question! Let me look into that and get back to you.

**Comment by GITNE** [comment]
@mishari Indeed, it would nice to have that feature. However, please note that this does not solve your problem because legally it is not Mapillary who may be committing an offense but you are if you take pictures in a restricted area (basically the same applies to private property and/or estate). It is always the perpetrator who is liable and will eventually be held accountable, hence you, not Mapillary. So, please be careful not to cross any local rules and regulations. Mapillary cannot solve this problem for you, nor protect you from getting into trouble.

**Comment by mprins** [comment]
Adding this kind of behaviour would enforce local (in this case Thai) law to the rest of the world where it does not apply.
This should be "fixed" (if at all) in the app(s), eg. by preventing taking photographs

**Comment by GITNE** [comment]
> This should be "fixed" (if at all) in the app(s), eg. by preventing taking photographs

@mprins And how this supposed to happen or how is this different from doing this sort of check on the server side? Guys, no technology exists or will ever exist which will prevent you from doing illegal or stupid stuff. And, if it did it would be a terrible type of big brother or overlord kind of thing. I do think that anybody would really want this to ever happen. This is equivalent to those people who are asking computer scientists to build computers which will process only *good* *data* but will not process *bad* *data*. Look into information theory: You cannot! Although perhaps well intended, yet unfortunately this clearly shows a vary naive or uninformed type of thinking about how information processing works.

The closest thing you could do today is to warn users when they have taken photos in a restricted area provided that the GPS location of the photo is known **and** you have a correct set of restricted areas to validate against. Technically, this is possible but for the Mapillary app not really feasible.

**Comment by mprins** [comment]
> And how this supposed to happen or how is this different from doing this sort of check on the server side?

how hard can it be to have a digital map of restricted areas inside an app and prevent the app from using the camera, it's basic geofencing functionality. (things like route finding are much harder yet we all have navigation on our device) 

the difference is obvious: prevent taking photographs versus (illegally) taking photographs and uploading those.

of course the key point here is that the map holds the truth, which it never does as it is always only a model of reality

**Comment by GITNE** [comment]
> of course the key point here is that the map holds the truth, which it never does as it is always only a model of reality

And that's exactly the problem. Somebody has to update and verify these areas, plus you have to have additional knowledge of the local ordinances and jurisdiction. What may be acceptable in one area may not be in another, even in the same country or type of restricted area. Who is going to keep track of this? This is a lot! There are currently about 183 (depending on how you count) countries on the globe. Hence, mapping 183 countries with fuzzy semantics is one thing, mapping **exact** legal semantics is a totally different story. You would need a battery of lawyers and tech people to implement this feature. Which by the way, would still need to be overridable because people and data may be wrong or change depending on time of year etc. Hence, you are at point zero back again where the user has to decide and observe local law.

But that's not all. You have to download and update this data in the app just like you have to do with maps in navigation apps. It is difficult to estimate any potential size of such data but I would not be surprised if it would reach gigabytes on the planet level. Yeah yeah, you can break it up into smaller chunks like countries etc. But, this shows how much work you would have to invest to make this feature work, and then you would still end up with potentially only mediocre quality.

It's simply currently not really feasible.

**Comment by mishari** [comment]
In which case, I would like to have Geofencing from Geojson feeds. One example is that country specific community can update json files on Github and Mapillary can use that to auto-hide images from contributors.

**Comment by Alessandro-Barbieri** [comment]
I'm against this, nothing should be done from mapillary

**Comment by mishari** [comment]
How about Geofencing where a geojson file URL can be given and images
hidden automatically. The community can maintain the files.

**Comment by Alessandro-Barbieri** [comment]
Just don't go there, mapillary is not a substitute for police or proper signaling. Why babysit users on where they are allowed to go?

**Comment by katrinhumal** [comment]
Closing this since we don't plan to implement. You're welcome to head over to our [forum](forum.mapillary.com) and open a thread there if you want to keep discussing around this.
