### ISSUE TITLE
iOS - picture direction indicator shows strange/false direction

### ISSUE THREAD

**Issue by ramapongithub** [mapillary/mapillary_issues#2584]
### Basic information
* Platform: iOS 10.1.1
* Version: Mapillary App 4.6.16

### Expected behavior

Picture direction indicator shows same direction as in the web broser

### Actual behavior

Sometimes the direction indicator shows strange directions.

### Additional information

Not always, but sometimes the direction indicator in the sequence view schows directions not matching the direction shown in the web app,
For instance this [image](https://www.mapillary.com/app/?lat=50.505955555555545&lng=10.444808333333299&z=17&menu=false&pKey=k82hlpALhAARnuFchMbZfg&focus=map&mapStyle=mapbox_satellite) in the web map shows an direction along the highway, wich is ok.
See also this [screenshot](https://www.pic-upload.de/view-33251987/direction.jpg.html).

The same image in the Mapillary map shows an direction directly in western direction, around 70° to the right. Shown in this [screenshot from iPhone](https://www.pic-upload.de/view-33251988/IMG_1337.png.html)

I could not find any system in this. Most images seem to be ok, but sometimes it does not fit.

**Comment by millenbop** [comment]
Hi, thanks for reporting!

I take it you mean this one:

<img width="159" alt="screen shot 2017-05-30 at 11 04 58" src="https://cloud.githubusercontent.com/assets/12835674/26576085/e4133122-4527-11e7-89d2-582f8c4a5405.png">

Everything displayed in the viewer is calculated using our technology called Structure from Motion (SfM). It has flaws but we are constantly improving it. You can also see that the navigation arrows are a bit weird in the sequence in this location. One of the problems SfM solves is a faulty compass direction, but sometimes it's the other way around, like in this case.

This flaw/bug is the same as https://github.com/mapillary/mapillary_issues/issues/2250.

Everything on the map however is using stored values in the photo, like compass direction. That's why it's correct in the map.

I'll close this issue and you can follow progress in https://github.com/mapillary/mapillary_issues/issues/2250 instead.
