### ISSUE TITLE
Please bring back "area notifications"

### ISSUE THREAD

**Issue by voschix** [mapillary/mapillary_issues#2590]
### Basic information
* Platform: `iOS` | `Android` | `Web`
* Version: `...` 
* System/Browser: `...`

I cannot find any more the Area Notifications feature in the "new" Mapillary (web and app)
Would be nice to have it back.

**Comment by katrinhumal** [comment]
@voschix Do I understand correctly that you mean the function where you could follow new comments and uploads in a specific area?

**Comment by voschix** [comment]
Yes.
I am referring to the feature that you can set in legacy.mapillary.com:

http://legacy.mapillary.com/map/settings/notifications
(lower part of the window)

Volker

**Comment by katrinhumal** [comment]
@voschix Check! I will investigate what the plan is with these and make sure your request is heard by the product team.

**Comment by katrinhumal** [comment]
@voschix closing this issue here with the comment that we don't currently plan to bring back area notifications in the same format as they used to be, but we're thinking around how to perform this in the [shape](https://help.mapillary.com/hc/en-us/articles/360004719792-Shapes) concept. To start with, shapes are only available for organizations, but it would be a great starting point to follow an area for any Mapillary user.

Also, if you'd like to discuss these topics further, I'd like to invite you to do so on the Mapillary [forum](forum.mapillary.com), which we want to start making more use of as the place for discussing all feature requests and feedback.
