### ISSUE TITLE
Signs unrecognisable

### ISSUE THREAD

**Issue by bitboy85** [mapillary/mapillary_issues#2593]
I've just found mapillary and want to use it for editing open street map. But sadly in many pictures road signs are unrecognisable.
I fully agree that this is nessessary for license plates on cars but is there a way to keep other signs clearly visible?

**Comment by katrinhumal** [comment]
Hi @bitboy85! Great that you have joined us to use Mapillary for editing OSM. :)

Some signs are falsely blurred because our algorithm is not 100% accurate. We are working to improve it, and meanwhile, anyone can go and edit the blurs. Please find more details here: https://help.mapillary.com/hc/en-us/articles/115001663705-Blurring-images

**Comment by dekarl** [comment]
Can we get a "remove this blur" shortcut for the verification of detected traffic signs? It appears as if the machine looks at the raw image without blurs applied.
Maybe a detected traffic sign can be an input for the blur decision?

**Comment by katrinhumal** [comment]
@dekarl Thanks for the input! We're thinking about how to solve this the best way and also are working on interrelating the different detections so that they help verify each other.

**Comment by katrinhumal** [comment]
This should mostly be resolved by https://blog.mapillary.com/update/2018/04/19/accurate-privacy-blurring-at-scale.html - closing here.
