### ISSUE TITLE
calculating contributions?

### ISSUE THREAD

**Issue by danbjoseph** [mapillary/mapillary_issues#2615]
I'm trying to calculate totals for some work the Red Cross did in Leyte, Philippines.
I went through and added up the numbers for the uploads listed in my feed. But they don't seem to match my numbers in the leaderboard. Is there an easy way to get the totals for a time range and area? It would be awesome if it could also be a breakdown of 360 vs standard images.

Also is the leaderboard calculated based on the displayed geometries? That is, does the Philippines leaderboard omit uploaded pictures that aren't in the yellow below?
![screen shot 2017-07-07 at 12 44 49 pm](https://user-images.githubusercontent.com/4806884/27967775-533de134-6312-11e7-9588-3608f47141b9.png)

**Comment by katrinhumal** [comment]
@danbjoseph thanks for raising this issue! Leaderboards with custom dates and for 360 imagery separately are a great idea and I hope we can offer them at some point in the future. As for now, there are only the pre-set timespans (all time, last month, last week - if applicable). The shapes we use are Mapzen's WOF-s (https://whosonfirst.mapzen.com/) and unfortunately, you are right that they do not cover everything on the border areas.

Can you tell me which date range you are trying to calculate for yourself in the Philippines and which numbers you get? I can check internally so we can compare. We have had some issues where the leaderboard doesn't take all contributions into account so it would be good to figure out if this can be the case here.

**Comment by danbjoseph** [comment]
I'm looking at the month of May 2017 for user `danbjoseph`. All pictures were taken in May, some uploads may have occurred in the first 2 weeks of June. 
- Looking (somewhat quickly) through my uploads feed on the website I counted 168 sequences and 99,021 images. 
- I've done some other uploads in the past (before May). The Philippines leaderboard for 'All time' has me at 80.3k. 
- Somewhat unrelated... on OpenStreetCam, I counted 60 sequences and 102,919. Both images and sequences should be less than Mapillary. Which makes me think I may have done some duplicate upload(s) of high image count sequences.

If you could pull it, I would be interested to know the image totals in Leyte (or really, all Philippines would be fine, since I think everything is in Leyte anyways) for both users `danbjoseph` and `arc_ttl`.

**Comment by katrinhumal** [comment]
@danbjoseph from 1 May until now in the Philippines, I get:
danbjoseph 79672
arc_ttl 6796

And all-time:
danbjoseph 80276
arc_ttl 7614

One more thing we can check - if you give me your capture dates for when you were in the Philippines now, I can just look at totals for that instead of limiting it with the shape. You probably couldn't capture in two places at the same time anyway. :)

**Comment by danbjoseph** [comment]
If going off the photo metadata (when the picture was taken), then it would be any photos for the month of May.

**Comment by katrinhumal** [comment]
@danbjoseph bingo! Your contributions in May come out as 99,023. Good job calculating from your profile. :) And also, we can draw the conclusion that the cause of the leaderboard difference is indeed the WOF shape... Good in the sense that everything is there and gets counted; bad in the sense that we can't improve this since we can't do anything about the shape.

**Comment by danbjoseph** [comment]
great. thanks! feel free to close this issue.
