### ISSUE TITLE
Traffic signs get blurred

### ISSUE THREAD

**Issue by diovon** [mapillary/mapillary_issues#2631]
### Basic information
* Platform: `Android` | `Web`

I noticed when working with the blur editor, that many signs from my capturing are getting blurred.
e.g. https://is.gd/K1R4Uv (I just shorted the link for better reading ;-) )
e.g. https://is.gd/5FZ71J

I don't know if that has an effect of your traffic sign recognition algorithm, but I thought you should know this issue. I'll try to find this things with the blur editor, but it takes time to overview my captured pics.
### Expected behavior

The blur algorithm just blur faces and car numbers.

### Actual behavior

The blur algorithm blurs faces, car numbers, vegetation and some traffic signs.

**Comment by katrinhumal** [comment]
Hi @diovon! Thanks for pointing this out. We are continuously working to improve the algorithm, but as you are seeing, it's not 100% there yet. So it's not unusual to see falsely blurred parts of images - most often they would be road and street signs, which the algorithm has confused with license plates.

The good news is that you (and everyone else) can fix this by using our blur editor. The manual fixes create data that can be used for further improving the algorithm. Read more about blurring here: https://help.mapillary.com/hc/en-us/articles/115001663705-Blurring-images.

Closing this issue since there is no immediate fix to offer, but the improvements are part of a longer process.
