### ISSUE TITLE
Unfied terminology

### ISSUE THREAD

**Issue by GITNE** [mapillary/mapillary_issues#2645]
Please unify your terminology. Some irritating and/or ambiguous terms exist throughout Mapillary. This can be observed more or less depending on the platform.

For example, the UI refers to the *background* *map* as `Basemap` whereas the URL parameter name is `mapStyle`.  Besides, the proper wording or spelling for `Basemap` would be `Base map`.

Similar is true for detections. Sometimes they are referred to as `AI detections` then as `Computer vision detections`. Is it *AI* or *Computer* *vision*? The info text speaks of *features* being identified but then one should choose *detection* *types*. What now? Is it *features* or *detection* *types*? And then, the `Image details` menu speaks of *Tagging* and *editing* *tags* *on* *this* *photo*. So, it is even three (!) terms *features*, *detection* *types*, and *tags*! :confused:
I am well aware that the things denoted by these terms are not identical, and that scholars, engineers, and developers have to distinguish between them. But, this is not how UIs for the common user should be labeled.

Or, look at the `…` (`Image details`) menu in the web viewer. There, the term *image* is used almost consistently throughout the menu but the new button for *Tagging* speaks of *photos*. This is even more confusing because in almost all of its publications Mapillary uses the term *photo* instead of *image*. IMHO choosing the term *photo* over *image* was a very good decision because even though digital photos are technically images, like any other, Mapillary's mission is to collect photos of real places, not artificially created images. 

The developer API documentation also suffers from few similar irregularities. One of which again pertains to the terms *image* and *photo*. Take for example  the `pKey` URL parameter name. But then, its value is referred to as *image* *key*. This is just one obvious example.

Please pick terms and stick to them once established. A consistent communications policy or strategy makes life easier for everybody. However, please do not take it too far by reinventing definitions because then your communication becomes propaganda. :wink:

Oh, one last thing about labeling UI elements with text in English: Please, treat all labels as title text. Hence, use capital letters on all words, except for prepositions. [Microsoft](https://www.microsoft.com/Language/en-US/StyleGuides.aspx), Google (Android), and Apple have all produced very useful guidelines on how to properly label UI elements in different languages. They are basically identical with regards to this matter. No need to reinvent the wheel, draw from the experiences and struggles of others where helpful. :smiley:

**Comment by katrinhumal** [comment]
Hi @GITNE - thank you for a thorough review of what you think is wrong. You definitely have a good point about consistency and it is something we are striving for. While we'll keep on working on it, here are a few notes.

- We have actually chosen to `images` over `photos`. It might be that we have still missed this in some places (especially in previously existing documentation, whether technical or non-technical).
- Parameter names and UI labels might be different probably because we have improved (which is a relative concept) the UI labels and not prioritised updating the parameter names accordingly.
- We use synonyms for some concepts in info texts to make the text more natural and less dry. I understand this might be confusing to some people in some cases. (Also, in the particular case of tag editing, this is actually not the same function and we have "published" it accidentally together with the AI detections, as we just discovered. This will be fixed.)
- We are not reinventing the wheel with not using title case in the UI. There are lots of heated arguments both online and offline about this. Big corporations definitely feed a lot into how most of us perceive that the world should look like, but in Mapillary, for now, we have chosen to use a more conversationally sounding approach, which is why we don't treat our UI elements as having titles.

With that said, let me underline again that we will keep working on consistency, and particularly prioritise cases where inconsistency is not just a style flaw but might actually stop people from using Mapillary.

**Comment by GITNE** [comment]
@katrin Thank you for your extensive answer and taking this matter seriously.

> We are not reinventing the wheel with not using title case in the UI. There are lots of heated arguments both online and offline about this. Big corporations definitely feed a lot into how most of us perceive that the world should look like, but in Mapillary, for now, we have chosen to use a more conversationally sounding approach, which is why we don't treat our UI elements as having titles.

I did not mean to insinuate that Mapillary is reinventing the wheel. What I was trying to hint at was that it is often easier and rewarding to build on the experiences of others (do not confuse this with traditions), even if they might seem to look like conventions initially. Certainly, the mentioned corporations do transport a lot of their own (marketing) mindset but they also have spent a lot of time and resources on genuine usability and UI research which has fruited in freely available publications. Hence, many things that may seem like conventions in their products are actually the result of research and not artistic design (or marketing) decisions. Overall, the Mapillary web design looks well, even though some UI elements could be rearranged or grouped for even more clarity. Where the web design IMHO is failing a bit is the number of clicks to get to a function. But, this a different topic from terminology.

Maybe I should have been more precise and say that only active UI elements should have title text labels in English. Passive elements and simple labels should be treated as prose text. But, I understand if Mapillary wants to go its way and also because usability is a fuzzy subject it is debatable which way to go in certain situations.

**Comment by katrinhumal** [comment]
Thanks for your kind words @gitne! There's definitely lots that we can learn from others, and rely on the research that has already been made. We'll keep pushing forward - I'm closing this issue now, with taking several points from here to help us improve. :)
