### ISSUE TITLE
The map is not obvious when visiting mapillary.com

### ISSUE THREAD

**Issue by trigpoint** [mapillary/mapillary_issues#2649]
When visiting http://mapillary.com the map is not obvious. I had to ask on the irc channel where it is these days.

The choice of 'explore places' is very unintuitive as a place to put the most important feature of mapillary, maybe the words 'view map' would make the map easier to find?

**Comment by katrinhumal** [comment]
@trigpoint Thank you for your insights! Very useful to know that this is how you experience the website. We'll take this into consideration when we think further about our web, with the aim to make it clear and easy for everyone to find what they're looking for.

**Comment by richlv** [comment]
i was also confused about that at first, but having used website before i managed to guess which is the right button. new users might give up before finding it.

**Comment by GITNE** [comment]
Yes, this has been my impression since the *relaunch* too. The map should be like almost right into your face because it is what Mapillary is all about. And, the second thing that should be as obvious as the map itself is the fact that anyone can/should contribute images to the map. These two basic principles should be equally immediately recognizable and comprehensible.

Btw, I kept silent about this because I thought that Mapillary is going to find out for themselves eventually. I also did not want to talk about this because the front page is like a business card at prime location where companies take great pride and meticulous design to present themselves to customers and users. So, to meddle in this area means to touch the core of a company's policy or mission. Anyway, I hope you will be able to make the right adjustments to the front page in order to convey Mapillary's mission even better! :wink:

**Comment by GITNE** [comment]
`Create account` gives no reason why anyone should do this. It should rather say `Contribute photos` or the like. Generally speaking, the button labels on the front page should sound engaging and inviting do something or to join Mapillary but should also be comprehensible. The other stuff on the page should give reasons to why should one click those buttons.

`Explore places` sounds engaging but there is not enough significant information on the rest of the page which would lead the assumption why should anyone do this. Explore? Yeah, fine but why? Places? Alright. What places?

**Comment by katrinhumal** [comment]
Closing this issue but taking the feedback with me as we keep iterating our web pages further. Thanks everyone for the insights!
