### ISSUE TITLE
cut sequences

### ISSUE THREAD

**Issue by jotpe** [mapillary/mapillary_issues#2654]
How can I cut sequences?

**Comment by katrinhumal** [comment]
Hi @jotpe - it's not possible for you to cut sequences post-upload. If capturing with the mobile apps, you can choose when you start a new sequence. If uploading with the web uploader, you can publish in batches and each batch will form one sequence. We do have a bot that automatically cuts sequences where the photos are too far apart. This should happen within a few days from the upload.

**Comment by jotpe** [comment]
I would like be able to do that too, *feature request*

**Comment by katrinhumal** [comment]
Thanks - we've heard that from people a couple of times before, but since it's competing with lots of other stuff to develop, it's not been taken into the near-term plan yet. On the positive side, it's not off the table either, so let's see how this goes. :)
Closing this issue since no immediate resolve.
