### ISSUE TITLE
Internal server error when retrieving detections for image key

### ISSUE THREAD

**Issue by daniel-j-h** [mapillary/mapillary_issues#2655]
I just hit an internal server error querying the `/images/{key}/detections` endpoint:

    curl "https://a.mapillary.com/v3/images/Hb2S0nTmcqbwf2iDp3axSQ/detections?client_id=XXX" | jq "."

```json
{
  "message": "Internal server error. Please report the issue at https://github.com/mapillary/mapillary_issues/issues"
}
```

(please send me a mail if you need the client id)

---

My use-case was making a query looking at an intersection:

    curl "https://a.mapillary.com/v3/images?client_id=XXX&closeto=13.41919,52.50116&lookat=13.41927,52.50129&radius=25&start_time=2016-01-01" | jq "."

Then taking the first image key and trying to retrieve detections:

    curl "https://a.mapillary.com/v3/images/Hb2S0nTmcqbwf2iDp3axSQ/detections?client_id=XXX" | jq "."

The location is here: http://www.openstreetmap.org/#map=19/52.50122/13.41928

Greetings from Berlin :)

**Comment by gyllen** [comment]
@ptpt Please elevate to internal issue

**Comment by ptpt** [comment]
@daniel-j-h Thanks for reporting. The backend should actually return 401 instead of 500 if the client ID is not permitted to access image detections. Now it should be fixed. Feel free to contact sales for editing OSM for free. See https://www.mapillary.com/developer/api-documentation/#image-detections
