### ISSUE TITLE
Too many notifications

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#2656]
Both the (Android) app and the email are giving too many notifications about photos being published.

I'm currently getting a new notification every few hours, sometimes about just a handful of images.

Please, only send ONE notification for each sequence that has been published.

**Comment by katrinhumal** [comment]
@pbb72 Thanks for raising this point. In general, you should be getting only one notification per sequence. The catch is that a sequence that you capture might not always overlap 100% with a sequence that has been processed and reaches the map. That is because actually, in the eyes of our system, there is not really the concept of a sequence before the images get processed on the map. 

When you start uploading, we see each image as an event, and have a moving time window of one hour to go with it - with every new event, i.e. new image processed, the time window restarts. So if you continuously upload and the photos continuously get processed, they will end up forming one sequence on the map that matches what you, the author, perceive as a sequence of images during capture/upload. However, if there are any obstacles along the way - either your connection speed is slow or you pause upload, or there's a lag in processing, then the time window might close and a sequence gets formed in our system - also triggering a notification.

The only thing that the system recognises from what you perceive as a sequence during capture is that it won't merge several of them together into one sequence on the map, even though you might upload in succession with less than hour-long time windows.

Please let me know if this helps explain the situation. I will gladly try to rephrase if too confusing.

**Comment by pbb72** [comment]
I think I understand what you are saying, but that means the only interruption that is happening must be on the server, because all my uploads are easily finished within an hour, and I haven't pressed pause.

I am doing all my uploads through the web interface. The only place where there often is a multi-hour gap, is between the uploading and pressing the "publish" button. (I still don't understand why there has to be an extra step after the lengthy upload process.)

For me, you can easily increase the wait time for concluding that a sequence is ready, to 24 hours. But I guess that would be more demanding on the server.

**Comment by katrinhumal** [comment]
@pbb good input! Yes, in this case, it's surely our fault that your sequences ended up interrupted. We had some quite big disturbances yesterday. The gap between uploading via the web and pressing "Publish" should not make a difference though, since it's only the publishing that sends the images off for processing. The part before that is the one where we're still able to detect if you're trying to add the same images several times.

**Comment by pbb72** [comment]
It looks like it indeed was a temporary problem. I am not getting notifications for partial sequences anymore.

**Comment by katrinhumal** [comment]
That's nice. We'll work on making the system more stable, i.e. try to avoid the underlying problem so that you wouldn't be flooded like this again.
