### ISSUE TITLE
The frame of the preview and taken picture are different

### ISSUE THREAD

**Issue by kudarisenmon** [mapillary/mapillary_issues#2660]
### Basic information
* Platform: `Android`
* Version: `3.83-BETA` 
* System/Browser: `Android 4.2.2`

### Steps to reproduce behavior

 1. Preview and Capture

### Expected behavior

The box of the preview and taken picture are same.

### Actual behavior

The box of the preview and taken picture are different.
Look at a position of the bicycle mark on the road.
The aspect ratio of the preview seems to be incorrect.

### Additional information

When driving, this issue makes it difficult to set so that part of the car does not appear.
I have not encountered this issue on Android 7.0.

![screenshot_2017-08-12-15-55-57](https://user-images.githubusercontent.com/2560699/29239577-fba88ff4-7f8c-11e7-88b5-cbf3eb71f7e9.png)
![2017_08_12_15_55_31_485_ 0900](https://user-images.githubusercontent.com/2560699/29239579-0a9384c4-7f8d-11e7-9566-b48bb398a1ca.jpg)

**Comment by HolgerJeromin** [comment]
Same as #2259 ?

**Comment by peterneubauer** [comment]
@kudarisenmon this is most likely an issue of matching the closest preview aspect ratio to the image ratio Can you please attach a log when you have started the app and just taken an image, so we can see the model, and the aspect ratios of image/preview?

**Comment by kudarisenmon** [comment]
Here is the startup debug log.
[mapillary_trace (2).txt](https://github.com/mapillary/mapillary_issues/files/1222030/mapillary_trace.2.txt)

**Comment by GITNE** [comment]
Btw, the device's camera auto mode chooses really poor photometric settings, if one is to believe the EXIF data.
```
Exif.Image.ImageWidth                        Short       1  4128
Exif.Image.ImageLength                       Short       1  3096
Exif.Image.Make                              Ascii       8  FUJITSU
Exif.Image.Model                             Ascii       6  FJL22
Exif.Image.Orientation                       Short       1  top, left
Exif.Image.DateTime                          Ascii      20  2017:08:12 15:55:31
Exif.Image.ExposureTime                      SRational   1  1/385 s
Exif.Image.FNumber                           SRational   1  F2.2
Exif.Image.ExifTag                           Long        1  284
Exif.Image.GPSTag                            Long        1  218
Exif.GPSInfo.GPSLatitudeRef                  Ascii       2  North
Exif.GPSInfo.GPSLatitude                     Rational    3  35deg 1' 5.132" 
Exif.GPSInfo.GPSLongitudeRef                 Ascii       2  East
Exif.GPSInfo.GPSLongitude                    Rational    3  138deg 28' 30.399" 
Exif.GPSInfo.GPSImgDirection                 Rational    3  162/1 12/1 24165/2048
Exif.Image.ISOSpeedRatings                   SShort      1  8000
Exif.Image.MeteringMode                      Short       1  Multi-segment
Exif.Image.LightSource                       Short       1  Unknown
Exif.Image.Flash                             Short       1  No flash
Exif.Image.FocalLength                       Rational    1  3.7 mm
```
ISO speed of `8000` :astonished: with an aperture at `F2.2` (which I assume is fixed anyway) in merely cloudy daylight! Wow, something is really wrong with the auto mode on that device. This clearly indicates that the auto mode outlandishly favors short exposure times over picture quality. The auto mode should have rather setup ISO 250 with an exposure time of 1/100. This would have produced far better picture quality and would still bear enough tolerance against shaky or blurry photos. Well, maybe the metering method just messed everything up and everything would have worked out fine if it was set to center weighted average.

Unfortunately, the device also produces one invalid EXIF field. According to the spec, the `GPSImgDirection` is supposed to hold just **1** rational. I am a bit surprised how this passed Fujitsu's QA.

@peterneubauer Does the Mapillary app control photomertic settings in manual mode? AFAIK, Android M has introduced a camera API enabling control of photometric settings. See if you can set the center weighted average metering method while the app is using the camera. This should work fine because most pictures on Mapillary are not anything near macro photography nor indoors but land scrapes.

@kudarisenmon Please remember to blur licenses plates before publishing photos. :wink:

**Comment by andrewharvey** [comment]
I ran into this too on the OnePlus One. In a car looking at the preview in the Mapillary app it looked like there was a clear view, but later seeing the photos it actually captured part of the dash. Easy workaround is to check through the camera app first, but new users won't know that and will run into this issue.

**Comment by peterneubauer** [comment]
@GITNE actually, the ImgDirection is inserted by the Mapillary app since the vendors are not to be relied on with that info. This was a bug and is fixed, in recent versions it is just one rational.

**Comment by GITNE** [comment]
>> According to the spec, the GPSImgDirection is supposed to hold just 1 rational. I am a bit surprised how this passed Fujitsu's QA.

> @GITNE actually, the ImgDirection is inserted by the Mapillary app since the vendors are not to be relied on with that info. This was a bug and is fixed, in recent versions it is just one rational.

Hihi, well then Fujitsu is in the clear. :wink: I am happy it's fixed. :smile:

**Comment by peterneubauer** [comment]
:)
