### ISSUE TITLE
Cannot add blurs as image is tilted

### ISSUE THREAD

**Issue by blobgo** [mapillary/mapillary_issues#2683]
### Basic information
* Platform: `Web`
* Version: ???
* System/Browser: Firefox 55 on Linux

### Steps to reproduce behavior

 1. Edit blurs.
 2. Now, as the instructions show, try to add a blur by drag and dropping.

### Expected behavior

Drag and drop should draw a rectangle, at least when the cursor is a cross.

### Actual behavior

The image is tilted in this 3d area, similar to when viewing the images as usual.

### Additional information

Everything else (removing or moving blurs, works)

Here you see the upper part of an image belong tilted in the blur edit mode:

![toptiled](https://user-images.githubusercontent.com/12105354/29790158-0ff5de9a-8c39-11e7-919d-8bb62d3d094c.png)

**Comment by katrinhumal** [comment]
@blobgo This is actually expected behaviour. Dragging is supposed to pan the image, while blurs will be added by click-release-move-click. I.e. you will click twice, to first mark the top left corner and then the bottom right one. Instructions for this can be seen both on our help pages (https://help.mapillary.com/hc/en-us/articles/115001663705-Blurring-images) as well as if you click on the little question mark icon at the bottom right of the blur editor.
Could you give this another try and let me know if it works for you like this?

![image](https://user-images.githubusercontent.com/16334352/30052493-4d3cd380-922e-11e7-808d-b0859b12d8db.png)

**Comment by blobgo** [comment]
Ah, got it. Maybe also add the information about how to move the image to this help screen or so.

**Comment by katrinhumal** [comment]
Thanks, good point. I'll request this.
