### ISSUE TITLE
[Android app] landscape issue

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [mapillary/mapillary_issues#2695]
* Platform: `Android`
* Version: `3.89`

### Steps to reproduce behavior

 1. Go to record tab (landscape mode)
 2. rotate phone clockwise

### Expected behavior

Landscape mode rotates based on accelerometer 

### Actual behavior

Upside down interface

**Comment by katrinhumal** [comment]
@Alessandro-Barbieri Thanks for reporting. For the time being, this is actually intentional. We have a long-term bug of images turning out rotated every once in a while for some people, and in the process of troubleshooting this issue, we've currently "frozen" the app interface. Though inconvenient and definitely not optimal, it should still be possible for you to capture even if you rotate your phone and the interface is upside down.

I'm closing this issue for now since it won't be fixed separately, but the plan is to address it when we've managed to fix the underlying issue of the rotated images.
