### ISSUE TITLE
sequence ID from explore tab in app

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [mapillary/mapillary_issues#2696]
### Basic information
* Platform: `Android`
* Version: `3.89` 

Would be nice to have the sequence ID of a photo in the explore tab in the app.

**Comment by katrinhumal** [comment]
@Alessandro-Barbieri Thanks for the suggestion! The trouble with the mobile apps is that on a small phone screen, it easily becomes very crowded when lots of functions are added. That's why we've decided to keep it as basic as possible, and make most of the more advanced features available on the web. The good thing is that if necessary, you can easily open the same sequence in your mobile web browser and access the features there. Just tap on the `mapillary.com` at the bottom right of the image when viewing it in the Explore tab. Then you can open it in your browser, tap on the three dots icon on the right, and find the image or sequence key under advanced options.

I'm still interested to know - what are the situations when you miss the sequence ID in the app Explore tab?

**Comment by Alessandro-Barbieri** [comment]
It's enough to add an option to share the sequence ID alongside the image link

**Comment by katrinhumal** [comment]
@Alessandro-Barbieri Just to help me understand you better and build a stronger case when I pass this request to our team - can you please give a few examples of what you would want to use it for on your phone?

**Comment by Alessandro-Barbieri** [comment]
@katrinhumal I want to report  upside down sequences from the app, my browser is too slow and cluttered

**Comment by katrinhumal** [comment]
@Alessandro-Barbieri I hear you. Will pass this on to the team and I hope we can figure something out about the whole reporting rotations process.
