### ISSUE TITLE
Forum login

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [mapillary/mapillary_issues#2701]
Is it possible to allow login into the forum with the mapillary credentials?

**Comment by katrinhumal** [comment]
@Alessandro-Barbieri Unfortunately, not now. It would surely be great but we don't host the forum ourselves, and therefore integration is not very simple. But we have this request in mind for several users so hopefully, we'll be able to provide this some day.
I'm noting your request to our team and closing this issue since it won't likely happen in the near future.
