### ISSUE TITLE
More sign detection requests

### ISSUE THREAD

**Issue by maning** [mapillary/mapillary_issues#2730]
This is feature request to add more signs in the traffic sign detection.  I will update the lists as our team encounters them.

| Sample Sign | Category | Description |
|----|----|----|
| ![](https://user-images.githubusercontent.com/17470597/31265282-b048f65a-aa8b-11e7-937e-93c04cae658c.png) | regulatory-turn-left-no-u-turn | Allows only a left turn, no u-turn is allowed

cc @krishnanammala

**Comment by GITNE** [comment]
:laughing: To me, this looks like a custom creation of a local transportation board/authority, which is mind boggling because the FHWA “Manual on Uniform Traffic Control Devices for Streets and Highways” has had `R3-5L` and `R3-4` for decades and somebody either did not read it or is trying to reinvent the wheel (or created this big *new* sign thinking that it is going to cost less than two mass produced standard signs). I am not sure this sign is even legal at all. Which unfortunately is sad and ridiculous at the same time.

And, the best of it is that if you start think about this *new invention*; does it mean that from a through only lane a u-turn is permissible? :laughing: Yeah, that makes sense! Brainiacs and geniuses at work! :laughing:

**Comment by ybkuang** [comment]
mapillary_issues is no longer an active repository.
This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!
