### ISSUE TITLE
[Android] Prevent app to rotate image when capturing

### ISSUE THREAD

**Issue by Binnette** [mapillary/mapillary_issues#2734]
I capture image on my bike. I think sometimes, my phone is shaked and Mapillary capture an image "upside down". Is there a way to prevent this ? Can't you force Mapillary to always capture image in the same "position" ? I'm pretty sure you can :smirk_cat: 

### Basic information
* Platform: `Android`
* Version: `3.104` 
* System/Browser: `Android 6.0`

### Steps to reproduce behavior
 1. Start Mapillary on your bike
 2. Ride your bike
 3. Ride on a "speed bump"
 4. Your image is captured upside down !

### Expected behavior

The image must be captured in correct position.

### Actual behavior

The image is upside down.

### Additional information
https://www.mapillary.com/map/im/kBaRe8BgvL-Q9zkY5FyInA

![image](https://user-images.githubusercontent.com/6597721/31387094-6de77138-adc9-11e7-9ebb-582823a6cb15.png)

**Comment by katrinhumal** [comment]
Hi @Binnette - thanks for reporting. We've had a long-standing bug that causes rotated images, and we've managed to fix it for a lot of devices, but still not yet for all of them. So we'll keep working.

However, as in your case, when the phone is shaking while the image is captured, then we can't really do much about it. That's because the shaking is confusing the accelerometer, which then falsely adjusts the image orientation. Therefore, you should try to take it slow and smooth - not always easy, but gives better results. :)

**Comment by Binnette** [comment]
Ok, thanks for the explanations.
Here is my device :
- brand: HOMTOM
- model: HT17 Pro
- build: HOMTOM-HT17Pro-Android_6.0-R09-20170104
- android: 6.0
- android security fix: 5 december 2016
- kernel: 3.18.19

I will close this bug and wait until this one is fixed : #2732
