### ISSUE TITLE
Blur on traffic signs

### ISSUE THREAD

**Issue by operon** [mapillary/mapillary_issues#2735]
Hello,

There are often blurred signs on road signs.

Is it possible when the AI detects signposts blur functions is non-existent or with a lower priority level.
https://www.mapillary.com/map/im/eVTP-qjxg_UPm37ext5Muw

Conversely, on vehicle detection, the fuzzy function may be more precise.
https://www.mapillary.com/map/im/WTIeEaG2cftDEAdxpiK8Uw

**Comment by katrinhumal** [comment]
Hi @operon - thanks for your input. An improved version of blurring is currently in the works, where we plan to do exactly what you said, i.e. consider the context around the blurred area. Working this out will take some time but the results will improve the accuracy. I'm closing this issue since there is no instant fix.
