### ISSUE TITLE
Webuploader: no method to resume stuck upload

### ISSUE THREAD

**Issue by polarbearing** [mapillary/mapillary_issues#2744]
I had a sequence of 51 images which got stuck at image 38. There was no method (resume button or so) to continue the upload. The last resort was to reload the page. Having done so, the page told me that 38 images were uploaded. Thus the rest was missing. When starting the upload from scratch, there is no method to distinguish the already uploaded from the rest, thus they end up as duplicates.

**Comment by katrinhumal** [comment]
Hi @polarbearing - actually, at this stage the uploader is able to recognise duplicates. That's because the images first get uploaded to the staging area, not straight to Mapillary. They only get sent to Mapillary when you hit "Publish", and after that, we can't recognise duplicates anymore. 
But as long as you haven't published yet, the same images will not be uploaded twice. Try it out on a small batch to see how it behaves. :)

**Comment by polarbearing** [comment]
As said in #2839, the workflow is cumbersome since I cannot identify which of the partial upload is in the staging area and which not, so my only chance is to delete them from the staging and start everything new.

**Comment by katrinhumal** [comment]
Response in #2839: when you try to add images to the staging area that are already there, the uploader is able to figure this out and will skip adding those for the second time. So you can just add your whole folder again, no need to delete the ones that are already in the staging area.

It's only after you hit the Publish button that duplicates unfortunately can't be detected anymore.
