### ISSUE TITLE
Blurring of faces with sunglasses often fails

### ISSUE THREAD

**Issue by voschix** [mapillary/mapillary_issues#2754]
### Basic information
* Platform: `Web`
* Version: `current` 
* System/Browser: `NA`

### Steps to reproduce behavior

 check blurring results

### Expected behavior

Faces with and without sunglasses should blurred 

### Actual behavior

It appears as if I have a larger percentage of people wearing sunglassess amongst the missing face blurs

### Additional information

I have no statistics, so I may be wrong

**Comment by katrinhumal** [comment]
@voschix you are probably right, I'm not sure we've had so many images of faces with sunglasses in the training data. Therefore, the algorithm would only have "half a face" to recognise (eyes are an important feature altogether in that) and is more likely to fail. I'll notify our computer vision team about this so that we can take this into account as the algorithm gets further trained!

**Comment by ToeBee** [comment]
Also hats and (probably more noticeable to me than most users) bicycle helmets tend to throw it off :)

**Comment by ligfietser** [comment]
Faces are now much better recognized and blurred, but here Mapillary fails:
https://www.mapillary.com/map/im/JZR63zMeqB8SYSC9XRZ9TA

**Comment by katrinhumal** [comment]
Thanks for reporting @ligfietser - we've listed these internally as the computer vision team keeps working on blurring even now when we have a 99.9% detection rate. :)

If you (or anyone) see more examples, please email them to us at support@mapillary.com. We're phasing out mapillary_issues so I'm closing here.
