### ISSUE TITLE
add fast-forward button

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [mapillary/mapillary_issues#2775]
### Basic information
* Platform: `Web`
* System/Browser: `Firefox`

Would be nice to add a fast-forward like button in the web interface to jump to the first image of the current sequence.

**Comment by katrinhumal** [comment]
@Alessandro-Barbieri Thanks for the suggestion! I'll pass it on to the team so we can discuss this when we develop the viewer further. The thing that's holding us back from adding lots of buttons is that the interface would become very cluttered.

Meanwhile, I can suggest two ways for you to get to the beginning of the image:
1) zoom out on the map until you see the endpoint of the current sequence, which is displayed in blue, and click on the respective dot on the map (if necessary, zoom in again at that spot)
2) use the three dots menu (...) on the right to find the sequence key under "Advanced options", then use that in the URL `mapillary.com/map/s/{sequencekey}` and it will take you to the first image of the sequence.

Closing here since no instant fix.
