### ISSUE TITLE
31 MPH - Trenton, TN

### ISSUE THREAD

**Issue by AllenGraetz** [mapillary/mapillary_issues#2776]
An edge case for the AI folks.   Trenton, TN has a 31MPH speed limit, not 25, 30, 35, etc. that are usually found.     They'll want to update the AI at some point to be able to recognize this.

Also, any plans on adding something to the desktop web GUI to enable us to flag traffic signs that the AI missed?   grax

https://www.mapillary.com/app/?lat=35.97956388888889&lng=-88.94172500000002&z=17&pKey=WOYofGVU-ZDOOM-ZQCpQOg&focus=photo&signs=true&menu=false&x=0.5190329277388062&y=0.8371162488133959&zoom=1.7777777777777777

![image](https://user-images.githubusercontent.com/11722025/32191275-de1f7690-bd86-11e7-93b3-2b8958a39f75.png)

**Comment by GITNE** [comment]
:laughing: To be honest with you, I do not think the AI needs an update—it’s more like someone at the transportation authority or police department needs a brain update. Sure, this is a perfectly legal sign but it is pointless not to post a standard mass produced 30 mph speed limit sign—which is also cheaper and has the same effect. If the AI detects this sign as a 30 mph sign then thumbs up (and good riddance).

To say the least, I have also seen 9½ mph speed limit signs. Yes, 9½ mph speed limit, no joke! Personally, I thought this kind of thing only belonged into Harry Potter’s world of fantasy. But no, this thing was for real. Conclusion: You fill all sorts of stupidity on public roads—not only by drivers but also by the authorities. You cannot possibly build any AI which is going to be able to adequately deal with every kind of human stupidity, unfortunately… :dissapointed:

**Comment by katrinhumal** [comment]
@AllenGraetz Thanks for pointing out this curious case! I'll definitely mention this to our computer vision team. And yes, we plan to make more tools available within the "[Human in the Loop](http://blog.mapillary.com/update/2017/10/12/human-in-the-loop.html)" concept but we're not at the stage yet to say anything specific about what and when. Very glad to hear you're interested in this!

Closing the issue since no instant fixes.

**Comment by GITNE** [comment]
![9½ mph speed limit](https://c1.staticflickr.com/7/6048/5912166105_4133c3202a_b.jpg "9½ mph speed limit")![7½ mph speed limit](https://farm1.staticflickr.com/22/24344425_5b4afa6802.jpg "7½ mph speed limit")

So, they do exist, and not only on private property. It’s a pity I cannot find any examples on Mapillary but there are images. They came up in the verification tool.

On the other hand, these speed limits or signs are clearly politically motivated and are not really a service to anybody, except for the fact that they may catch some drivers’ attention when passing for the first time, so that they may adjust their speed accordingly. However, I would argue that even in this case they cause more confusion than they provide clarity or safety (or protection mostly to pedestrians). Hence, there is little need to bother about it from an AI perspective.

Besides, there are good reasons for why the US FHWA’s MUTCD says that “speed limits shown shall be in multiples of 10 km/h or 5 mph”. Again, no need to go into detail here why that is. Just use plain simple common sense and you will figure it out.
