### ISSUE TITLE
Setting Distance based capture once for all

### ISSUE THREAD

**Issue by severinmenard** [mapillary/mapillary_issues#2782]
I noticed on my Android app for my Moto G5 than the Distance based capture parameter is deactivated whenever you switch from automatic to manual capture mode when capturing. The capture mode becomes automatically time based, therefore you need to go back to the settings/capture to reactivate the distance based capture mode.

**Comment by Eric-FR** [comment]
Same observation with Wiko P4200AN.

**Comment by fgouget** [comment]
I have the same issue with my Galaxy S7. This is nothing new; this issue has been there for many months, maybe over a year. However to reproduce one needs a bit more than switching to manual mode and back. Here is the precise procedure:

1. Make sure that the capture mode is Auto+distance-based.
1.a. Go to the capture screen and make sure it shows 'A' for automatic capture
1.b. Open the Settings -> Capture screen and make sure that 'Use distance-based capture' is checked.
1.c. Close the settings screen and start a capture while not moving.
1.d. Verify that Mapillary takes a single picture. This proves that it is in distance-based mode.
1.d. Stop the capture.

2. Breaking things
2.a. Still on the capture screen, swipe the toggle to switch to Manual capture mode.
2.b. Take a picture.
2.c. Click on the icon to go review the brand new sequence.
       `---> This is the step that breaks the distance-based setting!
2.d. Go back to the Capture screen.
2.e. Swipe the toggle back to Auto mode.
2.f. Start a capture while not moving. **Mapillary now takes a picture every second**.
     (Or if you're unlucky like me, sometimes Mapillary only shows a black screen and takes no picture in which case exit and reenter capture mode and try 2.f again)
2.g. Stop the capture.
2.h. Open the Settings -> Capture screen and indeed 'Use distance-based capture' is **unchecked**.


You can verify that step 2.c. is the one breaking things simply by skipping it.
You can also check that 2.d. is not the source of the problem by reviewing the sequence while in Auto mode. The distance-based setting does not get lost.


This bug is very annoying. It causes Mapillary to surreptitiously switch to taking one picture every second which is a major pain for city driving where you cannot go 100 meters without getting stopped by a traffic light, stop or traffic jam :-(

**Comment by HolgerJeromin** [comment]
#2360 was closed as fixed. :-(

**Comment by ovivoda** [comment]
_mapillary_issues is no longer an active repository._

_This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!_
