### ISSUE TITLE
Switching sequence discards any changes without warning

### ISSUE THREAD

**Issue by AffeAli** [mapillary/mapillary_issues#2802]
### Basic information
* Platform: `Web`
* Version: `2017-11-17` 
* System/Browser: `Arch Linux/Firefox 57`

### Steps to reproduce behavior

 1. Make changes to a sequence (like positions etc.)
 2. Use the spatial arrows on the picture to move to a picture in a different sequence

### Expected behavior

* A warning about the sequence switch

### Actual behavior

* Editor switchs picture and sequence **discarding any not submitted changes**

### Additional information

There should be a warning or the spatial arrows to a different sequence should not be displayed.

**Comment by katrinhumal** [comment]
@AffeAli thanks for reporting, let's see what we can do here. PS I edited "navigation arrows" into "[spatial arrows](https://help.mapillary.com/hc/en-us/articles/115001761965-Spatial-arrows)" in your comment just so it's clear which of the two types of navigation arrows you are talking about (since this problem doesn't apply to the [sequence arrows](https://help.mapillary.com/hc/en-us/articles/115001724909) at the top of the image).

**Comment by gyllen** [comment]
@AffeAli @katrinhumal My suggestion would be that we remove the "spatial arrows" from the interface. This was you will always be editing in the preferred sequence. WDYT?

**Comment by katrinhumal** [comment]
It makes sense to me since you can't edit outside of the sequence in the same go anyway.

**Comment by gyllen** [comment]
@nickplesha Is it possible to remove spatial arrows in editing mode?

**Comment by nickplesha** [comment]
@gyllen Yes, we can remove them.

**Comment by gyllen** [comment]
@nickplesha Perfect, elevate!

**Comment by nickplesha** [comment]
Thanks for reporting! This should be fixed now.
