### ISSUE TITLE
review of user edits

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [mapillary/mapillary_issues#2803]
Do you really review user edits or just auto-approve them?
An user edited the compass angles of a sequence, @peterneubauer approved them but are WRONG

**Comment by voschix** [comment]
This is touching on a wider issue: there is no way for users to communicate. 
In this case the better procedure would have been that the user who detects a possible problem with a sequence, could contact the author instead of correcting the sequence. 
I feel guilty on that sense, as I have, very occasionally, requested sequence orientation changes.

**Comment by katrinhumal** [comment]
Indeed, a lot of edits get auto-approved. To date, we have not heard any complaints of someone mis-editing sequences, and also it's possible to fix or even revert them if something really goes wrong. But the same doesn't apply to deletions and that's why we don't auto-approve when you try to delete someone else's contributions.

The current way for communication between users is via commenting on each other's images. We know it might not be optimal in some cases but creating a more elaborate communication system is right now less of a priority than e.g. improving our data accuracy and the tools that are at the disposal of our community. However, this doesn't mean it can't become a priority sometime in the future. And for the purpose of discussing the imagery and any edits it might need, commenting on images should work quite well.

**Comment by Alessandro-Barbieri** [comment]
>The current way for communication between users is via commenting on each other's images.

So should I take a random image from that user and comment?

**Comment by katrinhumal** [comment]
If you just want to get in touch then any image will probably do. If you want to say something about a specific image or sequence, related to potential edits to them, then I suggest doing that on that image or an image of that sequence. The author will see this in their feed and also get notifications (provided they are turned on).

**Comment by Alessandro-Barbieri** [comment]
In my case the image modified was mine, will the other user get the notification?
