### ISSUE TITLE
Order of photos in a sequence is wrong if date exif is the same

### ISSUE THREAD

**Issue by tobecwb** [mapillary/mapillary_issues#2809]
### Basic information
* Platform: `Web`
* System/Browser: `Windows/Google Chrome 62.0.3202.94 x64`

### Steps to reproduce behavior

 1. Upload a new sequence with two or more images with same date (including the seconds)
 2. Access the sequence on web browser
 3. The map shows the sequence out of order (lines connecting the photos). The sequence skips an image, and then returns the skipped image, looking like "you take two steps forward and one step backwards"

### Expected behavior

Show the images on correct sequence, one image after another, without jump forward, jump backward.

### Actual behavior

If two or more images has same timestamp on EXIF, sometimes the sequence is wrong.

### Additional information

See the two previous images on this link: https://www.mapillary.com/app/user/projevias?lat=-25.369692630963655&lng=-49.116332436427854&z=20&feedItem=user-2lv8X-hz4sE7lli0VP_3bw-activity-user-2lv8X-hz4sE7lli0VP_3bw-publishing_done-image%3A1511210888788&pKey=A5gnVghni6vvsVD34EbnMw&username%5B%5D=projevias

In this link, the current image, and the two previous images has the same timestamp (`2015-12-16T17:44:38Z`)

This "bug" is similar to the bug reported in https://github.com/mapillary/mapillary_issues/issues/2670.

I think Mapillary only use the timestamp to known the sequence... but the filename of original image (including the key used on upload script) has a sequential number.

In my case, because the mapped area is urban, the distance between the points are shorter.
There's any solution for this without discard photos with same timestamp?

**Comment by gyllen** [comment]
@tobecwb We always do order in timestamp, is it possible for you to introduce milli seconds to the timestamp. One way todo it it would be to use the ms as just a sequential number

**Comment by tobecwb** [comment]
I don't think EXIF support milli seconds on GPSDateStamp or GPSTimeStamp

ref:
https://sno.phy.queensu.ca/~phil/exiftool/TagNames/GPS.html
https://www.awaresystems.be/imaging/tiff/tifftags/privateifd/gps/gpstimestamp.html
http://www.exiv2.org/tags.html
http://www.opanda.com/en/pe/help/gps.html

**Comment by gyllen** [comment]
@ybkuang Can you confirm this ^^^

**Comment by ybkuang** [comment]
@tobecwb we need to add the milli seconds [here](https://www.awaresystems.be/imaging/tiff/tifftags/privateifd/exif/subsectime.html)

**Comment by GITNE** [comment]
> I don't think EXIF support milli seconds on `GPSDateStamp` or `GPSTimeStamp`

@tobecwb @ybkuang In fact, `GPSTimeStamp` **does** support fractional seconds by specification since its inception. `GPSTimeStamp` is a rational number tri-tuple, hence you can represent all fractions in 1/2147483647th steps. Of course, irrational numbers are excluded by definition.

`SubsecTime`, `SubsecTimeOriginal`, and `SubsecTimeDigitized` enable you to store fractions of up to 6 decimal digits, in other words µs. This should be quite enough for almost all applications, unless you are playing around with ultra high speed photography.:grinning:

@tobecwb The problem with identical time stamps is that in this case there is no way to decide which one comes first when *stitching* a sequence together. What one could do is to *fall back* to UTF-8 file name collation in this situation. But, at best, this would only serve as a last ditch desperate attempt to get things into deterministic order (since identical files in a sequence must not exist, though they *could* potentially get uploaded), assuming that file names are in sequential order. Deterministic order still does not guarantee correct order.:wink:

**Comment by gyllen** [comment]
@ybkuang Reassigning to you

**Comment by peterneubauer** [comment]
I'm closing this, since GPS timestamp support for date extraction is now on our internal tasklist and will come out soon.
