### ISSUE TITLE
Deleted sequence still visible

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [mapillary/mapillary_issues#2824]
I deleted a sequence but it's still visible on the map.
https://www.mapillary.com/app/?lat=45.55667171519568&lng=10.229010053581419&z=18.133607664628006

If I click on the green dots I'll get

> Sorry, we can't find the image you're looking for. Most likely, the image is still under processing and will be visible soon. Please check back later. If you need more help, contact us.

It's visible up to zoom 8 (and maybe beyond)
https://www.mapillary.com/app/?lat=45.54578861934354&lng=10.25096834026408&z=8&username%5B%5D=baliano&dateTo=2017-10-25&dateFrom=2017-10-25

**Comment by GITNE** [comment]
I would also like to note that deleted sequences and images leave extracted data behind:
* Thumbnails in the feed
* Semantic segmentation location points (yellow dots on the map)
* Detected traffic signs
* Possibly also tags

**Comment by gyllen** [comment]
@Alessandro-Barbieri Sometimes it takes some time for our caches to clear out. Sequence will soon be gone from map.

@GITNE To be correct
Deleted sequences might leave thumbnails in the feed during caching period but they will disappear after a while.

About other artefacts you are right they take longer to clear out.

**Comment by GITNE** [comment]
> About other artifacts you are right they take longer to clear out.

@gyllen Ah uhm, no offense but really? Like [those](https://www.mapillary.com/app/?lat=54.17464400906587&lng=15.562896500000079&z=17.745796984261247&focus=map&signs=true "Podporucznika Józefa Śliwińskiego") since September 2016?

**Comment by Alessandro-Barbieri** [comment]
@gyllen Soon™ which order of magnitude? Monthly, yearly? Or it's just bugged? It was deleted some weeks ago together with other sequences  (but the other sequences disappeared the day following)

**Comment by gyllen** [comment]
@Alessandro-Barbieri Checking now what happened to that sequence

@GITNE Yeah only updated when we update the merging algorithms or new data is added to the area.

**Comment by Alessandro-Barbieri** [comment]
@gyllen that specific deletion was approved by katrinhumal

**Comment by GITNE** [comment]
> @GITNE Yeah only updated when we update the merging algorithms or new data is added to the area.

@gyllen :thinking: Sounds like an *interesting* strategy. In order to completely get rid of artifacts you have to *overwrite* them with new data? The problem is that this strategy is confusing to mappers and also sort of violates the terms of service, where deletion is part of the general “contract”. Mappers have to double check that the symbols they see on Mapillary are still current, or are actually reflected in the imagery, which is wired because this is the kind of work why you employ AI in the first place.

Alright, I am going to try to capture this area again and check if the residual artifacts disappear. This time in better quality. Lack of quality was one reason why I have deleted that sequence back then.

**Comment by katrinhumal** [comment]
@gyllen https://www.mapillary.com/app/?lat=45.55667171519568&lng=10.229010053581419&z=18.133607664628006 still seems to be there...

**Comment by gyllen** [comment]
@peterneubauer Can you take a peak at this sequence ^^^

**Comment by peterneubauer** [comment]
Dirtying it, should be deleted with tiles etc by tomorrow.
