### ISSUE TITLE
Web uploader does not honor set map style

### ISSUE THREAD

**Issue by GITNE** [mapillary/mapillary_issues#2831]
### Basic information
* Platform: `Web`
* Version: `Any` 
* System/Browser: `Linux/Firefox`

### Steps to reproduce behavior
1. Select a map style other than `Mapbox Streets`
2. Go to web uploader. It does not matter if via left hand menu, right hand `Uploads` panel, or browser’s address bar.
3. Select any files to upload
4. Click on the map style icon
5. Observe that the correct map stile is selected but `Mapbox Streets` is rendered.

### Expected behavior
The web uploader should honor any previously set map style.

### Actual behavior
The web uploader always launches with the Mapbox Streets vector map style, even if the user has previously set a different map style. This behavior may be considered abnormal because when in the web uploader, if the user clicks on the map style icon the radio button of any previously selected or rendered map style (other than `Mapbox Streets`) is checked, yet the `Mapbox Streets` is rendered.

### Additional information
I do not know if this glitch only pertains to Firefox. Probably not. :worried: But, it should be easy to fix. :wink:

**Comment by AnkEric** [comment]
Also Google Chrome.
You have recently suggested using a 'not vector' map as work-around to upload files. (Resolved now).
I couldn't select a 'not vector' map (Mapbox Satellite) for Upload.
Always [MapBox Streets] will be selected during Upload.

**Comment by GITNE** [comment]
> I couldn't select a 'not vector' map (Mapbox Satellite) for Upload.
> Always [MapBox Streets] will be selected during Upload.

@AnkEric You have to select files first (because the `Browse files…` popup is modal), then you can switch the map style. This may seem a little bit odd from usability perspective but it is an acceptable design decision.

**Comment by AnkEric** [comment]
> You have to select files first (because the Browse files… popup is modal), then you can switch the map style. This may seem a little bit odd from usability perspective but it is an acceptable design decision.

Oke, but during the - resolved - showstopper I did not reach the point where I could select the map.
Browse files... and map was not responsive. 
This issue is resolved now, no need to select another map than [MapBox Streets].

Not relevant anymore, just confirming - this - issue applies to Chrome as well.

> "rendered map style (other than Mapbox Streets) is checked, yet the Mapbox Streets is rendered".

**Comment by gyllen** [comment]
@nickplesha Reassigned to you for decision

**Comment by AnkEric** [comment]
First step: it's OK.

- Open https://www.mapillary.com/app/user/ankeric
- Select [Map style] = OpenStreetMap
- Close https://www.mapillary.com
- Re-Open https://www.mapillary.com/app/user/ankeric
- [Map style] = OpenStreetMap is still selected **and** Rendered Map style = @ OpenStreetMap 
- OK!

![image](https://user-images.githubusercontent.com/20150550/43384543-a5fc7e00-93de-11e8-8494-7ffc183d983a.png)

Next step is NOT OK:
- Open https://www.mapillary.com/app/user/ankeric
- Select tab [Upload]
- Select [Upload]
- Rendered Map style = @ Mapbox (**it has been changed!**)
- Open [Map style] --> OpenStreetMap is still selected, but NOT rendered.
- Re-select [Map style] = OpenStreetMap (click and do not change, since "OpenStreetMap" is already selected ) --> - Rendered Map style = @ OpenStreetMap (which is OK, again)

![image](https://user-images.githubusercontent.com/20150550/43384552-ad0d09d0-93de-11e8-935a-da5e879ede60.png)

Summary:
I want to select "OpenStreetMap" as [Map style]. [Map style] should not change, unless I do change [Map style]. 
Keep state!

**Comment by nickplesha** [comment]
@GITNE @AnkEric This should be fixed now, the selected map style will be used in the uploader and the map selector will show the correct value. Thanks for your patience!

**Comment by GITNE** [comment]
@nickplesha Thank you!
