### ISSUE TITLE
GNSS quality indicator fading out - bad idea

### ISSUE THREAD

**Issue by polarbearing** [mapillary/mapillary_issues#2838]
Android 7.1.1, mapillary 3.117

In older versions, the GNSS quality indicator was always on screen. It seems in recent versions, it has been moved on top, and while the gray (no fix) and red (bad fix) stick on the screen, the orange and green (good/very good fix) fade out after a second or so. 

I consider this a bad idea. While driving I can only give the device a glimpse in safe situations, e.g. when stopping at a traffic light. I cannot stare on the screen just to be informed about the quality of the GNSS signal, and once it is faded out, I cannot get this information.

**Comment by katrinhumal** [comment]
@polarbearing thanks for sharing your thoughts! Just to give a little insight into how we were thinking here - the screen is only clear when the fix is good or very good, which is when everything works as it should. Having the no/bad fix message stick around is similar to the principle of displaying an error message; while there is no need to constantly display a message that says `No errors`.
Could you explain a bit why you feel like it would be useful for you to see the good/very good fix indicator at all times?

**Comment by polarbearing** [comment]
Besides having daylight, to have a correct location fix is the key point for using the capturing app. Thus it is a condition I'd like to actively monitor. There are other conditions like battery level (which is already in the device's status bar), temperature and storage shown permanently which are less important. 
The current label for the GNSS quality is too big for permanent display, the small dot we had previously was better. 
You might colour the ring around the trigger button according to the quality, if you don't want the icon back.
BTW, my device is using more GNSS services than just GPS (Glonass, Galileo, etc,) so that should be phrased accordingly.

**Comment by katrinhumal** [comment]
@polarbearing thanks for the insights! I'll pass this onto the team for consideration. Meanwhile, I hope it helps you somewhat to know that if the GPS indicator is not visible on the screen, there is only one conclusion to make - that the location fix is good and capturing is possible.
