### ISSUE TITLE
Leaderboard - Florida & Georgia & Alabama & ???

### ISSUE THREAD

**Issue by AllenGraetz** [mapillary/mapillary_issues#2858]
I'm not seeing Florida as an option in the leaderboard.  Well, Florida the county in Puerto Rico is showing.  But I'm looking for Florida the region ( aka state ).   I didn't see an open issue for this one.

![image](https://user-images.githubusercontent.com/11722025/35590480-0a109dba-05d5-11e8-9e13-cddf4dd0ebda.png)

**Comment by AllenGraetz** [comment]
It looks like more than one state has this issue.  North Dakota shows up as a region.  But neither Georgia nor Alabama do.  Maybe it's not searching regions for those?  Not adding the region to the JSON the service is returning?

![image](https://user-images.githubusercontent.com/11722025/35590715-ad51986c-05d5-11e8-87c1-45e072c8e889.png)

**Comment by gyllen** [comment]
@AllenGraetz Thanks for reporting this. This is actually an effect of MapZen shutting down and we have to fallback to out own search API. We are currently investigating on how we can improve that.

@knikel  @peterneubauer ^^^ looks strand

**Comment by peterneubauer** [comment]
Seeing it, will check why the US states are not searchable. They should be importable and found in our backend.

**Comment by gyllen** [comment]
@AllenGraetz We are currently working on brining up a local clone of spelunker so it should not take that long until we have the better search back. So stay tuned.

/cc @peterneubauer

**Comment by GITNE** [comment]
@gyllen @peterneubauer
Yeah, [Mapzen’s whoisonfirst](https://whoisonfirst.mapzen.com) is utterly broken beyond repair. I was to open an issue on this too, because unfortunately, in the past whoisonfirst has suffered poor imports by people who apparently did not know what they were doing, especially on countries which use other codepages than ISO-8859-1 or WINDOWS-1252. This cannot be easily fixed anymore. Basically all countries which use the latin script with diacritics or other marks are broken, hence many Czech, Polish, Slovak etc localities are inaccessible.

Additionally, whoisonfirst does not seem to “forget”. It does pull new locations from OSM but it does not handle edits or deletes from OSM. Which over time, causes a huge pileup of garbage.

My hope and advice would be to migrate to [Nominatim](https://nominatim.openstreetmap.org). I am well aware that this is not as easy as it may sound but after all it is correct, consistently uses UTF-8, is up to date, and it works as expected.

Finally, IMHO whoisonfirst is logically broken and cannot ever achieve its initial goal. But, this is a topic of its own.

**Comment by peterneubauer** [comment]
Agreed,
there are other sources than WOF, but it lends itself quite easily to import the shapes for searches on images and other stats. We are working on getting the spelunker up ASAP.

**Comment by pbb72** [comment]
It's not limited to US states. Also searching for the country Norway (Mapillary's neighbour country!) and it's capitol Oslo comes up with faulty results.

**Comment by gyllen** [comment]
@pbb72 Yeah we working on getting Spelunker search up locally (much smarter search)

**Comment by peterneubauer** [comment]
Florida is now working, looking at Norway ...

**Comment by peterneubauer** [comment]
Norway is now also working, please confirm the rest. We had to check explicitly for validity of the WOF shapes, and use a little hack (shapely.buffer(0) ) to make some of them valid. https://www.mapillary.com/app/stats/85633341?lat=36.69653718786422&lng=12.262098500000093&z=1.6319280293872382
