### ISSUE TITLE
Feature request: Support for USB Webcam

### ISSUE THREAD

**Issue by dr2okevin** [mapillary/mapillary_issues#2882]
In my Car I have a android headunit that also has GPS, Wifi and LTE, but no internal Camera. But there are a bunch of USB Ports where I could connect a webcam. If the Android App supports webcams, I could easy record and upload on my daily driving.

**Comment by katrinhumal** [comment]
Hi @dr2okevin - thanks for the request! Currently, we don't have any plans for supporting webcams. We'll keep the request in mind for the future though.

**Comment by GITNE** [comment]
If I may add, the general problem is that not all Android devices which have even multiple USB ports also have USB camera support. USB camera support depends on the vendor specific flavor of Android (firmware) the device is running. More specifically, the Android device must be running an Android kernel which has the USB camera device driver compiled into it (AFAIK the Android kernel does not support kernel modules, in contrast to the Linux kernel). So, even if the Mapillary app would support USB cameras on an app level, it would not necessarily work on every Android device (with USB ports) because some vendor specific Android flavors lack the necessary device drivers (by design).

**Comment by GITNE** [comment]
If I may add even a bit more; What @mapillary could certainly do—I do know if this is already implemented in the app—is to enable users to select a specific camera to use to capture, if a device has multiple cameras. The rationale behind this is that if a device supports USB cameras it is also probably going to be available through the Camera and Camera2 API which would mean minimal development effort to @mapillary. At the same time, USB camera users would potentially also benefit from it. @peterneubauer, would you accept this scenario?

@dr2okevin Please bear in mind that this would still not solve your problem if your Android flavor does not support USB cameras by design.

**Comment by dr2okevin** [comment]
My Device is a Ownice C500. The backplate looks like this [https://www.ownice.es/img/cms/638544966.jpg](https://www.ownice.es/img/cms/638544966.jpg)
There is already a DVR app preinstalled, but I couldn't get it working with my old logitec webcam.

**Comment by GITNE** [comment]
@dr2okevin Thank you for the diagram. Well, if you have tried your standard USB webcam—which actually all Logitech cams are—on all of the available USB ports and no other app can access it then you are probably out of luck. If there is a vendor provided app which works with USB cameras but no other app then the vendor has not implemented the USB consortium's standard USB camera support (exists for over a decade now) but a proprietary solution.

I do know why Android device vendors choose to exclude USB camera support from their flavors—because it takes only just about 20KB of static kernel space to run the device driver—but it seems to be a common practice on non-phone devices. I am saying this because I had a similar problem with an Android gaming console and set top boxes which also have USB ports but no USB camera support. :disappointed: There are only a few reasons I can think of for this. The CPU might not be powerful enough to process the video bitstream fast enough, the native USB camera host (which runs in userspace) requires to much RAM at runtime to run smoothly, it is to difficult to compile the native host for the target architecture (which it shouldn't be), or it was a vendor's distinct marketing decision.

After looking at the diagram, to me it seems like the device has been primarily designed and built for processing analog video signals. More specifically, the digital board seems to only be able to control a separate analog muxer than actually process the video signal, like it is required for digital USB cameras.
