### ISSUE TITLE
Impossible to create tags.

### ISSUE THREAD

**Issue by filipca** [mapillary/mapillary_issues#2883]
### Basic information
* Platform: ` `Web`
* Version: `Windows 10...` 
* System/Browser: `Chrome...`

### Steps to reproduce behavior

 1.
 2.
 3.

### tag created and green dot remains

...

### green dot disappears

...

### Additional information

... The error happens since one week approximately.

**Comment by ulikoehler** [comment]
I created some tags yesterday using Chrome on Linux. It takes some time (spinning wheel in the gray tag on the left) until it is created on the server, but it seemed to work. I only created two, however.

I experienced a similar issue last year when the tag feature was freshly introduced. Maybe its due to server load.

**Comment by gyllen** [comment]
@filipca @ulikoehler We had an error in the backend from upgrading our database (we just made a major upgrade so let us know if you see anything else)

Tags should be back to working normally now again. And tags that you created and could not see should now be added.
