### ISSUE TITLE
Mapbox Streets base map outdated

### ISSUE THREAD

**Issue by GITNE** [mapillary/mapillary_issues#2885]
### Basic information
* Platform: `Web`
* Version: *`any`*
* System/Browser: *`any`*

### Expected behavior
OSM changesets should become visible on the Mapbox Streets base map within about 24 hours.

### Actual behavior
No updates to the Mapbox Street base map for months.

### Additional information
For almost a year now the Mapbox Streets vector and raster map has not received any updates. I have noticed this after reviewing locations I have mapped in OSM months ago but are still not visible on Mapbox Streets. Do you know anything about it, or could you ping Mapzen to resume updates?

Vector maps is a really cool feature and I would love to see my latest OSM edits on Mapillary back again. It is somehow depressing to have spent a lot of time and effort using Mapillary imagery to extract map data but you actually cannot see the mapping result on the website. Sure, the OSM *carto* style is up to date but it is not a vector map. But what is more important, since the Mapbox Street vector base map is the default on the Mapillary website, it feels like Mapillary might be outdated and unmaintained. :disappointed: This is not the impression you would expect from Mapillary, especially to new people.

**Comment by gyllen** [comment]
@GITNE Thanks for reporting, we will look into what map source we are using. It might be that Mapbox changed something and we are using an old source.

@knikel Do you have any idea why the maps are not updating?

**Comment by majkaz** [comment]
@gyllen 
Mapbox doesn't update automatically any more - they are "confirming" the OSM changes manually, as far as I know. This means, that the map is severely outdated locally - they didn't include motorway opened in the last year, for example.
This isn't a specific problem of Mapillary, all maps using Mapbox suffer from this. The updating stopped sometimes around August 2017 - see for example [here](https://gis.stackexchange.com/questions/257401/mapbox-not-updating-from-osm) and follow the [twitter link](https://twitter.com/Anonymaps/status/913812009547902978).

**Comment by GITNE** [comment]
@majkaz Thank you for investigating.

Well, I understand the reasoning of Mapbox to only accept approved changesets, especially for QA reasons. However, IMHO this causes a multitude of problems in the long run. For one, the OSM database and Mapbox's data set will eventually diverge to a point where changesets will become impossible to merge into Mapbox's data set, simply because the OSM database will have changesets based on previously disapproved changesets by Mapbox. For second, I do not think they can keep up with the rate of changesets coming in, unless they want to employ some sort of AI (OSMCha seems to hint at that). But, even then they will need to have **extremely** **high** true positive and **extremely** **low** false negative rates (far better than those of Mapillary's latest blur AI). Call me an uneducated barbarian but I do not believe the technology is there yet because I believe you are going to need *strong* *AI* to assess complex changesets, where you have to pull data, information, and experience from different sources, like aerial imagery, street level imagery, website data, and legal information to validate changesets. Not to mentions situations where any other data for cross referencing is either obsolete or does not exist, like when local users enter survey data.

Anyhow, this situation kind of sets back Mapillary too. Yeah, you can use the OSM carto layer but this is not the real deal, especially if you use imagery hosted on Mapillary to improve OSM. Additionally, whoisonfirst seems to be affected by this policy and technical change too, e.g. I cannot find POIs I have added in OSM on whoisonfirst. So again, this breaks the user experience on the Mapillary web app even more.

@mapillary I hope you can resolve this issue soon because the current situation means stagnation.

**Comment by gyllen** [comment]
@GITNE @majkaz Thanks for digging into this. I'm happy for any suggestions here on how we would be able to make life easier for you.

@GITNE Regarding WOF we actually host that layer ourselves now (since mapzen shutdown) and we should be able todo periodic updates directly from the WOF source. You have any recommendations on how often?

**Comment by GITNE** [comment]
@gyllen @gyllen I have just discovered that the vector Mapbox style base map keeps up with OSM again. Yey! :+1: Thank you! :joy: Looks like the update interval is 24 hours. Is it?

> You have any recommendations on how often?

Hmm, I think I am not the right one to ask about this because I have never run an instance of WOF, so I do not know what the performance pressure from OSM might be. The only thing that I would suggest is to update WOF in sync with the map (but you probably already know this and do it anyway), which currently looks like every 24 hours to me.

Besides that, IMHO better geocoding indexes or geocoding concepts exist than WOF. To say the least, I think that WOF is conceptually seriously flawed. For one, it *does not forget*. Which in the context of creating a historic geolocation archive might be okay but in the context of OSM edits is not. There are also other issues that make it little suited for the purpose of the Mapillary web app. But, this is a topic of its own. :wink:

**Comment by gyllen** [comment]
@GITNE Interesting, what would you recommend instead of WOF. What is great for us and WOF is that we actually do have a constant `id`. Which makes it possible for us to link to ids internally.

**Comment by GITNE** [comment]
I see. It is difficult to give a complete answer here but I will try to do my best and I hope I understand your question.

I would probably go for Nominatim and use ISO 3166 codes as identifiers. Since I do not know what level of geographic granularity you are aiming for, I suppose that for monthly stats ISO 3166 should do a good enough job. ISO 3166 code queries work very well with Nominatim, although I am not sure if the first result is guaranteed to be the correct one because it is somewhat similar to a *full text* search. For better results on ISO 3166-2 queries one should search using the `countrycodes=`*`ISO 3166-1 code`* URL parameter. Nominatim is also capable of returning GeoJSON results which should suit you. For any more granular stats queries it might be best to compute those on the fly. If an object returned by Nominatim is not a closed way, a multipolygon relation, or a boundary relation then just drop it.

Nominatim has also support for a `place_id` (not `osm_id`) but AFAIK it is not guaranteed to be unique to a place indefinitely nor to migrate with any place name (including name changes). `place_id` is more like a reference to query results.

Alternatively, you can use an Overpass query to search only—and only—for ISO 3166-1 or ISO 3166-2 (not to be confused with ISO 3166 alpha-2) code tagged boundary relations. The OpenStreetMap database still lacks a few ISO 3166-1 and ISO 3166-2 codes but it is mostly complete.

Should you *really* require numerical ids only then you may want to consider ISO 3166-1 numeric. However, these are UN statistical areas which may not be identical to administrative or political boundaries. Besides, it should be fairly easy to alias any string to any numeric id in any database system, so ISO 3166-1 numeric is not really an option.

**Comment by gyllen** [comment]
The reason we use WOF is really for the ability to get shapes all the way down to very low administration levels, such as a county it also have a license that fits us well.

Whats great with WOF is that we can import all the boundaries in our database (elasticsearch) and then use these indexed shapes to search against and since the ids are consistent its very easy to reference.

@knikel @GITNE I am unsure that Nomatim would work in our case actually.

You could pretty much search for any geostat you want here https://www.mapillary.com/app/geo-stats?menu=true

I am open to hear other clever solutions to this. Also one thing I think that we are suffering from is actually not so much the shapes as the reality that we have to simplify them to even be able to use them for search. Australia is one of the more troublesome ones.

**Comment by GITNE** [comment]
> The reason we use WOF is really for the ability to get shapes all the way down to very low administration levels, such as a county

You can do that with Nominatim too, including GeoJSON shapes.

> it also have a license that fits us well.

Should you have any problem—technical or legal—querying the instance on nominatim.openstreetmap.org, you can always run your own instance. Of course, I have no clue what Mapillary's user query statistics may be but I suppose that they should not pose much of a burden on OpenStreetMap's Nominatim instance. Well, you can always talk to the nominatim.openstreetmap.org admins or sponsor them with bigger/better hardware. :wink:

> Whats great with WOF is that we can import all the boundaries in our database (elasticsearch) and then use these indexed shapes to search against and since the ids are consistent its very easy to reference.

As already mentioned, you can import shapes via Nominatim too. I have been searching Nominatim's documentation for additional information about its `place_id` field but have not found anything new. Apparently, if you want to know more about it you will probably have to ask the Nominatim maintainers. But, I would be surprised if the `place_id` is guaranteed to be unique to a place indefinitely. However, this just me assuming based on the little documentation that is out there.

> @knikel @GITNE I am unsure that Nomatim would work in our case actually.

Why? So far, I have not really seen anything that could not be solved. Some glue code may be required but it looks doable to me (maybe I am just missing something). 

> You could pretty much search for any geostat you want here https://www.mapillary.com/app/geo-stats?menu=true
> 
> I am open to hear other clever solutions to this. Also one thing I think that we are suffering from is actually not so much the shapes as the reality that we have to simplify them to even be able to use them for search. Australia is one of the more troublesome ones.

Well, this is a topic of its own. I do not know exactly what you have to put up with but IMHO I would almost always strongly advise against simplifying border shapes simply because borders are what they are—sometimes complex sometimes simple. Sooner or later, simplified boarders will almost always lead to new problems. Usually, the impact of simplified shapes of natural features is negligible (because these often do not have clear contours) but it often proves problematic with man made borders (which are geometrically precise).
The main reasons why I suggest Nominatim are:
* It works
* Is fast
* Is structured
* Is tightly coupled with OSM (no additional abstraction layer), hence users can even search for OSM features not just place names
* It is up-to-date (at least the instance on nominatim.openstreetmap.org is)
* Many other commercial and non-commercial services use it (e.g. Graphhopper, and AFAIK even uses the aforementioned public instance)
* It is *relatively simple* (conceptually and implementation wise)

**Comment by gyllen** [comment]
@GITNE Thanks for long and insightful answer

There are a couple of things we need to look into

1. How can we pull a million shapes? In reality I think it would be better if we exported directly from OSM. For search to work we do need the data in our database and not having to download it on every query (this would be really expensive and time consuming, since data is really big)
2. The ODbL license has the possibility to taint our databases (we are always super careful of how we use OSM data (as we should))
3. Simplification, this is a tricky one, we have not yet found a way for elasticsearch queries that works well with none simplified shapes.

**Comment by knikel** [comment]
Regarding the core issue, it looks like Mapbox started updating the map again! 🎉 

*Thanks a lot to everyone involved in this discussion* ❤️. We used to use it back in the day, a.k.a. the first prototype of Mapillary for localtion lookups. All in all it was good besides temporary timeouts. WOFs (and their `id`'s, especially for countries, regions and cities) are pretty deeply integrated in our current system, so we won't be ripping out that part of our codebase any time soon. However we'll keep in mind the Nominatim alternative in context of querying against shapes they have and research a possible usage. Maybe there is a nice way to _glue_ wof id's against Nominatim's data.

Anyhow, since `mapillary_issues` is no longer an active repository I'd like to close this issue. As I said, we would check out Nominatim with regards to shortcomings of WOFs and we track that internally. However if there is anything else you'd like to discuss with regards to this, I'd suggest creating a topic on the forum. Thanks!
