### ISSUE TITLE
Uploader not working

### ISSUE THREAD

**Issue by houska2** [mapillary/mapillary_issues#2890]
### Basic information
* Platform: `web`
* System/Browser: `Linux Debian, Chrome 65.0.3325.181`

### Steps to reproduce behavior

 1. visit https://www.mapillary.com/app/uploader
 2. application not working (see screenshot)

![1c577423d0049818422122afe5fb877f307d2122](https://user-images.githubusercontent.com/38128730/38413851-297578a6-398d-11e8-9d39-a30c94736c95.png)

**Comment by katrinhumal** [comment]
@houska2 Thanks for reporting! I'd like to ask some more information.

1) How long has this been going on? If it was the first time you saw this when you reported, can you please try again and see if the issue repeats?

2) How many images and what kind are you trying to upload? Could you attach a couple as a sample?

3) What happens when you do a hard refresh?

**Comment by houska2** [comment]
Hi, 
it works now \o/ 

I tried hard refresh, I even install new version  of Chrome and still saw the error. 
I couldnt upload anything - there was no button "Browse files" (see picture) 

Thanks for your time and your work on mapillary :)

**Comment by katrinhumal** [comment]
@houska2 Great that it works! We've been updating our systems so that has caused some services to temporarily fail at some point or another. This should happen less and less until we finish the work, after which everything should be faster and better. :)
