### ISSUE TITLE
JOSM plugin shows more traffic signs than Mapillary web viewer

### ISSUE THREAD

**Issue by voschix** [mapillary/mapillary_issues#2907]
### Basic information
* Platforms:  `Web`;  `JOSM plugin`
* Version: `up-to-date` 
* System/Browser: `not relevant`

### Steps to reproduce behavior

 1. open Mapillary web interface on a location with Mapillary traces
 2. enable traffic signs
 3. Open the same location in JOSM with the Mapillary plugin active

### Expected behaviour

Both views show the same Mapillary traces and detected traffic signs

### Actual behaviour

Both views show the same Mapillary traces
The JOSM plugin shows more traffic signs (and some icons are different)

### Additional information

[sample location](https://www.mapillary.com/app/?lat=45.386572581527304&lng=11.894833784803723&z=18)

![traffic signs mapillary](https://user-images.githubusercontent.com/11076112/39803788-6caa21b8-5372-11e8-8ca9-abe1d04a0ade.jpg)

![traffic signs josm plugin](https://user-images.githubusercontent.com/11076112/39803800-733136b6-5372-11e8-9504-8b9889c7494d.jpg)

...

**Comment by octanebaby** [comment]
Thanks for reporting this @voschix . We recently released an update on Mapillary.com which only displays signs that are seen in more than one image.  We did this based on feedback that there was a lot of noise in the data when signs only found in one image were shown.  

While we have not rolled this change out in the ID integrations, I am interested in your thoughts on whether the same change is useful in JOSM.  Since JOSM is used specifically for editing OSM, maybe it's still useful to see which images contain signs, even if it's only one?  We do not maintain the JOSM plugin but can pass on your feedback either way.

**Comment by voschix** [comment]
Hmmm. On iD I see _much_ less traffic signs than on the Mapillary web interface
![image](https://user-images.githubusercontent.com/11076112/39945817-1fcd7358-556c-11e8-9511-9d2d2f652a36.png)

Regarding the JOSM plugin, I miss the possibility to see where in which pictures the signs turn up. 

I am not yet  often using the signs in my mapping, so on the filter I really don't have an experience-based opinion. My gut feeling, however is that the filtering my be a good idea, at least as long as you have many pictures in an area. This may be different when you have, say only one trace with lower picture taking frequency. In that case you may be throwing away valid detections. But this is a theoretical assumption, not experience.

**Comment by octanebaby** [comment]
Thank you, I assume you mean the feature on Mapillary where you click on the icon on the map, and it shows you different pictures with the detection. 

We do not maintain the JOSM plugin but can see about passing on this type of feedback.   (There is also the repo here as you run into more issues https://github.com/JOSM/Mapillary)
