### ISSUE TITLE
Unable to Activate ArcGIS Pro Add-In

### ISSUE THREAD

**Issue by darrencope** [mapillary/mapillary_issues#2924]
### Basic information
* Platform: ArcGIS Pro
* Version: 2.0.1
* Mapillary for ArcGIS Pro Version 0.8.3

### Steps to reproduce behavior

 1. Download Mapillary Add-In for ArcGIS Pro
 2. Install Mapillary Add-In for ArcGIS Pro
 3. Verify under Add-In Manager that "Mapillary for ArcGIS Pro" appears
 4. Click the blue Project Tab
 5. Click Licensing...

### Expected behavior

 * Scroll down to External Extensions
 * Put a check in Enabled next to Mapillary for ArcGIS Pro.

### Actual behavior

The "External Extensions" section is not visible at all, so Mapillary cannot be activated.

![pro1](https://user-images.githubusercontent.com/3187388/40979815-e4f6206c-68a4-11e8-8f8a-1ae28116a1d3.png)
![pro2](https://user-images.githubusercontent.com/3187388/40979816-e51a130a-68a4-11e8-8bab-1f7b8eb2dca6.png)

**Comment by katrinhumal** [comment]
@darrencope Thanks for reporting!
@cbeddow Can you please help with this?

**Comment by cbeddow** [comment]
@darrencope When you open an ArcGIS Pro project, are you able to access the Mapillary tab, activate coverage, and use the Select Image tool?

Also, can you tell me what operating system you are running?

**Comment by darrencope** [comment]
@cbeddow No, when I open a project, the Mapillary tab is greyed out, with the exception of the "Mapillary.com" "MAGP Help" and "Feedback" icons. However, even though these icons appear active, they do nothing when clicked. In fact.. I just tried again, and after clicking those three icons, they then became greyed out.
![maillary1](https://user-images.githubusercontent.com/3187388/41046709-e35b331c-6978-11e8-8d67-43f02474419f.png)

**Comment by cbeddow** [comment]
@darrencope some steps I want to ask you to try, so I can isolate this:

1.  Open ArcGIS Pro, and open an existing project

2. Proceed to the project, open the Mapillary tab, toggle coverage on, and attempt to select an image

* If this functions for you, then please let me know at this point. Otherwise please continue:

3. Close ArcGIS Pro, restart the application, and then re-open a project. Repeat step #2 above.

* If the add-in is now working, once again please let me know that it worked at this step.

4. Click the Project tab at top, and go to Licensing. Under External Extensions, remove the check from the Mapillary add-in's enabled checkbox, then add it again, and log in again to authorize.

* Please confirm yes/no if you receive an error message at this point about being licensed for the current ArcGIS Pro version.

5. Return to your project, and repeat step #2 above. 

* If Select Image works at this point, please notify me that this step worked.

6. Click the Project tab, go to Add-in Manager and please confirm it Target Version reads 2.0 or 2.1 (specify which)

* Send me the confirmation of the target version, despite any failure or success above!

Going through these steps will help me to isolate where the bug lies, and I hope will get the add-in working for you as soon as possible! This sounds like a unique book so may take some days to implement a fix and update.

**Comment by darrencope** [comment]
@cbeddow 

* Sorry, I didn't answer re: operating system. I'm running Windows 7 Pro SP1.

2&3&5. I am unable to toggle coverage on--that button is always greyed out (it is only the buttons I mentioned which are NOT grey out, but even they do not function when clicked, then subsequently grey themselves out.)
4. as per the original bug report, the "External Extensions" section is not visible at all, so Mapillary cannot be activated.
6.  Target version reads 2.0

**Comment by cbeddow** [comment]
@darrencope I've seen this error before, but I am not sure how to fix it--the best we've seen is to remove the widget, restart the computer, open ArcGIS again, and try from scratch. I'm consulting with Esri on why this would not be visible to you otherwise.

**Comment by darrencope** [comment]
Hi @cbeddow  I fully uninstalled the add-in (and another add-in as well, in case there was a conflict), rebooted, and reinstalled. The same issue is still present.

**Comment by cbeddow** [comment]
Hi @darrencope still no solution on this yet. I've created an internal issue for the developers to try debugging here.

**Comment by cbeddow** [comment]
@darrencope please follow up with me via email at christopher@mapillary.com and I'll send you this week's updated installer. It's typically acquired through the survey, but I'll get a direct link on a private message.
