### ISSUE TITLE
too many emails

### ISSUE THREAD

**Issue by dr2okevin** [mapillary/mapillary_issues#2935]
If I upload a video I would except to get one email after the processing is done. 
But I get every hour a mail that says that around 10 Images have been published. That is annoying.
![mapillary-mails](https://user-images.githubusercontent.com/1845792/41479507-aae411de-70cb-11e8-907c-04641571b659.PNG)

**Comment by Kaldea** [comment]
Hi!

Has this been happening only recently, or with all of your uploads? If so, how long?

**Comment by dr2okevin** [comment]
I think i got always more than one mail, but with the last 3 or 4 uploads, I got a lot more than before.
my last upload is around one week old, an I still get emails.

**Comment by pbb72** [comment]
This is a commonly reported issue (eg #2909, there have been more but I can't remember the exact wording so I can't find them), not only for videos, and not only recently. I can get over 50 emails in one day, sometimes even just for ONE photo being published.

![image](https://user-images.githubusercontent.com/1436366/42134477-c5a48cf6-7d3c-11e8-8925-a2e28a7194ad.png)

Often, the reported photos aren't even published, when I click the link in the email I get a message on the website that the photo can't be found and is probably still processing.

I have requested before to only send a notification when a whole sequence has been published (ie, accessible on the website and visible on the map), but it appears that is not possible because of parallel processing. (Which is weird, because sequences only become visible on the map when all photos have been published.)

**Comment by gyllen** [comment]
This will improve after our latests database upgrade, we are currently working on recovering. After that the goal for this quarter is that _all_ images should be processed within 30 minutes leading to much less emails.
