### ISSUE TITLE
Traffic sign triangulation ignores focal length

### ISSUE THREAD

**Issue by GITNE** [mapillary/mapillary_issues#2938]
Maybe I am wrong but I am under the impression that in contrast to OpenSfM the traffic sign triangulation does not factor in the focal length (if available). This is unfortunate because this would lead to far better triangulation results than currently possible.

Just for simple testing purposes, I have uploaded overlapping photos with varying `FocalLength` EXIF values, and correct `FocalPlaneXResolution`, `FocalPlaneYResolution`, and `FocalPlaneResolutionUnit` EXIF fields. And although all detected traffic signs in these photos have been basically correctly triangulated respective to the camera position, unfortunately none have been positioned at the correct distance from the camera position. If you need any examples, just ping me.

**Comment by paulinus** [comment]
Hey @GITNE, thanks for your interest in the internal of placing signs from images.

We do use the focal length to triangulate signs. The process works as follows.

1. Using the metadata in the EXIF (including camera brand and model, focal length, and others) we get the best initial camera calibration we can guess.

2. We run SfM reconstruction algorithms that align the images to each other in 3d.

3. The resulting camera positions and calibrations are used to triangulate the traffic signs.

About varying focal lengths, in point 1 we do our best to find the correct calibration to use for each image. This is sometimes difficult because the information on the EXIF might not be complete enough for us to find the best calibration. Our preference is to always get the images with the default focal length of each camera.

Please, do share a link to your varying focal length experiments. I'll have a look at how they worked.
Thanks!

**Comment by GITNE** [comment]
@tobias-o @paulinus Btw, my latest sequence [`OA0zfe2iK_buxKUYVVWY1g`](https://www.mapillary.com/app/?lat=50.84783798736569&lng=7.985187023209733&z=17&signs=true&pKey=uSmsUKd7b49Y_lgBn4MIww) does not show detected traffic signs on the map. Three :warning: days have passed since upload. So, I am assuming something must have gone wrong there because all other traffic signs show up on the map thus there is no problem with the viewer.

**Comment by paulinus** [comment]
@GITNE the traffic signs on that sequence are online now. We are in the middle of a worldwide rerun of traffic sign detection which might have caused the delay. Sorry for the inconvenience.

I'll keep track of the offset sign that you reported. Need to investigate what happened there.

I'll also investigate the reading of the focal length metadata. I've tested opensfm and it does not read any focal length from the EXIF even if ExifTool can find it.

In general, though, I would recommend using cameras with fixed focal lengths since they will have more chances of getting a proper calibration. We use images from other users using the same camera to do calibrations so, the more common the camera is, the more chances of it having a good calibration.

I'm going to close this issue since we are setting down mapillary_issues. Please, feel free to continue the discussions in the forum, thanks
