### ISSUE TITLE
Export GPX files

### ISSUE THREAD

**Issue by Stalfur** [mapillary/mapillary_issues#388]
I would like to be able to export my sequences to OpenStreetMap GPX tracks. Could this be done as an automatic feed if I check an option in Options? Could I manually pick sequences to import?

OSM API: http://wiki.openstreetmap.org/wiki/Api06#GPS_Traces

**Comment by jesolem** [comment]
@elopio Where would we push them?

Anyone can download and submit but is there a place for Mapillary to dump trace data?

**Comment by elopio** [comment]
@jesolem I'm not sure I'm getting your questions.
Just upload them to osm: http://wiki.openstreetmap.org/wiki/API_v0.6#Uploading_traces

As you said, I could do a script that downloads from mapillary and uploads to osm, but I would prefer if the upload to mapillary triggers and automatic upload to osm.

**Comment by de-vries** [comment]
>I could do a script that downloads from mapillary and uploads to osm, but I would prefer if the upload to mapillary triggers and automatic upload to osm.

I can see a problem with that. Gpx tracks are seen as a form of raw data in osm and it is not desirable that you edit your traces before uploading to osm. Traces in Mapillary are quite often heavily edited and thus shouldn't be uploaded to osm.

The danger is that when you upload a Mapillary trace that's edited with the help of a osm background, someone will later us that trace to improve the osm data. And voilà, you've created a circle jerk.

**Comment by elopio** [comment]
ah, that's interesting. So what we should upload to OSM is a raw gpx. Can we have access to that?

**Comment by de-vries** [comment]
@elopio You could run a separate gps logger on your phone. I do that too, just so I don't loose gps connection when close the app.

**Comment by elopio** [comment]
@de-vries, that's what I do. I have osmand running at the same time as mapillary. I was looking for a way to avoid it.

**Comment by jesolem** [comment]
For most users, the gpx would be the "raw" unedited track. However, there is no way to know from our end if the user edited the track before uploading (edits on Mapillary we can know of course).

**Comment by Stalfur** [comment]
Uploading from app, those should be unedited tracks?

**Comment by jesolem** [comment]
@Stalfur yes, but we cannot reliably tell if the photos come directly from the app or if someone copied to a laptop, edited and then uploaded. For most users there are no edits though.

**Comment by Ainali** [comment]
@jesolem Yes, that is why the upload option should be done from the app itself. Because there are no manual way to import images to the app, we can be sure that it is the raw gpx. No need in adding this to the web interface.

**Comment by jesolem** [comment]
@millenbop Do you think we could add this as a setting in the app and then at upload we submit the traces directly to OSM (link above)?

**Comment by HolgerJeromin** [comment]
These public GPS traces are now available as a overlay on osm.org
Would be cool if mapillary app would lower the barrier to submit

**Comment by GITNE** [comment]
> Because there are no manual way to import images to the app, we can be sure that it is the raw gpx.

@Ainali This is not true. Sure, there is every way to modify photos taken by the app and also to let the app upload modified photos.

Please, learn a bit about the basics of computational theory before making any general statements. There is no way to guarantee the origin or quality of raw data. However, ways do exist to ensure data integrity with a certain probability once it has been created but this is a different story. Hence, there is no way to guarantee that any data creation process will not be tainted, especially on remote devices where unrestricted physical access is the norm.

> Gpx tracks are seen as a form of raw data in osm and it is not desirable that you edit your traces before uploading to osm. Traces in Mapillary are quite often heavily edited and thus shouldn't be uploaded to osm.

@de-vries It is true that raw GPX traces are desirable for the OSM repository. Yet, this repository is not safe from users editing their tracks before upload either. So, your argument is understandable and portrays a desirable ideal situation but this is not how open repositories work. Additionally, no gate keeping mechanism can be devised to tell tainted/modified data apart from raw data. Assuming you have an existing repository of guaranteed untainted raw data then statistical analysis on incoming data, based on that untainted data, *can* give you some hint as to the probability of the incoming data being tainted. But, even this will not work in every case. We just have to accept the fact that open repositories have raw untainted data as well as modified data, that is data of varying quality in many dimensions. However, I do think that one should be careful before implementing any automated exports of Mapillary sequences into the OSM GPX repository, even though most of them are probably raw untainted data indeed.

**Comment by Ainali** [comment]
@GITNE That is so obvious I can't believe you chose to be rude rather than hesitate if you got me right. Of course I meant that there is no such way from within the app interface itself. There is no need to care about users that want to sabotage OSM because they can just [upload ](https://www.openstreetmap.org/trace/create) their fake gpx files to OSM without bothering to put it through the Mapillary app. There is only need to make sure it doesn't happen by mistake from a user with good intentions.

**Comment by millenbop** [comment]
@jesolem yup should be possible

**Comment by GITNE** [comment]
> That is so obvious I can't believe you chose to be rude rather than hesitate if you got me right. Of course I meant that there is no such way from within the app interface itself.

How can anyone be rude by simply stating facts? The point is that it is a secondary issue how and where Mapillary enables users to automatically export GPX traces from sequences to OSM. I was just trying to make clear that the reasoning in your statement is flawed. Just because you (supposedly) cannot import photos into the app and upload them via the app doesn't mean that it is safe to add an auto-export option to the app but not on the web page. The question to be considered here is if Mapillary should export *all* sequences automatically, by default, or at all because it could be perceived as *polluting* or *flooding* someone else's repository in the worst case scenario, or sharing open data in the best case scenario.
Any possible reason to assume it may be safe to add an auto-export option, regardless whether it is in the app or on the web page, may be the basic assumption that it is off by default and users understand what they are doing when activating this option.

Besides, there are multiple ways to implement this feature. The best solution would probably be to have all auto-exported sequences be (possibly anonymized) put into one account on OSM's side, something like `mapillary_gpx_export` or the like. This way, if something goes wrong on Mapillary's side it should be easy to remove or at least *hide* these exported GPX traces from OSM mappers until issues get resolved.

There are some legal issues to be considered here as well because in this case Mapillary may be sharing users' data with a third party.

> There is no need to care about users that want to sabotage OSM because they can just upload their fake gpx files to OSM without bothering to put it through the Mapillary app. There is only need to make sure it doesn't happen by mistake from a user with good intentions.

So, it is okay if it happens by mistake of a malicious user? :laughing: Any user's intentions do not matter here. Data quality is what matters.

**Comment by Ainali** [comment]
Wouldn't it be better to associate those uploads with these peoples OSM-accounts? That way it is easy to block any malicious user without affecting all other Mapillary users. And by forcing them to connect their accounts, they themselves have shared their data with the third party, and can be appropriately attributed in the OSM community. So it shouldn't be all uploads by default, but only the uploads for the users that actively choose to share the data. I am also open to the solution of not making it a global setting per user, but that the user should actively select it for each upload. It will still save the user plenty of work (and reduce the risk of mistakes on the way) compared to the existing workflow

**Comment by polarbearing** [comment]
> There is no need to care about users that want to sabotage OSM because they can just upload their fake gpx 

The discussion here is not about 'sabotage' or malicious users. The problem, as pointed out before, is that user might have 'snapped the images to the road' or straightened their tracks before uploading. That is useful for mapillary images, but not for correcting roads in OSM, or aligning aerial imagery in OSM editors, for which the raw data are needed. Snapping traces to roads is undesirable for OSM data.

**Comment by Ainali** [comment]
@polarbearing That is why I only talk about uploading from the app at the same time you originally upload the images. In that work state nothing have been snapped yet.

**Comment by polarbearing** [comment]
> In that work state nothing have been snapped yet.

And this is what you don't know. You are extrapolating your own workflow to others. 
I was reviewing the pictures on a desktop machine with the phone mounted as a filesystem, before uploading them to the server with the app.

**Comment by HolgerJeromin** [comment]
This upload should definitely be with the users account (authorized via oauth) and not with an generic osm account. 
Also because for my osm trace count :-)

**Comment by polarbearing** [comment]
> I would love if it could be done automatically

It must not be uploaded automatically. 

If there is an upload mechanism, it should be voluntary and only triggered on individual request per sequence. There are sequences that are good for mapillary, such as walking around an object on unpaved ground, that make no sense as OSM trace. 

That button should have a warning _not_ to upload edited/snapped traces. I am not worried about malicious uploads, there is little gain from it, and there is no mechanism to prevent fake traces uploaded to OSM directly. I am just worried about new and/or uninformed users, and traces not taken along a mappable linear feature.

**Comment by Skippern** [comment]
It would be a nice feature to have the GPX of sequences automatically be uploaded to ones OSM profile, though I am currently running scripts that does that prepares the GPX of the sequences before posting to Mapillary, and posting these separately to OSM. I have not yet, but I can make a script creating GPX files from the EXIF of photos taken with the Mapillary app on my iPhone, so that GPX from these sequences also can be sent to OSM.

**Comment by polarbearing** [comment]
@Skippern - it should **_not_** be an automatic upload, as said in my previous post.

**Comment by GITNE** [comment]
> The pattern is
> `https://api.mapillary.com/v1/s/gpx/{sequencekey}.gpx`

Is this still online? I'm getting a 502 HTTP error.

**Comment by almostserena** [comment]
@elopio where exactly you can download the GPX data?
What profile page? on Mapillary or OSM? I cannot find any GPX box.
I need the gpx file to import in Mapbox for doing some visualizations.

Moreover the Advanced feature Download data allows to have an unstructured file of locations...



@Stalfur You can download GPX files for every sequence on your profile page. (Tick the GPX box top right)
The pattern is
https://api.mapillary.com/v1/s/gpx/{sequencekey}.gpx
so there should be easy ways to automate it if you don't want to get them from the website.

**Comment by jesolem** [comment]
The gpx api is now added to API v3. Will be added to the API documentation. 

Closing this and please continue any discussion on the forum
https://forum.mapillary.com/

**Comment by jesolem** [comment]
And the link
https://www.mapillary.com/developer/api-documentation/#sequence-in-the-gpx-format
