### ISSUE TITLE
Cannot rotate pics on the website

### ISSUE THREAD

**Issue by Ziltoidium** [mapillary/mapillary_issues#439]
some pics i took are 90° or 180° wrong. like here

http://www.mapillary.com/map/e/Rw52phuWEb27bn_ewZ34Cw

http://www.mapillary.com/map/im/4FsfyFoVo--pNSKANTZThA

there are even more in this sequence.  how can i rotate them?

**Comment by zibik** [comment]
Yes, I can click and report „the image is rotated“. But this does'nt work. I have reported some pictures a few days ago and nothing happened - these pictures are still unrotated. For example: https://www.mapillary.com/map/im/y7iWH1y20oktWvd1qMkvBQ

**Comment by ybkuang** [comment]
Hi all, thanks for raising the issue. Currently, we are not running processing to correct the rotation. But it is in our list to fix this in the near future. On the other hand, your reports will help us collect statistics on the wrongly rotated images, sorry for the confusion. 

Thanks!

**Comment by GITNE** [comment]
Over a year has passed now since this was an issue. Unfortunately, this **is** **still** a major issue. :-( Flagging still does not work as intended.

@Mapillary: People, you **really** need to get going! You are just too slow for the task at hand. This whole project has clearly outgrown yourselves. Perhaps even your competence to master such a project properly?
I am not say this to hurt or smear you. I am saying this because you really need to wake up and hear the call! There are a lot, and I mean really a lot of issues on your plate and most people get the feeling that you are not reacting adequately. I do not know how many potential users you have lost by now because of this. I hope not many. But, this is not what you should bet on.

**Comment by jesolem** [comment]
@GITNE Thanks for your great and detailed comments over the past days, here and elsewhere. Much appreciated. 

I think it is an overstatement to say that **most** people have the feeling we're not reacting to issues, but you have a point. Already ~6 months ago we recognized that we as a team were under-staffed to keep up with our growth. With this I mean, us adequately doing all the things on all fronts where we want to move forward. So we did two things: 1) prioritized, 2) I worked on securing some funds to be able to grow the team. 

1) Meant that some features of our platform suffered. Editing is the one I'm personally saddest we had to compromise, but rotating images is another.
2) Is done and we're right now growing the team in the areas where the pain points are the worst.

We have over the last months made deep and heavy work on our backend. For example retiring our graph database cluster and other necessary processes to be able to scale our data store. @peterneubauer and @gyllen also re-wrote the entire "change set" backend to be able to turn back editing and add more editing features. This is almost ready and we are working as fast as we can to get this out to everyone. 

A side note on rotating images: Rotating one single image has a lot of consequences that you may not think about at first. Rotation means we need to recompute all image features, all face detections, license plate detections, object detections. Then we need to recompute the 3D reconstruction in that area and potentially move nearby photos, recompute the 3D location of all objects located in the image and correctly propagate that information throughout the system. So until we have the new editing (change set) infrastructure in place it is incredibly difficult to do.

Bear with us, we're doing all we can. Because sometimes things take time does not mean we are not interested or capable, it just means that sometimes things take time to do right.

**Comment by GITNE** [comment]
@jesolem
Thank you for your clarifying and explanatory words. And, I am sorry if I tipped of some people with my last comment but the data speaks for itself.

> I think it is an overstatement to say that most people have the feeling we're not reacting to issues, but you have a point. Already ~6 months ago we recognized that we as a team were under-staffed to keep up with our growth. With this I mean, us adequately doing all the things on all fronts where we want to move forward. So we did two things: 1) prioritized, 2) I worked on securing some funds to be able to grow the team.
>
> 1) Meant that some features of our platform suffered. Editing is the one I'm personally saddest we had to compromise, but rotating images is another.
> 2) Is done and we're right now growing the team in the areas where the pain points are the worst.
>
> We have over the last months made deep and heavy work on our backend. For example retiring our graph database cluster and other necessary processes to be able to scale our data store. @peterneubauer and @gyllen also re-wrote the entire "change set" backend to be able to turn back editing and add more editing features. This is almost ready and we are working as fast as we can to get this out to everyone.

Your comments seem to make a lot of sense. However, I think this information should have been explained much earlier and more extensively on the blog first. Nevertheless, Mapillary obviously is still in need of help, not only financial but mainly in the form of man power. Please acknowledge your need for help and then do not hesitate to ask for help. I have seen too many people and organizations struggle for too long (and then eventually even fail) just because they could not acknowledge to themselves that they were in need of help. I am still convinced of Mapillary's mission to bring street level photos from around the world to the world (for whatever purposes). However, this crowd sourced service needs entirely different technical as well as social solutions than those found in other in-house commercial solutions. It needs working tools, lots of tools, in the hands of the community. Smartphone apps are good but do not suite everybody in the community. Plus, a crowd sourced project needs means of communication. Currently, Mapillary users and contributors have no easy means to communicate, except for posting a comment on some photo. This is not direct user to user communication. Dynamic social networks require direct communication channels.

> A side note on rotating images: Rotating one single image has a lot of consequences that you may not think about at first. Rotation means we need to recompute all image features, all face detections, license plate detections, object detections. Then we need to recompute the 3D reconstruction in that area and potentially move nearby photos, recompute the 3D location of all objects located in the image and correctly propagate that information throughout the system. So until we have the new editing (change set) infrastructure in place it is incredibly difficult to do.

Once again, thank you for the detailed technical explanation. You know, you do not need to go into so much detail. I suppose it would suffice if you would have communicated much earlier that you are creating a new backend infrastructure (some big thing) and work on the current infrastructure is put on hold. But, a statement like "Currently, we are not running processing to correct the rotation." seems to suggest that you could do it but you do not care indefinitely. Similar statements can be found on other issues.

**Comment by ybkuang** [comment]
@GITNE Thanks for the suggestions. We will consider this as feature for the future release. Sorry about the delay. 

mapillary_issues is no longer an active repository.
Let’s continue discussing features in our forum! We will import this issue as topic to the Mapillary Forum in the coming weeks. We’ll notify here once it’s been done. See you there!
