### ISSUE TITLE
'Request blur' not working in windows

### ISSUE THREAD

**Issue by ybkuang** [mapillary/mapillary_issues#526]
win7/ 8.1, opera/ chrome/ IE. 
@knikel can you help take a look?

(discussions here http://www.mapillary.com/map/im/UNbe1Z5Uw3z8K0iscbx9Mg)

**Comment by nomoregrapes** [comment]
Request blurring button not working on Linux(Ubuntu) with Chrome. Opening the console, this is the JS where it fails.
> POST https://api.mapillary.com/v1/b/request?key=EBvNQ2aIcrF999lv5vLi4w 400 (Bad Request) api.mapillary.com/v1/b/request?key=EBvNQ2aIcrF999lv5vLi4w:1
 > XHR finished loading: POST "https://api.mapillary.com/v1/b/request?key=EBvNQ2aIcrF999lv5vLi4w".

The bug needs to be fixed, but also some feedback should be given to the user when it fails. Even I (a web developer) just kept bashing my left-click button harder.

**Comment by peterneubauer** [comment]
Yup, we need to fix this, @knikel

**Comment by gyllen** [comment]
Can you try to login/logout?

**Comment by nomoregrapes** [comment]
In response to the request by @gyllen I have just logged out and back in. The request still fails with a hidden 400 error.

Ah, I have just tried it in an incognito window of Chrome and was able to submit a request. So there must be something cached on my computer. Back to my primary (not incognito window) I am still logged in but did a hard-refresh on several pages, that is to press Control+F5 and I presume the key page to do it on is on an "Edit blurring" page that you draw the red boxes on, e.g. http://www.mapillary.com/map/b/aJVaUP697soK7xjmbJEKuw

So this issue is fixed but may continue to affect some existing users until they clear their cache or do a hard refresh as explained.

**Comment by knikel** [comment]
I've been investigating this issue today, and it seems that often the cause for getting the 400 error is when one tries to request a blur for a photo which has a blur request pending. Additional feedback for the user has been added to cover for such scenarios.
