### ISSUE TITLE
Being a phone app

### ISSUE THREAD

**Issue by randy7771026** [mapillary/mapillary_issues#536]
Being a phone app only is bad enough but since the app store download wants me to upgrade to ios 7 or greater this leaves me out in the cold and I do mean cold right now in Chicago.  Great idea but need way to move images from my phone, imgur, fb, my xubuntu files or something besides in an app I cannot download.

**Comment by jesolem** [comment]
Hi @randy7771026 

We do support action cameras and manual upload of photos (from any camera as long as you have GPS in EXIF) too if you don't want to use an app. On both iOS and Android we have to use reasonable cutoff for supporting old versions because the APIs change a lot. 

iOS7 introduced a lot of API changes so going older than that is a lot of work. Latest numbers show iOS < 7 at below 4% of the user base. Not something a small team can support. Hope you understand.

**Comment by randy7771026** [comment]
Right now just undertanding that I myself and I cannoou are able to support
other devicest use it and I really want to as well as knowing a ton of
people that use an iPhone 4s and Imgur.  Not sure if the geo info needed is
preserved in the stream in my phone or when uploading to imgur.  I take a
lot of photos as I am out walking and rally want to incorporte crowd
sharing photo into my web app for those using the Chicago transit that have
differing abilities.
