### ISSUE TITLE
How exactly should be the metadata to manual uploads?

### ISSUE THREAD

**Issue by alexandre-mbm** [mapillary/mapillary_issues#571]
I suggest more documentation about this.

I want to colaborate using a old Android 2.3 smartphone. I initially thought about making a Python script to SL4A. After I accumulated knowledge to make a traditional app in Java. Today I know the Tina Time-lapse app and it works! [But the metadata are broken for the Mapillary's manual upload](https://github.com/mapillary/mapillary_issues/issues/538#issuecomment-70098142). 

I need to know how the Mapillary website expects EXIF metadata.

Seems alien but I do not use mobile phone. My uploads were did from smartphones of my brothers (Moto G). I use a old Sony Xperia X10i with Android 2.3 and without operator's chip. I think is interesting have a alternative for who uses Android unsupported by official Mapillary app, and I am
willing to discover this workflow, same if I need code a small app. Perharps the Tina Time-lapse app has solved the Android part, lacking only make a [Mapillary tool](https://github.com/mapillary/mapillary_tools/) to adjust the EXIF.

Show below full samples of **valid** EXIF metadata please.

I could look at the photos of the mobile app, but this issue can manage content for documentation.

**Comment by geomapper69** [comment]
@alexandre-mbm From the documentation in Mapilary tool - upload_with_authentication.py:

20 The following EXIF tags are required: 
21 -GPSLongitude 
22 -GPSLatitude 
23 -(GPSDateStamp and GPSTimeStamp) or DateTimeOriginal or DateTimeDigitized or DateTime 
24 -Orientation 

Here is an example output from exiftool:

ExifTool Version Number         : 9.80
File Name                       : example.jpg
Directory                       : .
File Size                       : 353 kB
File Modification Date/Time     : 2015:01:29 22:57:09+04:00
File Access Date/Time           : 2015:01:30 20:37:15+04:00
File Creation Date/Time         : 2015:01:30 20:37:15+04:00
File Permissions                : rw-rw-rw-
File Type                       : JPEG
MIME Type                       : image/jpeg
JFIF Version                    : 1.01
Exif Byte Order                 : Big-endian (Motorola, MM)
Image Description               : Created with OSnap! for iOS - Project: New Project 1
Orientation                     : Rotate 180
X Resolution                    : 72
Y Resolution                    : 72
Resolution Unit                 : inches
Exposure Time                   : 1/4785
F Number                        : 2.4
Exposure Program                : Program AE
ISO                             : 50
Exif Version                    : 0221
Date/Time Original              : 2015:01:29 15:36:16
Create Date                     : 2015:01:29 15:36:16
Components Configuration        : Y, Cb, Cr, -
Shutter Speed Value             : 1/4785
Aperture Value                  : 2.4
Brightness Value                : 10.89444879
Exposure Compensation           : 0
Metering Mode                   : Multi-segment
Flash                           : Off, Did not fire
Focal Length                    : 4.1 mm
Subject Area                    : 960 539 1056 475
Run Time Scale                  : 1000000000
Run Time Value                  : 453519043199916
Run Time Epoch                  : 0
Run Time Flags                  : Valid
Flashpix Version                : 0100
Color Space                     : sRGB
Exif Image Width                : 1920
Exif Image Height               : 1080
Sensing Method                  : One-chip color area
Scene Type                      : Directly photographed
Exposure Mode                   : Auto
White Balance                   : Auto
Focal Length In 35mm Format     : 35 mm
Scene Capture Type              : Standard
Lens Info                       : 4.12mm f/2.4
Lens Make                       : Apple
Lens Model                      : iPhone 5 back camera 4.12mm f/2.4
GPS Version ID                  : 2.0.0.0
GPS Latitude Ref                : North
GPS Longitude Ref               : East
GPS Altitude Ref                : Above Sea Level
GPS Img Direction Ref           : True North
GPS Img Direction               : 265.26
GPS Map Datum                   : WGS-84
XMP Toolkit                     : XMP Core 4.4.0-Exiv2
Date Created                    : 2015:01:29 15:36:16
Description                     : Created with OSnap! for iOS - Project: New Project 1
IPTC Digest                     : d41d8cd98f00b204e9800998ecf8427e
Image Width                     : 1920
Image Height                    : 1080
Encoding Process                : Baseline DCT, Huffman coding
Bits Per Sample                 : 8
Color Components                : 3
Y Cb Cr Sub Sampling            : YCbCr4:2:0 (2 2)
Aperture                        : 2.4
GPS Altitude                    : 11.6 m Above Sea Level
GPS Latitude                    : 40 deg 25' 34.21" N
GPS Longitude                   : 49 deg 54' 47.90" E
GPS Position                    : 40 deg 25' 34.21" N, 49 deg 54' 47.90" E
Image Size                      : 1920x1080
Run Time Since Power Up         : 5 days 5:58:39
Scale Factor To 35 mm Equivalent: 8.5
Shutter Speed                   : 1/4785
Circle Of Confusion             : 0.004 mm
Field Of View                   : 54.4 deg
Focal Length                    : 4.1 mm (35 mm equivalent: 35.0 mm)
Hyperfocal Distance             : 2.00 m
Light Value                     : 15.8

**Comment by alexandre-mbm** [comment]
@geomapper69 :keycap_ten:

**Comment by peterneubauer** [comment]
https://github.com/mapillary/mapillary_tools/blob/master/python/add_mapillary_tag_from_exif.py is now doing this for reference.
