### ISSUE TITLE
Automatically detect "constant" sections in images & tag them

### ISSUE THREAD

**Issue by rudolfmayer** [mapillary/mapillary_issues#579]
Some images taken while driving are quite bad because the camera is also capturing parts of the car interior/hood. If that portion of car-parts is too big, the image becomes less useful.

It would thus be great to tag those images (once #144 is done I guess) as of low quality. The algorithm could simply check whether in a sequence a certain portion of the image never changes (but the rest does), and then assume it is a part of the car.

**Comment by jesolem** [comment]
This is one of my pet complaints and something we have been trying different ideas for. My preference is to crop the photo to just remove the "constant" part. 

We're working on it...

**Comment by rudolfmayer** [comment]
Expansing a bit on this - cropping is fine, but an advance warning to the user would be the best; I am not sure whether the phone's hardware would allow you to do such an image processing, but indicating to the user that the way he mounted the phone contains parts of the car, the phone mount, etc., would be great while actually taking pictures.

**Comment by kaitu** [comment]
I often suffer from a "constant" reflection of the dashboard onto the windscreen, which falls on top of the usefull image. I hope the "constant" part recognition will not be too aggressive.

**Comment by jesolem** [comment]
@kaitu yes, and should only apply to removing things at the edges of the image

**Comment by paulinus** [comment]
Small update on this: since we started segmenting the images with semantic labels, we now know what areas of the images are covered by the dashboards, car hoods and such.

Because we are already finding and tagging these areas I'll close this issue.

The issue of hiding those parts in the viewer is still unsolved though. We have no plans on cropping the images but we could tell the viewer to start zoomed in a region of interest that does not include those parts. No specifics plans for that exist at the moment.
