### ISSUE TITLE
Improve "Select Traffic Signs" popup

### ISSUE THREAD

**Issue by pyrog** [mapillary/mapillary_issues#596]
![select traffic sign](https://cloud.githubusercontent.com/assets/2158081/6077569/9d34d2b8-adf0-11e4-99dd-8cde40d29ae2.png)

* some icons are missing
 * type-danger_animals
 * type-mandatory_go_left_or_straight
 * type-prohibitory_no_pedestiran_or_cycles
 * type-prohibitory_vehicle_weight_limit

* some logos are not well centered inside traffic signs (**type-danger**…)

* speed limits are not sort by… speed :wink: and in France we used also 110 km/h, 130 km/h

* could you also classify signs by [category](http://en.wikipedia.org/wiki/Vienna_Convention_on_Road_Signs_and_Signals#Road_signs) (speed, danger… in the same line)

**Comment by floscher** [comment]
> * some icons are missing
 * type-danger_animals
 * type-mandatory_go_left_or_straight
 * type-prohibitory_no_pedestiran_or_cycles
 * type-prohibitory_vehicle_weight_limit

These are issues with the icon-font. I've opened a pull request in its repo (mapillary/traffico#3).

> * some logos are not well centered inside traffic signs (type-danger…)

That's probably an interference between the CSS of mapillary.com and the icon-font, because http://traffico.io/examples.html looks better.

> * speed limits are not sort by… speed :wink: and in France we used also 110 km/h, 130 km/h

They are ordered by speed, but lexigraphically instead of numerically :wink:

**Comment by korst** [comment]
![images duckduckgo com](https://cloud.githubusercontent.com/assets/1449609/6094653/c4e5e812-af33-11e4-81dd-40e443065387.jpeg)
this is the one I've missed the most. (it is fairly common in the Netherlands)

**Comment by gyllen** [comment]
Merged traffico signs with mapillary
