### ISSUE TITLE
adjustable photo size

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#600]
Can you make the size of the photo box in the map view adjustable?

**Comment by gyllen** [comment]
I like this idea. This should be "fairly" easy now @knikel

**Comment by knikel** [comment]
@gyllen it's not so easy, but I think the new viewer solves this much better than adjustable control over a component which needs to be taken care of in a clever way on so many screen sizes.

@de-vries what do you think about the new viewer? http://blog.mapillary.com/design/2015/05/28/tiles-design.html We addressed this issue through having two distinct views, the photo and the map view, where either photo is the most important or map. I think in the long run this is a better solution, because most of the users are either interested in large photo or large map at the time. In the future we want to make this a standard layout for Mapillary and all the editing will happen in from within the right drawer.

**Comment by de-vries** [comment]
@knikel, I hoped it was as easy as making a text input box resizeable. But if it's that complex to implement and you're going to abandon the current map-view anyway, I wouldn't spent any time on this. And as you said this issue doesn't apply to the new viewer, so I'm closing this.

Speaking of the new viewer, it look great! I can see how a edit mode with a design consistent to the main-view will fit into this.
