### ISSUE TITLE
Compass Angle continue to count even when not pressed

### ISSUE THREAD

**Issue by glw** [mapillary/mapillary_issues#618]
Im experiencing odd behavior withe the +/- buttons, apparently opposite of issue #199 . Currently using chrome on windows 8, when holding down either button for an extended period of time then releasing, the counter will not stop. I found that if you click the same button again most of the time it will stop the counter. 

Suggestion: make the compass angle editable similar to location. so you dont have to press the button so many times.

**Comment by pbb72** [comment]
I've seen this problem also. In my case, it seemed to be connected to the number crossing over from 359 to 0 degrees (or the other way around). Since the +/- buttons are located directly after the number of degrees, the buttons move to the right when going from 359 to 0, and to the left when going from 0 to 359. If this happens while you have the mouse button pressed down, then Mapillary will afterwards not register the MouseUp event. You will have to click on the button again to make it stop.

**Comment by knikel** [comment]
Closing in favor of #199, will be fixed with the upcoming update of the editor.
