### ISSUE TITLE
Traffic sign feedback game. Some US signs appear blank in the list

### ISSUE THREAD

**Issue by jlevente** [mapillary/mapillary_issues#620]
When playing the sign recognition game, some US sign does not appear in the list. Both in Chrome and in Firefox. OS was Win7 when I tested. 
![image](https://cloud.githubusercontent.com/assets/7226757/6178426/c7e1785e-b2dc-11e4-8c8c-137dc482b2e7.png)

**Comment by floscher** [comment]
That is because mapillary wants to display signs that are either named different in the icon-font [traffico](/mapillary/traffico) or don't exist over there:

<table>
<tr><th>Name in popup on mapillary.com</th><th>Name in traffico</th></tr>
<tr><td>school_school</td><td></td></tr>
<tr><td>school_school_obsolete</td><td></td></tr>
<tr><td>warning_Y_roads</td><td>warning_<b>y</b>_roads</td></tr>
<tr><td>warning_loop_pretzel</td><td></td></tr>
<tr><td>warning_merging_traffic</td><td></td></tr>
<tr><td>warning_road_narrows_both<b>_sides</b></td><td>warning_road_narrows_both</td></tr>
<tr><td>warning_skewed_railroad_crossing</td><td>warning_skewed_railroad<b>s</b>_crossing</td></tr>
<tr><td>triple_2_reverse_curve</td><td>triple_2_<b>tra</b>verse_curve</td></tr>
<tr><td>warning_winding_road</td><td>warning_winding_road<b>_right</b></td></tr>
</table>

Part of this is fixed by mapillary/traffico#9:
* It renames `triple_2_traverse_curve` to `triple_2_reverse_curve`
* It renames `double_2_traverse_curve` to `double_2_reverse_curve` and removes `warning_double_reverse_curve` (both are the same)
* It renames `warning_skewed_railroads_crossing` to `warning_skewed_railroad_crossing`

**Comment by gyllen** [comment]
Thx @floscher awesome work with traffico.

**Comment by knikel** [comment]
With the pulling in the latest traffico update (and awesome help from @floscher!) and patching naming on our side this has been fixed.
