### ISSUE TITLE
Phone overheating to a dangerous degree

### ISSUE THREAD

**Issue by DaCor1** [mapillary/mapillary_issues#627]
I am using a HTC One M8 and I find that using Mapillary the phone gets painfully hot. 

I am charging the phone while using mapillary 

It would be good if mapillary would work with the screen turned off as this would resolve a lot of the overheating / battery consumption issues

**Comment by gyllen** [comment]
@peterneubauer Is this possible or can we close the issue?

**Comment by peterneubauer** [comment]
I think with the new version coming out the strain on the camera is much less. Still no turning off the screen from inside the app, but try out https://dl.dropboxusercontent.com/u/5925006/mapillary/android_prerelease/app-release.apk, you can always put the screen dimmer system wide.

**Comment by DaCor1** [comment]
Bumping this again. I'm using v1.20 of the android app 

I had numerous occasions where the frequency of photos being taken would slow to a crawl and each time I checked, my phone was dangerously hot. 

Later on, I set the air con in my car to as low as it would go, put on a hat, gloves and jacket (not kidding) and tried again. As long as the phone is kept cool, the timing is almost bang on 2 seconds everytime and there are few issues with crashes or freezing or errors but it makes for a VERY uncomfortable drive. 

Note, I have display dimmed as low as possible when running the app and am charging the phone at the same time.

**Comment by peterneubauer** [comment]
Wow,
that sounds like a very costly implementation of some of the camera
features like either live preview or image processing. What model are you
using?

**Comment by DaCor1** [comment]
Image processing is set to background, if I understand right, that's the
best option?

I'm using a HTC One M8

Believe me, I tried a number of different settings and the only thing that
ensured consistent capturing and fewer crashes was to cool the phone

I have an old spare Galaxy Nexus that I will try out to see how that goes

**Comment by DaCor1** [comment]
I used my old Galaxy Nexus today for a while and the app was way more stable and the phone barely warmed up at all. 

Once I switched back to the HTC ONE M8 the app was sluggish, slow to respond and within 15 mins the phone was very hot to the touch. 

There's something about the app that makes the M8 come under a lot of strain. 

Could it be the dual lens in the M8 maybe? There are 2 rear facing lens that work in unison

**Comment by peterneubauer** [comment]
Yeah,
that might be a reason, or the phone just not being tested that way (taking
a lot of serial single shots with saving in background). It's very hard to
know without actually profiling the hardware and code :/

**Comment by DaCor1** [comment]
No worries.

**Comment by pyrog** [comment]
Same issue with a Samsung Galaxy 5.
It was powered during Mapillary use, and fixed to the sun visor of the car.
The phone case was black, and the day :sunny:

**Comment by jaakkoh** [comment]
In short, I think it would be great if the app had an option to turn the screen off (within what ever time is set for turning the screen on).

That said, here are my experiences and some tips about this:

I've had very similar experiences with my S5. What I see is that the weather makes a huge difference. At latitude N12 deg where I live the situation is pretty horrible when ever it's sunny and the ambient temperature is between 30-40C, as in: nearly always. I have a laser thermometer and according to it the temperature of my dash is over 55C quite commonly. This is what the phone is receiving attached to the window!

On the other hand, when visiting DC at N38deg in winter I don't think I had any heating issues. What a surprise, eih?

It also matters what protective cover the phone has or doesn't have. I for example use a wireless charging back cover by default and it clearly increases the heating while mapillarying. I've noticed that I can actually remove the back cover while mapillarying without any issues since the phone is in a mount that keeps the battery in place.

Another trick that I've realized is that if the battery is 100% full when I start capturing the phone heats less. Again, not exactly surprising when one thinks about it. This is one more good reason to carry a fully charged extra battery in my bag as it often happens that somewhere along driving around and using the phone also in between mapillarying the battery level might drop -- or be far from full to begin with for natural reasons.

I haven't yet had enough experiences to see if using the map-in-camera maximized would reduce the heating. Not sure if I understand enough of what kind of stuff on the screen heats the phone more or less but my sense is that it matters. As also noted as a remedy the dimming of the screen to minimum brightness also works to a degree.

Hmm. The above would likely be better suited to the forum or a blog post or some other place. Oh well, better here than nowhere at least for now/starters.

**Comment by Caboosey** [comment]
Only workarounds that I did to keep my Samsung Galaxy S5 (SM-G900P) in white color in my 1998 Toyota Camry from overheating:
1. Have A/C vent or fan blowing into phone. Close or turn off  other vents if not needed for comfort . Note: My A/C usually set at coolest and fan level to 2 or higher on hot days. Normally just at 1.
2. Turn off Bluetooth and NFC. WiFi is ok to leave on and helps with geolocation. My Location setting is set to High.
3. Try to have phone anear 100% battery level prior starting mapillary.
4. Keep phone plugged up by wired connection to get power. Note: Make sure you get the right enough Amps. I use a USB 3.0 Micro Type B cable for my phone instead of a regular Micro-USB Type B.
5. Don't use the map-in-camera mode. 

Summary of settings while using mapillary:
Wifi: Enabled
Bluetooth: Disabled
NFC: Disabled
Location: Enabled
Location - Mode: High accuracy
Location - Improve accuracy - WiFi Scanning: Enabled
Location - Improve accuracy - Bluetooth Scanning: Enabled

Summary:
My setup has kept the Samsung Galaxy S5 from never or rarely overheating while in direct sunlight inside the car in Florida with outside tempatures running around 90 to 100 degrees Fahrenheit in summer.

**Comment by drkludge** [comment]
@jaakkoh [I started to map covered parking in the metro Phoenix area because of the extreme temperatures.  I parked in the shade of McDonald's when I was going next door to the smoke house.](https://www.mapillary.com/app/?focus=photo&pKey=v_Co11MZaME6c7qrpUA_hQ&lat=33.4955045&lng=-112.0121881&z=17) Some of @Caboosey's recommendations help. [If you have to use the defroster, then you will still have the same heat issues.](https://www.mapillary.com/app/user/drkludge?lat=42.3006722&lng=-112.2095569&z=17&pKey=a5bnzJbir6h_QHdAyxd0Vw&focus=photo)  At least I did.  Bring a jacket and run the air.  In the case, of the first picture, just run the air and hope that you don't need to charge your phone.

**Comment by Caboosey** [comment]
I also use time based mode instead of distance based to avoid overheating  since distance based settings is too long between photos on slower speeds and too quick at faster apeeds. It appears the app ignores the minimum delay set unlike previous versions of the app prior to v2.34 as references in issue #2013

**Comment by peterneubauer** [comment]
This should be done.
