### ISSUE TITLE
Android app Explore screen is empty, crashes app

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#660]
The first time you open the Explore screen, it's an empty white screen with only a caption showing. The second time you try to open the screen, the app crashes.

**Comment by kaktinjanka** [comment]
Confirm.
HTC Desire S (Saga) Android 4.04

**Comment by peterneubauer** [comment]
Any chance you can send me a log from the main menu?

**Comment by kaktinjanka** [comment]
Tried to save the log to dropbox but it was empty file. Then sent to hello@mapillary.com, hope it will not be empty.

**Comment by peterneubauer** [comment]
So, the problem is that the built-in browser that we (have to) use for an embedded web view is not supporting e.g. Angular.js, since it is not webkit or chrome-based. This is changed in later Android version, but for your Android 4.04, it is just too old. Sorry about that, I think I will change this to launch an external browser for older Android versions.

**Comment by peterneubauer** [comment]
Done, will be out in the next upgrade :)

**Comment by dymo** [comment]
@peterneubauer did you consider using [Crosswalk] (https://crosswalk-project.org/) then you can decide what webkit version is used.

**Comment by peterneubauer** [comment]
Yeah, but it seems there is a number of steps to do it, and it's really not a biggie to launch the external browser for older devices ...
