### ISSUE TITLE
Android app camera button unclear function

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#669]
It is very difficult to understand the functioning of the camera button.

It's a blue color, which is ambiguous, it doesn't say anything. (Red vs black or red vs green on the other hand convey some status information.)

Pressing the blue button shows a pause icon on the button. It is unclear if this means that the camera is now pausing, or if the button has to be pressed again to pause it.

The pause icon disappears automatically after a few seconds. This simply makes an incomprehensible situation even worse.

**Comment by knikel** [comment]
@pbb72 thanks for the feedback. In the next release the pause button becomes a big red button, to better reflect the state. Regarding colours we use green for single-shot and blue for auto-capture to distinguish between these two modes, but you are right, it's not communicated within the app in any way, besides the drawer.

Closing this, fixed in the next release.

**Comment by pbb72** [comment]
Thanks! I see the main confusion was actually caused by bug #682, but it's more understandable now.
