### ISSUE TITLE
HDR in the android app?

### ISSUE THREAD

**Issue by ireun** [mapillary/mapillary_issues#675]
Could you make that, i think pictures are better in this mode. SGS5 user here..

**Comment by iav** [comment]
Or, maybe, other way to void photos with light or blue sky - and dark-dark-dark all except sky.

**Comment by Peatsmoke** [comment]
Maybe it would be better to add a function for adjusting brightness and contrast. HDR is always looking  unnatural, fotofusion is a much better option imo.

**Comment by polarbearing** [comment]
3-letter acronyms can mean many things. Apparently we are talking about High-Dynamic-Range Imaging (HDRI or HDR).

**Comment by ireun** [comment]
@Peatsmoke I haven't noticed that. If course images taken with HDR enabled can look unnatural --> Google Graphics, but on my phone it really looks better, with higher range of colors.

@polarbearing Yes we do. :)

**Comment by jfburke3** [comment]
In the right lighting, HDR pics look great on my phone, too, but it *has to* be the right lighting.  IF this is implemented, there should probably be a button on-screen in camera mode to switch it on/off on the fly.  Not sure how feasible this really is....

**Comment by iav** [comment]
Case when HDR will be fine: http://mapillary.com/map/im/JQabIPhTucAIL8GD32DFSQ
Light sky, very dark all that interesting.
But there is a catch: currently most shots called "HDR" makes as a sequence of shots with different settings. This technology can't be used with moving camera.

Problem with sun or light sky can be solved by disabling all types of "auto-balance", and hard pin aperture and get overexposure for sun, clouds and sky.

**Comment by peterneubauer** [comment]
Not fixing.

**Comment by kaitu** [comment]
Any chance that offering the possibility of turning on HDR mode might be reconsidered in newer versions of the app?

At least in walking manual and panorama mode, keeping the camera steady while shooting a burst of images shouldn't be a problem. I'd like an option to activate HDR also in walking auto-shot mode, since I often use this mode for manual shooting (for single hand operation, I just find it more convenient to activate the shutter by controlling the device orientation than by pressing a button).
