### ISSUE TITLE
always reset zoomlevel when going to another photo

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#703]
I still have to encounter the first situation where it's useful to keep the zoom when going to another photo.
This request is for both the map view and the traffic sign game.

**Comment by knikel** [comment]
@de-vries This issue is strongly a matter of preference/usage and some people prefer to have it different way. Therefore, the navigation arrows stay when zoomed in (#356) and there is a 'reset-zoom' button when zoomed in (see #517, applies also to the traffic game). It's one extra action, but hopefully it should cover your use scenario :).

**Comment by dekarl** [comment]
@knikel, while I do understand this issue being a matter of preference for the map view I do not think the same holds true for the traffic game, where you get a random unrelated image every time.
I (may) have been removing (maybe) valid detected signs because I was surprised by being still zoomed in when switching to a completely unrelated picture. I'd appreciate if you could reconsider the behaviour in the traffic game.

**Comment by knikel** [comment]
@dekarl this is a very good point. I'll fix it to behave the way you described it in the traffic game. Thanks for the feedback!

**Comment by knikel** [comment]
Fixed, will be visible soon :)
