### ISSUE TITLE
Keep sign edior controls always on screen and correct size

### ISSUE THREAD

**Issue by iav** [mapillary/mapillary_issues#717]
Currently in sign editor controls placed in bottom left corner of image, and zoomed in and out with image. Size and place should be binded to window, not to image itself.

**Comment by waldyrious** [comment]
The red overlay should also always appear within the visible part of the image even when zoomed, rather than always at a fixed size in the center of the (fully zoomed-out) image.

Note that the sign selection dialog does behave as expected in this regard, so the geometry code should already be implemented and adaptable to the controls and overlay :)

**Comment by waldyrious** [comment]
This has been mentioned in #633 by the way:

> The size of the red box should be relative to the size of the frame it's rendered in, not to the image. in other words: when zoomed in the red box should be smaller. if you zoom a lot the red box can become bigger than the frame. When I zoom it's always to tag a small/distant sign anyway.

**Comment by gyllen** [comment]
Fixed
