### ISSUE TITLE
G-sensor too sensitive (flipped pictures)

### ISSUE THREAD

**Issue by sanderd17** [mapillary/mapillary_issues#722]
From yesterday's test ride, it appears that the G-sensor is too sensitive.

It's understandable that the force-field changes when I hit a bump with my bike, but in some cases, that causes the picture to flip.

There can be multiple solutions for this problem, like allowing to fix the orientation in the settings, or averaging the forces over the last few seconds (people normally don't turn their device while recording).

See some examples:
http://www.mapillary.com/map/im/QDiJkTJMx-Sjlo6JGrGoNw
http://www.mapillary.com/map/im/nzxHUD8NV2dOqk_TH2TinQ
http://www.mapillary.com/map/im/1PwBx7n4cisRRAL95Cyahw

**Comment by ybkuang** [comment]
@sanderd17, Good suggestions! It is on our to-do list to fix this in the processing backend i.e. correct the image orientation based on the orientation statistics of a sequence.

**Comment by flohoff** [comment]
I have the same problem - I tried using an app which locks the orientation. This works for the application itself but not the image orientation. Currently i upload all images and later flag them as beeing rotate but this is most likely a very broken workflow. Typically i mount the mobile on my bike in the same orientation so i'd like to lock the orientation.

I typically have all other picture take inhibitors turned off e.g. face down, shake, tilt etc because the vibration is so intense but minimal that otherwise the mobile fixed to the bike will not take a single image.

**Comment by ybkuang** [comment]
Referring this to #531
