### ISSUE TITLE
Limit to zoom function in game

### ISSUE THREAD

**Issue by Peatsmoke** [mapillary/mapillary_issues#736]
Maybe there should come a limit to the zoomfunction in the game. Some users zoom in at maximum to find the smallest signs on the screen. Now there are signs tagged, wich nearly aren't visible at all, so imo this don't help recognisation traffic signs.
Please let me know if I'm wrong with this opinion!

**Comment by HolgerJeromin** [comment]
please dont limit zoom but size of the sign marker.

**Comment by iav** [comment]
Please don't limit zoom.
If man can recognize a sign - it is recognizable.

**Comment by Peatsmoke** [comment]
Technically you will be right, but the consequence of this behaviour and way of tagging is the fact that traffic-signs are getting multiple displayed on places where they don't excist.

**Comment by pyrog** [comment]
@Peatsmoke 
> traffic-signs are getting multiple displayed on places where they don't exist.

Your right :smile: but the goal is to help to improve the vision engine.

Maybe, the "rules" of the "game" should be clarified:
* tag only traffic signs in the main way, and at a maximal distance?
* remove only false detections?
* …

**Comment by iav** [comment]
> traffic-signs are getting multiple displayed on places where they don't excist.
There is another big problem to the future - all signs located not there point of shot. And any sign can be shoted not only many times in one sequence, but in many sequences, abd on many directions.
To merce lot of recognized signs into one sign, and determination of a true geo position - huge quest.

And no need to make it harder then it is by remove of possibility to mark more shots - or to remove some signs, that can be regognized only on bug distance because track coverage much, much smaller than 10000% (100 tracks on every point).

**Comment by HolgerJeromin** [comment]
@iav both will be solved by https://github.com/mapillary/OpenSfM which will position the signs in the 3D space.

**Comment by gyllen** [comment]
@HolgerJeromin you are right, more fun stuff is coming up. closing
