### ISSUE TITLE
Cross-Origin Request Blocked in Traffic Sign Game

### ISSUE THREAD

**Issue by lokal-profil** [mapillary/mapillary_issues#746]
In Firefox running the Traffic sign game triggers a lot of "Cross-Origin Request Blocked". Intermittently this stops the webpage from loading completely or from saving of changes to occur.

Specifically it's:
* https://a.mapillary.com (v2 api)
* http://www.mapillary.com (favicon)

**Comment by lokal-profil** [comment]
Clarification: The favicon is a "mixed insecure content" warning (since it's not on https). It's a.mapillary that is creating the load/save issues.

**Comment by gyllen** [comment]
We are looking inot this issue at the moment.

**Comment by iav** [comment]
Trying to browse photos hawing roadsigns on I see it with firefox, on url http://www.mapillary.com/map/im/q1P5x3-aMEL-q0sy4MMuMw in error log:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://a.mapillary.com/v2/u/iav/connections?client_id=MkJKbDA0bnZuZlcxeTJHTmFqN3g1dzo1YTM0NjRkM2EyZGU5MzBh&match_type=1. This can be fixed by moving the resource to the same domain or enabling CORS.

**Comment by gyllen** [comment]
Should now be fixed
