### ISSUE TITLE
Use GPS info from images to prevent recognition of traffic signs from wrong continents

### ISSUE THREAD

**Issue by rudolfmayer** [mapillary/mapillary_issues#808]
To prevent having to fix traffic signs that are wrongly tagged as reported in #806, it would be good if the traffic sign recognition algorithm would outright exclude improbable traffic signs.

This, if I am uploading images taken e.g. somewhere in Europe, the engine should *only* try to recognise signs that are known to be used there, and *not* tag a traffic sign that is used only in the US (and other completely different places, once you recognise them). I guess with this simple approach you could exclude a huge number of false positives in your recognition.

**Comment by ybkuang** [comment]
@rudolfmayer Thanks for the suggestion. 

Right now, we have EU and US detector packages which are run separately for images in EU and US. So ideally, this should not happen. We tested the US package for Australia and South American countries (since they share similar signs), do you have images from those regions?

**Comment by rudolfmayer** [comment]
Ok, that might explain, I have images from both Australia & Brazil.

**Comment by ybkuang** [comment]
Yup, it must be that. We are currently working on expanding the detection to other regions. GPS will be used to guide what package to use in different regions. 

Anyways, this is a bug that the signs shown as US signs. Will fix when we deploy the new detection packages.

**Comment by ybkuang** [comment]
Closing this. Referring to #806.
