### ISSUE TITLE
Waiting for Better Location Fix

### ISSUE THREAD

**Issue by tacman** [mapillary/mapillary_issues#81]
I'm running on my Note 3, and I thought it was taking pictures in Walking mode, but wouldn't take in Panoramic, kept giving me the message "Waiting for Better Location Fix".  I was outside and had GPS and Wifi on, and going to Google Maps showed me in the right spot.

I'll try again later, when I've been outside longer, maybe it just takes a while to sync with the GPS?

**Comment by ViriatoLusitano** [comment]
Hey all,

I'm currently experiencing this exact issue, thing is Mapillary can't seemingly get any GPS signal.

The status is always black 0/0/0m (very rarely 0/1/0m) and I've checked many times if the GPS was activated and its use accepted by the application.

I don't understand why I can get signal on Google Maps and OSMand but not in Mapillary.

**Comment by CharlesNepote** [comment]
IMHO:
* [X] there is a "developper" [nerd] option that allow to "Skip location check" (good point): then we can be clean up sequences that have bad GPS in the editor.
* [ ] for the beginners, following @jaakkoh , limit for automatic shots could be raise up to 20-25m instead of 15m.

Accuracy information is in EXIF data, so, if images with 20m accuracy are not good, it will be easy for Mappillary to make changes in the future, for example :
* decide to hide this pictures except for their owner
* change editor UI to alert the users that is images have a "not so good accuracy"
* suggest users to fix location for this images

My experience is that I was *really* disapointed in my very first tests that so many pictures were not taken due to the yellow GPS icon (with and accuracy of ~16m).

Now I know how to solve that with the "developper" option, but I think about all beginners who won't give a chance to Mappillary due to this issue.

**Comment by jaakkoh** [comment]
re: @CharlesNepote "My experience is that I was really disapointed in my very first tests that so many pictures were not taken due to the yellow GPS icon (with and accuracy of ~16m).
Now I know how to solve that with the "developper" option, but I think about all beginners who won't give a chance to Mappillary due to this issue."

That's what I'm afraid, too, might happen to too many.

**Comment by nighto** [comment]
This also happens in my Moto X (XT-1058), most of the times I try to use, even though I'm using GPS with apps such as OSMTracker or Strava, the signal quality is not good enough for Mapillary app and thus no (or very few) photos are taken. This is very frustrating. I'll try this developer settings and see how it goes.

**Comment by filipca** [comment]
I have made too many sequences already to correct them with the editor.  Anyway that little screen is too clumsy.  
I start and try to end my sequences at a crosspoint where the gps indicator becomes green.
And I also use an external gps under my hat.
