### ISSUE TITLE
Allow to rotate pictures when editing (web & app)

### ISSUE THREAD

**Issue by rudolfmayer** [mapillary/mapillary_issues#811]
Especially while biking, it seems that sometimes the sensors get shaken too much, and pictures are wrongly rotated, e.g. this one: http://mapillary.com/map/im/RQEcm7W_a39ur_FpSCFEOA

I can't find a way in neither the app nor the website to correct that. The only way is if a notice it early enough, and edit the image with a third-party tool before uploading.

**Comment by jesolem** [comment]
On iOS you can rotate before uploading. 

Rotating in editor is a huge operation that will require some work on our backend since we have to regenerate thumbnails and run detectors etc. we'll get there..

**Comment by wolfv** [comment]
Is it possible to delete the sequence and reupload them rotated? I added a few sequences and all are upside down... (e.g http://www.mapillary.com/map/im/2cI4_UegG7Q9G8Hn0MNIDA/photo)

**Comment by ybkuang** [comment]
@wolfv Yes. We will delete the 9 rotated sequences for you.

**Comment by peterneubauer** [comment]
What device are you using @wolfv ? There might be a bug in the Android app that we are working with to fix these.

**Comment by wolfv** [comment]
Nexus 5x and latest non-beta mapillary.

Cheers,

Wolf

**Comment by peterneubauer** [comment]
Yeah, that is the issue we are working with. We need to implement the Google Android Camera2 API, see https://github.com/mapillary/mapillary_issues/issues/1612

**Comment by ToeBee** [comment]
I ran into a problem today on my Galaxy S 5 where the Mapillary app randomly switched orientation on me in the middle of 3 sequences. This is the first time I've seen this. I guess I was holding the phone weird or something. I don't know. 

By mounting the SD card on a computer and inspecting the files I noticed that the only thing different about them was the "Orientation" EXIF tag was wrong (a value of 3 instead of 1). So I wrote a 1 line bash script to change it back on the pictures that had it flipped wrong:

```for i in *.jpg; do ORIENT=`exiftool -s -s -s -n -Orientation $i` && if [ $ORIENT = "3" ] ; then exiftool -Orientation=1 -P -n "$i"; fi; done```

Then I had to delete the backup files that exiftool made, remounted the card in the phone and the Mapillary app is now happily uploading those pictures in the correct orientation.

**Comment by peterneubauer** [comment]
Awesome!
The rotation exif tag is written by the camera itself so yes, probably
shaking and sensor confusion...

**Comment by ybkuang** [comment]
This is related to https://github.com/mapillary/mapillary_issues/issues/770. Closing this one.

**Comment by pbb72** [comment]
Not really related. #770 is about photos that are not perfectly horizontal (like 5-10 degrees off). The issue here is about incorrect rotation of the photo itself, in multiples of 90 degrees. (Most probably because of incorrect EXIF tags.) Two very different issues.
