### ISSUE TITLE
There is no RSS for latest uploads

### ISSUE THREAD

**Issue by elopio** [mapillary/mapillary_issues#843]
The page http://www.mapillary.com/map/latestuploads has no RSS feed.

It would be nice to have access to the latest uploads through a feed aggregator.

**Comment by jesolem** [comment]
Slow response, sorry. We're getting ~100k photos per day, would this really be readable/useful in a RSS reader?

**Comment by elopio** [comment]
I think it would be. I would specially like the RSS for my photos, which are closer to 100 per week.

**Comment by jesolem** [comment]
There is a person specific feed https://www.mapillary.com/profile/USERNAME/activity (also in your app) and you can subscribe to feeds of geographic regions (subscribe at https://www.mapillary.com/map/settings/notifications) that also show in your feed and in the app. 

Closing this as we will work in the direction above for other interesting things to follow instead of RSS.
