### ISSUE TITLE
No reaction to flagging

### ISSUE THREAD

**Issue by voschix** [mapillary/mapillary_issues#874]
It seems that  the Mapillary team's  reaction time to flagged requests is very long (or there is an error).
I flagged, several times this image
    Image Key: _pp4NkJ0hNQ3NX9A_O4SBg
   Sequence Key: 0nL_Kkn9jAteDSmIpRsZIg 
with the request to split the sequence there 
(because the entire sequence to the west of this requested split has then to be removed  as all positions are completely wrong)
No reaction for weeks now.

**Comment by AllenGraetz** [comment]
I'm not sure they built the sequence cut function for that.   

One option would be to go to each image in the sequence you don't want shown and hide it.  Just click on it's ballon, then the hide image button and the next image.  Each one hidden will change color.  When you've got them all make sure to save/send the request.

http://screencast.com/t/UzcvsSGKvQ

**Comment by voschix** [comment]
Thanks. I am aware of the manual method. I wanted to avoid it, because it's slow and tedious. 
My message has two aspects: 
1) the flagging does not work in the sense that apparently these requests are ignored at present. 
2) the second one is technical as explained. In this particular example it regards the sequence of someone else (I want to remove it, as it has obviously completely wrong GPS data),  but I have the same need with some of my own sequences, where I would like to remove part of a sequence, as it's poor quality and I now have better footage to replace it.

**Comment by AllenGraetz** [comment]
THank you, that makes sense.

**Comment by travel193** [comment]
Hi @voschix ,
Any image you flag is being actioned apart for requests for rotation as we need to make considerable changes in the backend to get this up and running. The wait to have an image or sequence actioned should currently not take longer 48 hours.

The reason the sequence cut you requested hasn't gone through would be either because the distance between images is less than 300m or a backend issue we are having with sequence cuts. We will have to investigate this. As you may have seen with issue [1012](https://github.com/mapillary/mapillary_issues/issues/1012), we have a lot to do to improve the change editor. Part of this will be allowing sequence cuts where images are less than 300m apart.

Sorry for the inconvenience. We will notify everyone of updates to the editor via the blog and newsletter.

**Comment by travel193** [comment]
Hi @voschix ,
We are still working on the sequence cut aspect of this. Please follow progress for [issue 732](https://github.com/mapillary/mapillary_issues/issues/732).
See [issue 439](https://github.com/mapillary/mapillary_issues/issues/439) for our progress with rotating flagged images.
Thanks

**Comment by GITNE** [comment]
Unfortunately, this **is** **still** a major issue. :-( Flagging still does not work as intended. Additionally, there is no confirmation or error massage displayed on the website after sending a flag report.

@Mapillary: People, you **really** need to get going! You are just too slow for the task at hand. This whole project has clearly outgrown yourselves. Perhaps even your competence to master such a project properly?
I am not say this to hurt or smear you. I am saying this because you really need to wake up and hear the call! There are a lot, and I mean really a lot of issues on your plate and most people get the feeling that you are not reacting adequately. I do not know how many potential users you have lost by now because of this. I hope not many. But, this is not what you should bet on.
