### ISSUE TITLE
Video upload: Make it easy to jump 1 hour when setting location

### ISSUE THREAD

**Issue by smsm1** [mapillary/mapillary_issues#899]
Quite often the problem with the time on the videos, is that they were recorded in the wrong timezone, or daylight savings etc, thus being able to jump 1 hour would make it easy to get to roughly the correct location.

**Comment by ToeBee** [comment]
I would definitely like some kind of time-based input for fine positioning control. The problem with the map as it is implemented now is that it will only let you drag the marker to the nearest trackpoint, not to an arbitrary point along the trace. My older Garmin cycle computer has limited memory so it only records a trackpoint when one of the tracked parameters changes. So it could be over a hundred meters between trackpoints. This means that to accurately position the video I have to identify a landmark that also happens to be near a trackpoint and then repeatedly seek and pause until I can get the video paused in the exact location that a trackpoint was captured and *then* I can use the map to drag the marker to the appropriate trackpoint. It would be much easier if I could either step through the video with single second control or be able to manually manipulate the time difference.

**Comment by paulinus** [comment]
@ToeBee We've just updated the video upload page so that markers can be moved more precisely.

@smsm1 I see your need for directly editing the video time. Unfortunately, we are trying to rely as little as possible in the video time since it is showing to be very unreliable. Sources of error include

- time-zone differences between video and gpx (as in your case)
- clocks being un-sync by seconds or minutes, 
- and video time being the time the file was copied to the computer instead of the video time.

We are trying to find a simple interface that works for most cases. Right now, when we can detect a big sync issue, we are moving the video to the beginning of of the gpx track. So if you have timezone differences you will loose the original time of the video.
