### ISSUE TITLE
New sequence distance

### ISSUE THREAD

**Issue by VikDD** [mapillary/mapillary_issues#917]
Sory for my English, I will try to speak as I would say in Russian, but in English presentation.
After some uploads I see, what my images in it own sequence, it happened because I set "New sequence min distance" setting to 3m, but literaly it mean "Begin sequence only when your location more then Xm".  I thought that these settings to continue sequence after an interruption GPS signal (jumps depend on the device and can be significant), but, de-facto, in application it mean "Start new sequence  after Xm". May be you change setting name and/or add new?

**Comment by yopaseopor** [comment]
It can be worst.Yesterday my app made a trip of +200km , +1500 pics ...with +1500 tracks... l0l .It spread the map with 1500 points with no connection between them (It only began to work as a unique track when I stopped the smartphone (it begans to be so hot) -Xperia Z3 Android 5.0.2 - and reinitiate the app).I have tried to upload them from a unique folder but there is some data made to the pic so app uploaded in +1500 tracks instead of a unique folder to uploaded it.This error started when I have did the trip by plane (landing and take off from BCN and MUC) last month.I had think it was because there's no flight mode and the speed is so fast between points of GPS. Yesterday I have discovered that no.It is a dissapointing thing because in that way play button...doesn't work too, it doesn't jump to the next pic (I can do it on my pc).

**Comment by peterneubauer** [comment]
Yup, sorry for the wording, it should really say "Maximum distance that consecutive pictures can be apart before the sequence is stopped and a new one is started automatically". Would that work?

**Comment by yopaseopor** [comment]
For me yes, the question now is how can I join 1500+ sequences of one pic?

**Comment by peterneubauer** [comment]
Right now you can't.

We are going to implement some manual support for it in the editor next
version, and possibly expose an API together with editing other EXIF data
like lon/lat. That way, you could programmatically add other pics to an
existing sequence.

Good input.
