### ISSUE TITLE
Change capture button in app

### ISSUE THREAD

**Issue by HolgerJeromin** [mapillary/mapillary_issues#919]
The android app has a light blue button on idle (what does blue mean?) and a red button while taking a sequence.
I am regularly confused about the state of the camera. Therefor i propose a change.
Idle status:
Green round circle with the word "Go!" in the middle. [example](http://www.ourclassweb.com/images/scrappin_doodles/happy_cars_collection/go_sign.png)
While mapping:
Red octagon with the word "Stop" in the middle. Just like the [stop sign](http://commons.wikimedia.org/wiki/File:Vienna_Convention_road_sign_B2a.svg)

Then we would have the shape, word and color to indicate the status. This is good for example for color blind people.

**Comment by pbb72** [comment]
Personally, I don't think the blue color is so much the problem (the default Android camera also uses blue, I think), though I think green would also be a very good color. But the problem I think is that the red button is ambiguous. For some people, red means "start recording" (the record button on most physical recording devices is red), for other people it means "stop whatever you're doing" (as Holger suggests).

But Holger is correct that color alone is not enough to explain the function of the button, it must be supplemented by shape or text. I think a better choice for the stop button would be a black square.

But note that all color buttons (and icons) must have a contrasting border, or else they will disappear when the camera image behind the button happens to be the same color!

**Comment by rikahlberg** [comment]
I concur with this request, though I have this problem in the iOS app so you may want to tag it for that platform as well.

I do a lot of photography and video on the iPhone, and EVERY app I use has a RED button to indicate to START recording. Except for Mapillary. So I often find myself hitting the red button (thinking it means record) and ending my sequence.

You may want to make this platform specific so that the interface follows the users expectations of its native apps. Just look at how the iOS camera handles this for an example.

**Comment by peterneubauer** [comment]
out with the next release. Thanks!

**Comment by HolgerJeromin** [comment]
The Start and Stop in the new version is very nice. Thanks!

**Comment by peterneubauer** [comment]
Yay!
