### ISSUE TITLE
Navigation arrows are in wrong direction

### ISSUE THREAD

**Issue by pyrog** [mapillary/mapillary_issues#930]
When Camera is not pointing at **0 degree** to the forward direction, navigation arrows orientation is false.

In this example, the angle is 90° and arrows should be left/right not up/down.

[![navigation arrows in wrong direction](https://cloud.githubusercontent.com/assets/2158081/7224500/84ca6752-e733-11e4-86a4-c491f24bff53.png)
F_e4pumkuOE9dQ0WCjsuGw](http://www.mapillary.com/map/im/F_e4pumkuOE9dQ0WCjsuGw)

**Comment by pbb72** [comment]
Hey, familiar photo! ;-)

I agree. This problem is connected to the fact that the left/right arrows in Mapillary are commonly used to rotate, instead of panning. Pressing the left arrow, jumps to a nearby image that is circa 90 degrees rotated to the left, instead of jumping to an image that is situated to the left.

Can't link to any good examples now, because I am getting constant timeouts in the web interface.

**Comment by ybkuang** [comment]
The navigation in the current viewer should fix most of these problems. We are also working on an improved version of the viewer. Closing this now.
