### ISSUE TITLE
Map is not shown for specific path - several 404's

### ISSUE THREAD

**Issue by simonmikkelsen** [mapillary/mapillary_issues#981]
When I go to see a specific route (I have added) on the map, it does not work. Looking at the console, I see the following errors (in Chromium):

Failed to load resource: the server responded with a status of 404 (Not Found)
https://a.mapillary.com/v2/s/QHAtemvUvzqcfMARym7pNg?client_id=[removed by reporter]
Failed to load resource: the server responded with a status of 404 (Not Found)
d1dk9tvuiy3v51.cloudfront.net/javascripts/angular-sanitize.min.js.map:1
GET http://d1dk9tvuiy3v51.cloudfront.net/javascripts/angular-sanitize.min.js.map 404 (Not Found)

**Comment by simonmikkelsen** [comment]
The link: http://www.mapillary.com/map/s/qviTSA9S_X-o_JGMzhZCCA is an example of a page that show this error.

**Comment by gyllen** [comment]
Where did you get this link from?

**Comment by gyllen** [comment]
This is a sequence that is still processing in our system. We have had some delays lately because of a huge import and some server upgrades. Please reopen this issue if sequence is still not there by tuesday. Sorry for the inconvenience and please know that we are doing everything we can to support the fast growing mapillary community. Today we are having upload rates we never could have dreamed of when we started out on this adventure. Hopefully you will also keep on uploading :)

**Comment by pyrog** [comment]
> We have had some delays lately because of a huge import and some server upgrades

:bulb: Display a message: **"Server upgrade in progress…"**

>Today we are having upload rates we never could have dreamed

I hope you will have it again :smile:

**Comment by simonmikkelsen** [comment]
Such a status page would be really cool. Of cause there will be delays and down time, especially in this relatively early phase.

I got the link from my feed: http://www.mapillary.com/profile/tryl/activity where an image links to it with the text "2 days ago
tryl had 46 photos added on the map" (the one with the pointer over it).

So the text indicates the images are fully processed, but that might not be the case?

![image](https://cloud.githubusercontent.com/assets/8446338/7446107/6823ffec-f1cd-11e4-96e4-82c7892182c7.png)

**Comment by gyllen** [comment]
@simonmikkelsen Is this still an issue? We are working on a status page now by the way.
