### ISSUE TITLE
Name elements in photo

### ISSUE THREAD

**Issue by oldschoolBavarianReferenceSystem** [mapillary/mapillary_issues#984]
Add the possibility to tag elements in the photos and name it.

For example, if you see a famous building, mark it (either by point or better by polygon) and name it. Add semantic identity by linking to the Wikipedia article.

Automatically spread information into overlapping photos by SfM.

**Comment by jesolem** [comment]
Great idea. Not something we can do short term though. Adding to the list.

**Comment by HolgerJeromin** [comment]
For details in linking you can look at the links from openstreetmap to wikipedia.
http://wiki.openstreetmap.org/wiki/Key:wikipedia#Using_Wikipedia_links
for example "include a language prefix, 'en:St Paul's Cathedral', (en: for English, in that case) rather than assuming any particular language as with 'St Paul's Cathedral'."
The Editor iD handles this nicely with js code, so this can be used as inspiration.

**Comment by pbb72** [comment]
This could be done automatically. All photos are tagged with location and direction, so it's relatively easy to decide if a certain building should be visible. Possibly combine this with some image recognition routines, recognizing similar building shapes in nearby photos. Information on landmarks and their Wikipedia articles can be retrieved from OSM...

In fact, every photo could have links to all OSM objects that are visible in the photo.

**Comment by de-vries** [comment]
> In fact, every photo could have links to all OSM objects that are visible in the photo.

like [this](https://github.com/mapillary/mapillary_issues/issues/176#issuecomment-74644622)?

**Comment by Skippern** [comment]
Actually when a landmark is recognised in one photo, because of the georeferences in all Mapillary photos, the object could easilly (automagically) be added to other photos of it. Than, with an archive of recognised landmarks, this could be searched, and together with cardinals one could search for i.e. photos of **Empire State building as seen from south** or photos with **Empire State building and Chrysler building**, just as examples.

**Comment by epsg31468** [comment]
de-vries,

yes, like in the screenshot you linked to. Great!

**Comment by jesolem** [comment]
Will look into options. My preference would be to use visual matching but that requires some work.

**Comment by pbb72** [comment]
Either solution has it's problems. A small error in the compass direction has a big influence on determining what could be visible in the photo (at least at shorter distances), and not every landmark has a clear visual appearance.

**Comment by Skippern** [comment]
If Empire State Building is recognised in multiple photos, but position doesn't match than that would indicate that one or more of the photos have compass mismatch, over time this can be an aid in correcting compass bearing of photos, it might be that complete sequences are a few degrees off, and such landmark recognition  can be an aid to correct that

**Comment by jesolem** [comment]
Closing since we now launched tagging.

**Comment by oldschoolBavarianReferenceSystem** [comment]
Nice, this is a very good start!
Of cause, there are improovements as mentioned in the Blog article. For example the custom tags would be very nice. Translations is another. Explanatory text of the tag.
